import { Case } from "@/types";

export const corporatePoisonCase: Case = {
  metadata: {
    id: "CASE-004",
    title: "The Corporate Poison",
    description:
      "CEO Daniel Park collapsed during a board meeting at Meridian Tech's Manhattan headquarters. Cause of death: thallium poisoning administered over several weeks. The poison was in his daily green tea — prepared by his personal assistant. Four people had access to his office. One of them laced his tea. The board is in chaos. A $3B merger hangs in the balance.",
    difficulty: "medium",
    location: "Meridian Tech, 55 Hudson Yards, New York",
    date: "November 12, 2024",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "murder",
  },
  victim: {
    name: "Daniel Park",
    age: 51,
    occupation: "CEO, Meridian Tech",
    description:
      "Visionary tech CEO who built Meridian from a startup to a $20B company. Known for his charisma and ruthless business tactics. Was pushing through a controversial merger with Nexus Industries that would make him a billionaire but dilute employee stock options. He was beloved by investors and feared by rivals.",
    causeOfDeath: "Thallium poisoning — cumulative doses administered over 3-4 weeks",
    lastSeen: "9:55 AM, collapsing in the 38th floor boardroom",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Amy Chen",
      age: 29,
      occupation: "Executive Assistant to Daniel Park",
      relationshipToVictim: "Personal assistant for 3 years",
      motive:
        "Daniel discovered Amy had been leaking internal documents to a competitor. He confronted her the day before his death and threatened to have her arrested. Amy's visa status depends on her employment — deportation would follow a criminal charge.",
      alibi: "I prepared Daniel's tea at 7:30 AM as usual. I was at my desk the entire morning.",
      alibiVerified: true,
      knownLocations: [
        "Meridian Tech — 38th floor reception",
        "Break room (7:30 AM for tea preparation)",
      ],
      communicationHistory: [
        "7:15 AM — Called her brother in Shanghai (5 min)",
        "10:02 AM — Called immigration lawyer (no answer)",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-03", "EVIDENCE-07"],
      suspicionScore: 78,
      personality:
        "Quiet, efficient, deeply stressed. Fiercely protective of her family. Under immense pressure from immigration requirements. Not naturally devious but pushed to a breaking point.",
      secrets: [
        "Was being blackmailed by someone at Meridian to leak documents",
        "Has a hidden USB drive with all the leaked files",
        "Knows the tea preparation was the delivery method",
      ],
      truthfulStatements: [
        "I prepared the tea at 7:30 AM.",
        "Daniel did confront me about the leaks.",
      ],
      lies: [
        "I have no idea how the poison got in the tea. (She found the thallium residue on the tea tin lid and wiped it off — but traces remain)",
        "No one else had access to the tea. (She saw Kevin enter the break room that morning)",
      ],
      refusesToDiscuss: [
        "The leaked documents",
        "The blackmail",
        "The USB drive",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Kevin Park",
      age: 26,
      occupation: "VP of Product — Daniel's protégé",
      relationshipToVictim: "Daniel's nephew and mentee",
      motive:
        "Kevin was set to become CEO after the merger — Daniel had promised him the role. But Daniel recently changed his mind, planning to bring in an outside CEO. Kevin's entire career trajectory was about to collapse publicly.",
      alibi: "I was in the product team standup at 8:00 AM. Then I was in my office until the board meeting.",
      alibiVerified: false,
      knownLocations: [
        "Meridian Tech — 38th floor (product team area)",
        "Daniel's office (visited briefly at 8:15 AM)",
      ],
      communicationHistory: [
        "8:00 AM — Standup with product team",
        "8:15 AM — Texted Daniel: 'Can I grab the updated board deck?'",
        "9:30 AM — Texted his girlfriend: 'Today is the day everything changes'",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05", "EVIDENCE-09"],
      suspicionScore: 60,
      personality:
        "Ambitious, charming, knows how to work a room. Genuinely admired Daniel but his admiration curdled into resentment when the CEO promise was broken. Can be manipulative when cornered.",
      secrets: [
        "Visited Daniel's office and had access to the tea cup at 8:15 AM",
        "Has been meeting with Nexus Industries behind Daniel's back",
        "Daniel's last email to him was: 'We need to talk. My office. Now.' — sent at 9:40 AM",
      ],
      truthfulStatements: [
        "I did visit Daniel's office at 8:15 AM.",
        "Daniel was planning to bring in an outside CEO.",
      ],
      lies: [
        "I never touched Daniel's tea. (His fingerprints are on the tea cup — he claims he only picked it up to move it)",
        "Daniel and I were fine. (They had a heated argument two days before the death)",
      ],
      refusesToDiscuss: [
        "The Nexus Industries meetings",
        "The broken CEO promise",
        "Daniel's final email to him",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Dr. Sarah Okonkwo",
      age: 47,
      occupation: "Meridian Tech — Chief Medical Officer",
      relationshipToVictim: "Daniel's physician and board member",
      motive:
        "Daniel discovered Sarah had been approving fake medical leaves for board members to manipulate stock trades. He threatened to remove her from the board and report her. Sarah's medical license would be at risk.",
      alibi: "I was in a telehealth consultation from 7:00 AM to 8:30 AM. Then I went to the office.",
      alibiVerified: true,
      knownLocations: [
        "Home (telehealth until 8:30 AM)",
        "Meridian Tech — 36th floor medical suite (from 9:00 AM)",
      ],
      communicationHistory: [
        "8:35 AM — Called Daniel (missed call, no voicemail)",
        "9:15 AM — Texted board member: 'The vote today is critical. We need you there.'",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-06", "EVIDENCE-11"],
      suspicionScore: 55,
      personality:
        "Brilliant, commanding, uses her medical authority to deflect suspicion. Passionate about the company but willing to bend rules for what she believes is the greater good.",
      secrets: [
        "Has a medical supply cabinet with thallium compounds (used in research)",
        "Was having a secret relationship with a board member",
        "Accessed the company's poison database 2 weeks before Daniel's symptoms started",
      ],
      truthfulStatements: [
        "I did have a telehealth consultation that morning.",
        "Daniel and I disagreed about the board leaves.",
      ],
      lies: [
        "I never accessed the poison database. (System logs show her credentials accessed it)",
        "I have no medical reason to access thallium. (Her research lab request was denied 6 months ago)",
      ],
      refusesToDiscuss: [
        "The poison database access",
        "The board member relationship",
        "The denied research lab request",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Marcus Webb",
      age: 55,
      occupation: "COO, Meridian Tech",
      relationshipToVictim: "Co-founder and business partner",
      motive:
        "Marcus and Daniel co-founded Meridian, but Daniel systematically reduced Marcus's authority over 5 years. The merger would make Daniel the sole power center. Marcus would be reduced to a figurehead. His 15% company stake would be diluted to 8% post-merger.",
      alibi: "I was in my office reviewing merger documents. I walked to the boardroom at 9:45 AM for the meeting.",
      alibiVerified: false,
      knownLocations: [
        "Meridian Tech — 38th floor COO office",
        "Break room (8:45 AM — observed getting coffee)",
      ],
      communicationHistory: [
        "7:00 AM — Called his lawyer: 'How does the merger affect my stock?'",
        "8:45 AM — Texted Nexus CFO: 'Looking forward to the close'",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-08", "EVIDENCE-10"],
      suspicionScore: 62,
      personality:
        "Old-school executive, views the company as his birthright. Resentful but controlled. Would rather destroy something than let someone else have it. Deeply loyal to the original vision of Meridian.",
      secrets: [
        "Has been secretly negotiating a severance package that would pay him $50M if Daniel dies",
        "Was seen near the break room at 8:45 AM — outside his usual pattern",
        "Daniel's security team flagged Marcus for entering Daniel's office without an appointment 3 times in the last month",
      ],
      truthfulStatements: [
        "I was reviewing merger documents.",
        "I did walk to the boardroom at 9:45 AM.",
      ],
      lies: [
        "I never went near Daniel's office that morning. (Security log shows his badge near Daniel's office at 8:42 AM)",
        "The merger is fine with me. (He's been fighting it privately for months)",
      ],
      refusesToDiscuss: [
        "The severance package",
        "The badge access near Daniel's office",
        "His private opposition to the merger",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Lisa Tran",
      age: 33,
      occupation: "Board Meeting Coordinator",
      relationshipToVictim: "Organized the 10:00 AM board meeting",
      statement:
        "Daniel arrived at 9:55 AM with his tea. He seemed tired but focused. He took two sips during his opening remarks. At 9:58 AM he paused, touched his throat, said 'something tastes off,' and collapsed. I called 911 immediately. His tea cup spilled — I noticed the tea had a slightly metallic smell.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-03"],
      personality: "Efficient, detail-oriented, traumatized by witnessing the collapse.",
    },
    {
      id: "WITNESS-02",
      name: "Ben Carter",
      age: 40,
      occupation: "Meridian Tech Security Manager",
      relationshipToVictim: "Head of executive floor security",
      statement:
        "The 38th floor has badge access logs. I can tell you everyone who swiped in that morning: Amy at 7:15, Kevin at 7:55, Marcus at 8:40, Daniel at 8:50. Dr. Okonkwo arrived via the elevator from the 36th floor at 9:05. No one else accessed the 38th floor between 7:00 AM and 10:00 AM.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-12"],
      personality: "Thorough, takes security seriously, frustrated by the incident happening on his watch.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "38th Floor Break Room",
      type: "Room",
      address: "Meridian Tech, 38th Floor",
      description:
        "Executive break room with high-end tea station, coffee machine, and Daniel's personal tea tin (specialty oolong from Taiwan). Only executives and their assistants have access.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-03"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02"],
    },
    {
      id: "LOC-02",
      name: "Daniel's Office",
      type: "Room",
      address: "Meridian Tech, 38th Floor",
      description:
        "Corner office with a private entrance. Contains Daniel's desk, personal items, and a mini-fridge with his tea supplies. The office door was open throughout the morning.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-05"],
      relevantSuspects: ["SUSPECT-02", "SUSPECT-04"],
    },
    {
      id: "LOC-03",
      name: "Boardroom",
      type: "Room",
      address: "Meridian Tech, 38th Floor",
      description:
        "Glass-walled boardroom with 12 seats. The table has a central microphone system. Daniel collapsed here at 9:58 AM.",
      relevantEvidence: ["EVIDENCE-01"],
      relevantSuspects: [],
    },
    {
      id: "LOC-04",
      name: "Medical Suite",
      type: "Room",
      address: "Meridian Tech, 36th Floor",
      description:
        "Dr. Okonkwo's medical suite. Contains general medical supplies and a locked cabinet with controlled substances for employee health programs.",
      relevantEvidence: ["EVIDENCE-04", "EVIDENCE-11"],
      relevantSuspects: ["SUSPECT-03"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-004",
      title: "Tea Cup — Thallium Residue",
      category: "forensic",
      description:
        "Daniel's tea cup, recovered from the boardroom floor, contained trace amounts of thallium sulfate. The concentration in the remaining tea was consistent with a single heavy dose. The tea tin in the break room also showed trace thallium on the inner lid, suggesting the poison was introduced to the tin, not the cup directly.",
      timestamp: "2024-11-12T11:00:00",
      location: "Boardroom / Break Room",
      source: "Forensic Toxicology",
      reliability: "high",
      metadata: {
        Substance: "Thallium sulfate",
        Concentration: "Lethal — single dose in cup",
        TinResidue: "Trace on inner lid",
        CupFingerprints: "Daniel, Amy",
        Conclusion: "Poison introduced to tea tin",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-07"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-004",
      title: "38th Floor Badge Access Logs",
      category: "digital",
      description:
        "Badge access logs for the 38th floor on November 12: Amy Chen — 7:15 AM, Kevin Park — 7:55 AM, Daniel Park — 8:50 AM, Marcus Webb — 8:40 AM (badge near Daniel's office), Dr. Okonkwo — 9:05 AM. Marcus's badge was also recorded near the break room at 8:45 AM.",
      timestamp: "2024-11-12T08:40:00",
      location: "38th Floor Access System",
      source: "Security Badge System",
      reliability: "high",
      metadata: {
        Amy: "7:15 AM — reception desk",
        Kevin: "7:55 AM — product team area",
        Marcus: "8:40 AM — Daniel's office vicinity, 8:45 AM — break room",
        Daniel: "8:50 AM — his office",
        Okonkwo: "9:05 AM — from 36th floor elevator",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-004",
      title: "Break Room Tea Station — Camera Footage",
      category: "cctv",
      description:
        "Break room camera shows: Amy at 7:30 AM preparing tea (normal routine). Kevin at 8:15 AM — enters break room, opens the tea tin, appears to inspect it, closes it. Marcus at 8:45 AM — enters, gets coffee from the machine, stands near the tea station for 30 seconds, then leaves. No one else approaches the tea station.",
      timestamp: "2024-11-12T08:15:00",
      location: "38th Floor Break Room",
      source: "Security Camera",
      reliability: "high",
      metadata: {
        Amy: "7:30 AM — tea preparation (routine)",
        Kevin: "8:15 AM — opens and inspects tea tin",
        Marcus: "8:45 AM — coffee, near tea station 30 sec",
        NoOtherAccess: "7:00 AM to 10:00 AM",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-02"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-004",
      title: "Dr. Okonkwo — Medical Supply Inventory",
      category: "document",
      description:
        "Dr. Okonkwo's controlled substance inventory shows thallium compounds (used in medical research) are tracked. The last formal request was denied 6 months ago. However, a physical audit of the cabinet reveals 1 fewer vial than the log indicates. The discrepancy was noted but not investigated.",
      timestamp: "2024-11-13T10:00:00",
      location: "Medical Suite, 36th Floor",
      source: "Medical Inventory Audit",
      reliability: "high",
      metadata: {
        Substance: "Thallium sulfate (research grade)",
        Discrepancy: "1 vial missing",
        LastRequest: "Denied 6 months ago",
        AccessLog: "Dr. Okonkwo — last physical access 3 weeks ago",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-004",
      title: "Daniel's Final Emails",
      category: "digital",
      description:
        "Daniel's email at 9:40 AM — 18 minutes before collapse — shows two critical emails: (1) To Kevin: 'We need to talk. My office. Now. — This CEO decision is final.' (2) To Marcus: 'I know about the severance negotiation. We're done.' Both emails were opened by their recipients before the collapse.",
      timestamp: "2024-11-12T09:40:00",
      location: "Daniel's Office",
      source: "Email Server Logs",
      reliability: "high",
      metadata: {
        ToKevin: "9:40 AM — 'CEO decision is final'",
        ToMarcus: "9:40 AM — 'I know about the severance'",
        KevinOpened: "9:42 AM",
        MarcusOpened: "9:43 AM",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-09", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-004",
      title: "Merger Financial Analysis",
      category: "financial",
      description:
        "The Meridian-Nexus merger would: make Daniel the largest individual shareholder (22%), dilute Marcus's stake from 15% to 8%, dilute all employee stock options by 30%, and trigger $50M in executive bonuses for Daniel's inner circle — excluding Marcus. Post-merger, Daniel's net worth would increase by $1.2B.",
      timestamp: "2024-11-10T00:00:00",
      location: "Financial Records",
      source: "Merger Analysis",
      reliability: "high",
      metadata: {
        DanielStake: "22% post-merger",
        MarcusStake: "15% → 8%",
        EmployeeDilution: "30%",
        MarcusBonus: "Excluded from $50M pool",
        DanielGain: "+$1.2B net worth",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-05"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-004",
      title: "Amy's Leaked Documents",
      category: "document",
      description:
        "IT security found that Amy accessed and downloaded 47 confidential files over 2 weeks, including board meeting minutes, merger terms, and Daniel's personal schedule. The files were transferred to an external USB. The access pattern suggests she was directed by someone inside the company — not an outside competitor.",
      timestamp: "2024-11-08T00:00:00",
      location: "Meridian Tech — IT Security",
      source: "Data Loss Prevention System",
      reliability: "high",
      metadata: {
        FilesLeaked: "47",
        Timeframe: "2 weeks",
        Device: "External USB",
        Recipient: "Traced to Meridian IP — internal leak",
        AccessPattern: "Directed by insider",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-01"],
      isRedHerring: true,
      importance: 5,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-004",
      title: "Marcus's Severance Negotiation",
      category: "document",
      description:
        "Emails between Marcus and his lawyer reveal he negotiated a $50M severance package triggered by Daniel's death or incapacitation. The package was drafted 3 months before Daniel's death. Marcus also had a life insurance policy on Daniel — $10M keyman policy through the company.",
      timestamp: "2024-11-01T00:00:00",
      location: "Legal Records",
      source: "Email Forensics",
      reliability: "high",
      metadata: {
        SeveranceAmount: "$50M — triggered by death/incapacitation",
        Drafted: "3 months before death",
        KeymanInsurance: "$10M on Daniel",
        PolicyType: "Corporate keyman",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-004",
      title: "Kevin's Nexus Meetings",
      category: "document",
      description:
        "Calendar records show Kevin met with Nexus Industries CEO 4 times in the past month — behind Daniel's back. One meeting was at a private restaurant. Kevin also had a LinkedIn message from Nexus CEO: 'Once the merger closes and Daniel steps aside, the CEO seat is yours. We've always valued your vision.'",
      timestamp: "2024-11-05T00:00:00",
      location: "Calendar + LinkedIn",
      source: "Digital Forensics",
      reliability: "high",
      metadata: {
        NexusMeetings: "4 in past month",
        RestaurantMeeting: "Private — 2 weeks before death",
        LinkedInMessage: "CEO seat promised by Nexus",
        DanielAware: "Yes — confronted Kevin",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-05"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-004",
      title: "Marcus's Office — Chemical Test",
      category: "forensic",
      description:
        "Swabs taken from Marcus's desk surface, keyboard, and phone show no thallium residue. However, his personal coffee mug (kept in his office) shows a faint thallium trace — consistent with cross-contamination from handling the tea tin in the break room at 8:45 AM.",
      timestamp: "2024-11-12T14:00:00",
      location: "Marcus's Office",
      source: "Forensic Analysis",
      reliability: "medium",
      metadata: {
        Desk: "No thallium",
        Keyboard: "No thallium",
        Phone: "No thallium",
        CoffeeMug: "Faint thallium — cross-contamination",
        Conclusion: "Handled contaminated object, not direct poisoning",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-01"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-004",
      title: "Dr. Okonkwo — Poison Database Access",
      category: "digital",
      description:
        "Company IT logs show Dr. Okonkwo's credentials accessed Meridian's internal poison database (used for workplace safety research) on October 28 — two weeks before Daniel's symptoms began. She accessed the thallium entry specifically, including dosage information and detection methods.",
      timestamp: "2024-10-28T00:00:00",
      location: "Medical Suite, 36th Floor",
      source: "IT Access Logs",
      reliability: "high",
      metadata: {
        Date: "October 28",
        Accessed: "Thallium entry — dosage and detection",
        Credentials: "Dr. Okonkwo",
        Purpose: "No logged justification",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-04"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-004",
      title: "38th Floor Hallway Camera — 8:15 AM",
      category: "cctv",
      description:
        "Hallway camera shows Kevin Park entering Daniel's office area at 8:15 AM (he said he went to get the board deck). He exits at 8:18 AM carrying a folder. At 8:20 AM, he enters the break room. He exits the break room at 8:22 AM with nothing in his hands. His path: office → break room → his desk.",
      timestamp: "2024-11-12T08:15:00",
      location: "38th Floor Hallway",
      source: "Security Camera",
      reliability: "high",
      metadata: {
        KevinPath: "Daniel's office (8:15) → Break room (8:20) → Desk (8:22)",
        Folder: "Carried from Daniel's office",
        BreakRoom: "2 minutes, left empty-handed",
        Observation: "Accessed tea tin (per break room camera)",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-03"],
      isRedHerring: false,
      importance: 8,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "07:15",
      date: "2024-11-12",
      description: "Amy arrives and begins routine — prepares Daniel's tea.",
      evidenceIds: ["EVIDENCE-02", "EVIDENCE-03"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "07:30",
      date: "2024-11-12",
      description: "Amy prepares Daniel's tea from his personal tin.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "07:55",
      date: "2024-11-12",
      description: "Kevin arrives on 38th floor.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "08:15",
      date: "2024-11-12",
      description: "Kevin visits Daniel's office, then goes to break room.",
      evidenceIds: ["EVIDENCE-03", "EVIDENCE-12"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "08:15",
      date: "2024-11-12",
      description: "Kevin opens and inspects the tea tin.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "08:40",
      date: "2024-11-12",
      description: "Marcus arrives — badge near Daniel's office.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "08:45",
      date: "2024-11-12",
      description: "Marcus in break room — gets coffee, stands near tea station.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-04"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "08:50",
      date: "2024-11-12",
      description: "Daniel arrives at his office.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "09:05",
      date: "2024-11-12",
      description: "Dr. Okonkwo arrives from 36th floor.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "09:40",
      date: "2024-11-12",
      description: "Daniel sends critical emails to Kevin and Marcus.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-02", "SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "09:42",
      date: "2024-11-12",
      description: "Kevin opens Daniel's email about CEO decision.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "09:43",
      date: "2024-11-12",
      description: "Marcus opens Daniel's email about severance.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "09:55",
      date: "2024-11-12",
      description: "Daniel enters boardroom with tea.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-03",
    },
    {
      id: "TL-14",
      timestamp: "09:58",
      date: "2024-11-12",
      description: "Daniel collapses after two sips of tea.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-03",
    },
    {
      id: "TL-15",
      timestamp: "10:00",
      date: "2024-11-12",
      description: "911 called. Daniel pronounced dead at 10:45 AM.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Kevin stated: 'I never touched Daniel's tea.'",
      contradictingEvidenceId: "EVIDENCE-03",
      suspectId: "SUSPECT-02",
      confidence: 88,
      explanation:
        "Break room camera shows Kevin opening the tea tin at 8:15 AM and inspecting it. His fingerprints were found on the tea cup. While he claims he only moved the cup, his interaction with the tin itself is suspicious — he had no reason to open it if he was only getting the board deck.",
    },
    {
      id: "CONT-02",
      statementText:
        "Marcus stated: 'I never went near Daniel's office that morning.'",
      contradictingEvidenceId: "EVIDENCE-02",
      suspectId: "SUSPECT-04",
      confidence: 92,
      explanation:
        "Badge logs show Marcus's badge was recorded near Daniel's office at 8:40 AM and near the break room at 8:45 AM. He claims he went straight to his own office, but the logs place him in Daniel's vicinity.",
    },
    {
      id: "CONT-03",
      statementText:
        "Dr. Okonkwo stated: 'I never accessed the poison database.'",
      contradictingEvidenceId: "EVIDENCE-11",
      suspectId: "SUSPECT-03",
      confidence: 95,
      explanation:
        "IT logs show her credentials accessed the thallium entry on October 28 — two weeks before Daniel's symptoms. She accessed dosage information and detection methods, with no logged justification for the access.",
    },
    {
      id: "CONT-04",
      statementText:
        "Amy stated: 'No one else had access to the tea.'",
      contradictingEvidenceId: "EVIDENCE-03",
      suspectId: "SUSPECT-01",
      confidence: 80,
      explanation:
        "The break room camera shows both Kevin (8:15 AM) and Marcus (8:45 AM) had access to the tea tin after Amy prepared the initial tea but before Daniel drank it. Amy's claim that only she had access is false — the video evidence shows otherwise.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-02",
    motive:
      "Kevin Park, promised the CEO position by Daniel, learned two days before the death that Daniel was bringing in an outside CEO instead. Kevin had already been meeting with Nexus Industries, who promised him the CEO seat. But with Daniel alive and the merger proceeding, Kevin would lose everything. He introduced thallium to the tea tin at 8:15 AM, using a small vial he obtained from Dr. Okonkwo's unlocked medical cabinet (explaining the missing vial and Okonkwo's database access — she was researching thallium because she suspected someone had taken it). Kevin knew Amy prepared the tea daily and would be the prime suspect. The poison was designed to take effect gradually, but Kevin used a lethal dose in desperation when he received Daniel's 'This CEO decision is final' email at 9:42 AM.",
    sequenceOfEvents: [
      "Kevin learns Daniel is replacing him with an outside CEO, breaking a 2-year promise.",
      "Kevin begins meeting with Nexus Industries, who promise him the CEO seat if the merger closes.",
      "Kevin accesses Dr. Okonkwo's medical cabinet and takes a vial of thallium sulfate (the missing vial).",
      "He researches thallium dosage on the company poison database using Okonkwo's credentials (to deflect blame).",
      "On the morning of November 12, Kevin arrives at 7:55 AM.",
      "He enters the break room at 8:15 AM and introduces thallium to the inner lid of Daniel's tea tin.",
      "He receives Daniel's email at 9:42 AM confirming the CEO decision is final.",
      "Panicking, Kevin considers adding more poison but Daniel has already taken the tea.",
      "Daniel collapses at 9:58 AM after two sips — the initial dose was already lethal.",
      "Amy is the immediate suspect as the tea preparer, which is exactly what Kevin intended.",
    ],
    keyEvidenceIds: ["EVIDENCE-03", "EVIDENCE-09", "EVIDENCE-04", "EVIDENCE-05"],
    redHerringIds: ["EVIDENCE-07"],
    fullNarrative:
      "Kevin Park, Daniel's nephew and protégé, was promised the CEO position at Meridian Tech. When Daniel reneged and planned to bring in an outside CEO, Kevin's ambition turned lethal. He stole thallium from Dr. Okonkwo's medical cabinet, researched it using her credentials to frame her, and poisoned Daniel's personal tea tin on the morning of the murder. Kevin's meeting with Daniel at 8:15 AM gave him access to the tea tin, and Daniel's final email at 9:42 AM confirming the CEO decision sealed Kevin's desperation. Amy Chen, the tea preparer, was the natural suspect — but the break room camera shows Kevin had equal access to the tea tin. Marcus Webb's financial motive (severance package, keyman insurance) made him a strong secondary suspect, but chemical testing only found cross-contamination on his mug, consistent with incidental contact in the break room. Dr. Okonkwo's database access was real but motivated by her own suspicion that someone had taken the thallium from her cabinet.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
