import { Case } from "@/types";

export const digitalGhostCase: Case = {
  metadata: {
    id: "CASE-008",
    title: "The Digital Ghost",
    description:
      "A sophisticated cyberattack on NovaPay, a major fintech company, resulted in $28M being siphoned from customer accounts over 72 hours. The attack was traced to an inside job — someone with admin-level access. The company's CTO was found dead in the server room, an apparent suicide. But the dead man's laptop shows he was actively tracing the attacker when he died. Four people had admin access. The attacker is still inside the system.",
    difficulty: "hard",
    location: "NovaPay HQ, Flatiron District, New York",
    date: "January 15, 2025",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "cybercrime",
  },
  victim: {
    name: "Omar Hassan",
    age: 41,
    occupation: "CTO, NovaPay",
    description:
      "Brilliant cybersecurity engineer who built NovaPay's security architecture from scratch. Found dead in the server room with a cyanide capsule in his mouth — staged as suicide. His laptop, recovered from the scene, shows he was running a trace on the attacker's IP address at the time of death. He was murdered to stop his investigation.",
    causeOfDeath: "Cyanide poisoning — capsule found in mouth, staged as suicide",
    lastSeen: "11:30 PM by security entering the server room",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Priya Sharma",
      age: 36,
      occupation: "VP of Engineering",
      relationshipToVictim: "Omar's direct report and protégé",
      motive:
        "Priya was passed over for the CTO position when Omar was hired externally. She has been secretly working on a competing fintech startup and needed NovaPay's proprietary algorithm to make it viable. The $28M siphon was to fund her new company.",
      alibi: "I was at a team dinner until 9:00 PM. Then I went home and worked remotely.",
      alibiVerified: false,
      knownLocations: [
        "NovaPay — team dinner (until 9:00 PM)",
        "Home (claimed remote work)",
      ],
      communicationHistory: [
        "8:00 PM — Texted her co-founder: 'After tonight, we have the capital'",
        "11:45 PM — Called NovaPay security: 'Something wrong with the servers?'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-04", "EVIDENCE-09"],
      suspicionScore: 72,
      personality:
        "Driven, brilliant, resentful of being overlooked. Genuinely admires Omar's skills but believes she deserves his position. Her startup is her escape from being second.",
      secrets: [
        "Has been copying NovaPay's source code to a private repository for 6 months",
        "Admin credentials used during the siphon window — from her home IP",
        "Knows Omar was about to discover her side project",
      ],
      truthfulStatements: [
        "I was at the team dinner until 9:00 PM.",
        "I do have admin access to the system.",
      ],
      lies: [
        "I was home working on approved NovaPay projects. (She was working on her competing startup)",
        "I didn't access the system that night. (Login logs show her credentials used at 11:15 PM)",
      ],
      refusesToDiscuss: [
        "The competing startup",
        "The source code transfers",
        "Her 11:15 PM login",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Derek Moss",
      age: 29,
      occupation: "Junior Security Analyst",
      relationshipToVictim: "Omar's mentee, youngest person with admin access",
      motive:
        "Derek has been gambling online and owes $350K to a cryptocurrency lending platform. He was approached by the lending platform to provide admin access to NovaPay's systems as debt forgiveness.",
      alibi: "I was monitoring the security dashboard from my desk until 10:00 PM. Then I went to the server room to check a hardware alert.",
      alibiVerified: true,
      knownLocations: [
        "NovaPay — security desk (until 10:00 PM)",
        "Server room (10:15 PM — 10:30 PM)",
      ],
      communicationHistory: [
        "9:00 PM — Texted unknown number: 'The portal is open. Window closes at midnight.'",
        "10:45 PM — Texted the same number: 'I can't do this. Someone is in the server room.'",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05", "EVIDENCE-10"],
      suspicionScore: 65,
      personality:
        "Nervous, in over his head, genuinely remorseful. Got into gambling to pay off student loans and spiraled. Not a career criminal — a desperate kid.",
      secrets: [
        "Opened a backdoor portal for the lending platform at 9:00 PM",
        "Closed the portal at 10:30 PM when he realized someone was tracing the attack",
        "Found Omar's body in the server room but panicked and left without calling anyone",
      ],
      truthfulStatements: [
        "I did access the server room at 10:15 PM.",
        "I owe money to a cryptocurrency lender.",
      ],
      lies: [
        "I didn't open any backdoor. (Login logs show him creating a portal at 9:00 PM)",
        "I left the server room at 10:30 PM and everything was fine. (Omar was likely already dead or dying)",
      ],
      refusesToDiscuss: [
        "The cryptocurrency lender",
        "The backdoor portal",
        "What he saw in the server room",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Lisa Zhao",
      age: 44,
      occupation: "CFO, NovaPay",
      relationshipToVictim: "Board member and financial executive",
      motive:
        "Lisa has been inflating NovaPay's revenue numbers to secure a $200M Series D funding round. The $28M siphon, if traced to a 'hack,' would mask the accounting irregularities and make the loss look external rather than internal.",
      alibi: "I was at a board dinner until 10:00 PM. Then I went to my office to review the funding deck.",
      alibiVerified: true,
      knownLocations: [
        "Board dinner (until 10:00 PM)",
        "NovaPay CFO office (10:15 PM onward)",
      ],
      communicationHistory: [
        "10:30 PM — Called the lead investor: 'We have a situation. The hack may help our narrative.'",
        "11:00 PM — Sent email to board: 'Emergency meeting tomorrow. Cyberattack disclosed.'",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-06", "EVIDENCE-11"],
      suspicionScore: 58,
      personality:
        "Cool under pressure, financially brilliant, views the hack as a strategic opportunity. Would never get her hands dirty but is perfectly willing to benefit from someone else's crime.",
      secrets: [
        "Revenue inflated by $15M over the last two quarters",
        "Was informed about the hack at 10:30 PM and immediately saw its value",
        "Has been cooking the books since before Omar was hired",
      ],
      truthfulStatements: [
        "I was at the board dinner until 10:00 PM.",
        "I did call the lead investor about the hack.",
      ],
      lies: [
        "I had no knowledge of any accounting irregularities. (She personally approved the inflated numbers)",
        "The hack was a complete surprise to me. (She was alerted at 10:30 PM and immediately planned the narrative)",
      ],
      refusesToDiscuss: [
        "The accounting irregularities",
        "The inflated revenue",
        "Her conversation with the investor",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Tom Bradley",
      age: 50,
      occupation: "Head of IT Infrastructure",
      relationshipToVictim: "15-year veteran of the company, oversaw the server room",
      motive:
        "Tom is being quietly pushed out of NovaPay as part of a cost-cutting measure. His position is being automated. If the company's infrastructure fails spectacularly, it demonstrates the value of human oversight and saves his job. The $28M loss could also trigger his golden parachute clause.",
      alibi: "I was home all evening. I was called in at 11:30 PM when the breach was discovered.",
      alibiVerified: true,
      knownLocations: [
        "Home (verified)",
        "NovaPay — called in at 11:30 PM",
      ],
      communicationHistory: [
        "7:00 PM — Texted his wife: 'They're going to automate my job. I need a plan.'",
        "9:15 PM — Called an unknown number (4 min) — traced to a dark web forum",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-07", "EVIDENCE-12"],
      suspicionScore: 45,
      personality:
        "Old-school IT professional, resistant to change, feels disrespected by the company he helped build. Technically skilled enough to facilitate the attack but morally conflicted.",
      secrets: [
        "Created a maintenance account with admin access that was never deactivated",
        "The maintenance account was used during the siphon",
        "Called a dark web forum to sell information about NovaPay's security architecture",
      ],
      truthfulStatements: [
        "I was called in at 11:30 PM.",
        "My position is being automated.",
      ],
      lies: [
        "I never created any unauthorized accounts. (The maintenance account was created by him 3 years ago and never logged)",
        "I have no contact with dark web forums. (Call logs show a 4-minute call to a dark web forum number)",
      ],
      refusesToDiscuss: [
        "The maintenance account",
        "The dark web call",
        "His automation concerns",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Kevin Park",
      age: 25,
      occupation: "Night Security Guard",
      relationshipToVictim: "Security guard on duty the night of the attack",
      statement:
        "I saw Omar enter the server room at 11:30 PM. He looked focused, not distressed. He said he was investigating a security anomaly. I checked on the server room at 11:45 PM — door was closed, light was on inside. I didn't enter because the CTO had exclusive server room access. At 12:15 AM, the security alarm triggered and I found Omar on the floor.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-05"],
      personality: "Dutiful, new to the job, disturbed by finding the body.",
    },
    {
      id: "WITNESS-02",
      name: "Dr. Amanda Foster",
      age: 39,
      occupation: "NovaPay — Data Scientist",
      relationshipToVictim: "Colleague who worked closely with Omar",
      statement:
        "Omar told me at 5:00 PM that he'd detected unusual admin-level activity in the system and was going to trace it after hours. He said: 'Someone inside is moving money, and I'm going to find out who.' He seemed determined, not scared. I offered to help but he said he wanted to handle it alone.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-08"],
      personality: "Analytical, trusted Omar, devastated by his death.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "Server Room",
      type: "Room",
      address: "NovaPay HQ, Basement Level 2",
      description:
        "The company's primary server room. Contains the main servers, backup systems, and the core transaction database. Access requires CTO-level clearance. Omar was found dead on the floor between Server Racks 4 and 5.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-05"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02"],
    },
    {
      id: "LOC-02",
      name: "Security Operations Center",
      type: "Room",
      address: "NovaPay HQ, Ground Floor",
      description:
        "The company's security monitoring room. Contains multiple screens showing system logs, network traffic, and physical security cameras. Derek's workstation is here.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-10"],
      relevantSuspects: ["SUSPECT-02"],
    },
    {
      id: "LOC-03",
      name: "CFO Office",
      type: "Room",
      address: "NovaPay HQ, 12th Floor",
      description:
        "Lisa's office. Contains financial records, the Series D deck, and a locked safe with backup drive copies.",
      relevantEvidence: ["EVIDENCE-03", "EVIDENCE-11"],
      relevantSuspects: ["SUSPECT-03"],
    },
    {
      id: "LOC-04",
      name: "Engineering Floor",
      type: "Floor",
      address: "NovaPay HQ, 10th Floor",
      description:
        "The engineering team's workspace. Priya's office is here. Contains multiple workstations with admin access to the system.",
      relevantEvidence: ["EVIDENCE-04", "EVIDENCE-09"],
      relevantSuspects: ["SUSPECT-01"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-008",
      title: "Omar's Laptop — Active Trace",
      category: "digital",
      description:
        "Omar's laptop, found next to his body in the server room, was running a live trace on the attacker's IP address. The trace had locked onto an IP address belonging to Priya Sharma's home network. The trace window shows the attack originated from admin credentials — specifically Priya's admin account. Omar was moments from identifying her when he was killed.",
      timestamp: "2025-01-15T00:00:00",
      location: "Server Room",
      source: "Laptop Forensics",
      reliability: "high",
      metadata: {
        TraceTarget: "Attacker IP address",
        Result: "Priya Sharma's home network",
        Credentials: "Priya's admin account",
        Status: "Trace 94% complete at time of death",
        LaptopState: "Open, running, battery 40%",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-008",
      title: "Derek's Backdoor Portal — System Logs",
      category: "digital",
      description:
        "System logs show Derek created a maintenance portal at 9:00 PM using his admin credentials. The portal allowed external access to the transaction database. The portal was used to siphon $28M between 9:15 PM and 10:30 PM. Derek closed the portal at 10:30 PM. The siphon was executed through the portal, but Derek did not initiate the siphon itself — someone else used his portal.",
      timestamp: "2025-01-14T21:00:00",
      location: "Security Operations Center",
      source: "System Access Logs",
      reliability: "high",
      metadata: {
        PortalCreated: "9:00 PM — Derek's credentials",
        PortalUsed: "9:15 PM to 10:30 PM — siphon window",
        PortalClosed: "10:30 PM — Derek closed it",
        SiphonAmount: "$28M",
        PortalCreator: "Derek — but siphon initiated by external party",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-008",
      title: "NovaPay Financial Irregularities",
      category: "financial",
      description:
        "Forensic accounting reveals NovaPay's revenue has been inflated by $15M over the last two quarters. The inflated numbers are in the Series D funding deck. Lisa Zhao personally approved the revised numbers. If an external hack is blamed for the $28M loss, the accounting gap is masked.",
      timestamp: "2025-01-10T00:00:00",
      location: "CFO Office",
      source: "Forensic Accounting",
      reliability: "high",
      metadata: {
        InflatedAmount: "$15M over two quarters",
        Deck: "Series D funding — contains inflated numbers",
        ApprovedBy: "Lisa Zhao",
        CoverOpportunity: "External hack masks accounting gap",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-06", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-008",
      title: "Priya's Source Code Transfers",
      category: "digital",
      description:
        "Version control logs show Priya has been copying NovaPay's proprietary source code to a private GitHub repository over 6 months. The repository belongs to 'Helios Fintech' — Priya's competing startup. The code includes the algorithm that makes NovaPay's transaction processing unique.",
      timestamp: "2025-01-01T00:00:00",
      location: "Engineering Floor",
      source: "Version Control Logs",
      reliability: "high",
      metadata: {
        Repository: "Helios Fintech — private GitHub",
        Duration: "6 months",
        Content: "NovaPay's proprietary source code",
        Algorithm: "Transaction processing core IP",
        Access: "Priya's admin credentials",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-008",
      title: "Server Room — Cyanide Analysis",
      category: "forensic",
      description:
        "Omar's body shows cyanide capsule in his mouth — staged as suicide. However, the capsule was not bitten — it was placed. Omar's teeth show no bite marks on the capsule. Additionally, Omar's right hand has a bruise consistent with being grabbed from behind. The cyanide was administered by force.",
      timestamp: "2025-01-15T01:00:00",
      location: "Server Room",
      source: "Autopsy Report",
      reliability: "high",
      metadata: {
        CyanideCapsule: "Placed in mouth — not bitten",
        BiteMarks: "None on capsule",
        Bruise: "Right hand — grabbed from behind",
        Toxicology: "Cyanide in system — administered post-mortem or by force",
        Conclusion: "Staged suicide — murder",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-008",
      title: "Lisa's Investor Call",
      category: "digital",
      description:
        "Lisa called NovaPay's lead investor at 10:30 PM — 45 minutes before the breach was publicly discovered. The call lasted 8 minutes. Lisa stated: 'We have a situation. The hack may help our narrative.' The investor later confirmed Lisa mentioned the hack in general terms before it was publicly known.",
      timestamp: "2025-01-14T22:30:00",
      location: "CFO Office",
      source: "Phone Records + Investor Statement",
      reliability: "high",
      metadata: {
        Time: "10:30 PM — 45 min before public discovery",
        Duration: "8 minutes",
        Statement: "'The hack may help our narrative'",
        InvestorConfirmed: "Lisa mentioned hack in general terms",
        Timing: "Pre-knowledge of the breach",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-008",
      title: "Tom's Maintenance Account — System Backdoor",
      category: "digital",
      description:
        "A maintenance account named 'sys_maint_2021' with full admin access was found in the system. The account was created 3 years ago by Tom Bradley's credentials and was never deactivated. The account was used in 3 of the last 5 siphon transactions. Tom claims the account was for emergency hardware maintenance.",
      timestamp: "2025-01-14T00:00:00",
      location: "Server Room",
      source: "System Audit",
      reliability: "high",
      metadata: {
        Account: "sys_maint_2021",
        CreatedBy: "Tom Bradley — 3 years ago",
        AccessLevel: "Full admin",
        UsedIn: "3 of 5 siphon transactions",
        TomClaim: "Emergency hardware maintenance",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-12"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-008",
      title: "Omar's Last Message — Amanda",
      category: "message",
      description:
        "Omar sent Amanda a message at 5:15 PM: 'Found the leak. It's admin-level. Following the trail tonight. If something happens to me, check the maintenance account and Priya's home IP.' This message was sent before Omar entered the server room and suggests he suspected Priya.",
      timestamp: "2025-01-14T17:15:00",
      location: "Engineering Floor",
      source: "Internal Messaging System",
      reliability: "high",
      metadata: {
        To: "Amanda Foster",
        Time: "5:15 PM",
        Content: "'Found the leak. It's admin-level. Following the trail tonight.'",
        Warning: "'If something happens to me, check maintenance account and Priya's home IP.'",
        SentBefore: "Server room entry",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-07"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-008",
      title: "Priya's Login — 11:15 PM",
      category: "digital",
      description:
        "System logs show Priya's admin credentials logged in at 11:15 PM from her home IP address. She accessed the transaction database and attempted to delete the siphon transaction logs. The deletion was 60% complete when Omar's trace interrupted it. The remaining 40% of logs survived.",
      timestamp: "2025-01-14T23:15:00",
      location: "Priya's Home Network",
      source: "System Access Logs",
      reliability: "high",
      metadata: {
        LoginTime: "11:15 PM",
        IPAddress: "Priya's home network",
        Action: "Attempted deletion of siphon logs",
        DeletionComplete: "60% — interrupted by Omar's trace",
        SurvivingLogs: "40% — shows siphon transactions",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-04"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-008",
      title: "Derek's Dark Web Messages",
      category: "message",
      description:
        "Derek's phone and computer show he was communicating with a cryptocurrency lending platform through encrypted dark web messages. The messages show the platform offered to forgive Derek's $350K debt in exchange for opening a backdoor to NovaPay's transaction database. Derek agreed and opened the portal at 9:00 PM.",
      timestamp: "2025-01-14T21:00:00",
      location: "Security Operations Center",
      source: "Encrypted Message Recovery",
      reliability: "high",
      metadata: {
        DebtorPlatform: "Cryptocurrency lending platform",
        Debt: "$350K",
        Offer: "Backdoor access for debt forgiveness",
        Agreement: "Derek agreed — 8:45 PM",
        PortalOpened: "9:00 PM — per agreement",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-008",
      title: "Lisa's Board Email — Emergency Meeting",
      category: "message",
      description:
        "Lisa sent an email to the board at 11:00 PM — 15 minutes after Omar's body was found but before the breach was officially disclosed. The email called an 'emergency meeting tomorrow' and referenced a 'cyberattack and security incident.' She had not been notified of the breach through official channels.",
      timestamp: "2025-01-14T23:00:00",
      location: "CFO Office",
      source: "Email Server Logs",
      reliability: "high",
      metadata: {
        Time: "11:00 PM",
        Recipient: "Board of Directors",
        Content: "Emergency meeting — cyberattack reference",
        OfficialNotification: "Not yet received",
        Preknowledge: "Lisa knew before official disclosure",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-06"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-008",
      title: "Tom's Dark Web Forum Call",
      category: "digital",
      description:
        "Phone records show Tom called a dark web forum number at 9:15 PM for 4 minutes. The forum is known for trading corporate security exploits. The call occurred during the siphon window. Tom claims he was calling to report a vulnerability, not sell one.",
      timestamp: "2025-01-14T21:15:00",
      location: "Tom's Home",
      source: "Phone Records",
      reliability: "medium",
      metadata: {
        Time: "9:15 PM — during siphon window",
        Duration: "4 minutes",
        Number: "Dark web forum",
        ForumType: "Corporate security exploits",
        TomClaim: "Reporting a vulnerability",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-07"],
      isRedHerring: true,
      importance: 5,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "17:00",
      date: "2025-01-14",
      description: "Omar tells Amanda he's found the leak and will trace it tonight.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "17:15",
      date: "2025-01-14",
      description: "Omar sends warning message to Amanda about Priya and maintenance account.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "20:00",
      date: "2025-01-14",
      description: "Priya's co-founder texts: 'After tonight, we have the capital.'",
      evidenceIds: ["EVIDENCE-04"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "21:00",
      date: "2025-01-14",
      description: "Derek opens backdoor portal using his admin credentials.",
      evidenceIds: ["EVIDENCE-02", "EVIDENCE-10"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "21:15",
      date: "2025-01-14",
      description: "Siphon begins through Derek's portal. $28M transferred over 75 minutes.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "21:15",
      date: "2025-01-14",
      description: "Tom calls dark web forum (4 minutes).",
      evidenceIds: ["EVIDENCE-12"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "22:00",
      date: "2025-01-14",
      description: "Derek sees unusual activity on dashboard, panics.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "22:15",
      date: "2025-01-14",
      description: "Derek goes to server room to investigate.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "22:30",
      date: "2025-01-14",
      description: "Lisa calls lead investor: 'The hack may help our narrative.'",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "22:30",
      date: "2025-01-14",
      description: "Derek closes the backdoor portal.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "23:00",
      date: "2025-01-14",
      description: "Lisa sends emergency board meeting email.",
      evidenceIds: ["EVIDENCE-11"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "23:15",
      date: "2025-01-14",
      description: "Priya logs in from home, attempts to delete siphon logs.",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-04",
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "23:15",
      date: "2025-01-14",
      description: "Omar enters server room to trace the attack.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-14",
      timestamp: "23:20",
      date: "2025-01-14",
      description: "Omar begins trace, locks onto Priya's IP address.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "23:30",
      date: "2025-01-14",
      description: "Kevin checks server room — door closed, light on.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-16",
      timestamp: "23:45",
      date: "2025-01-14",
      description: "Omar is killed. Cyanide capsule placed in his mouth. Trace at 94%.",
      evidenceIds: ["EVIDENCE-05", "EVIDENCE-01"],
      suspectIds: [],
      verified: false,
      locationId: "LOC-01",
    },
    {
      id: "TL-17",
      timestamp: "23:45",
      date: "2025-01-14",
      description: "Priya's log deletion interrupted — Omar's trace disrupted her access.",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-18",
      timestamp: "00:00",
      date: "2025-01-15",
      description: "Security alarm triggered. Kevin finds Omar's body.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-19",
      timestamp: "00:15",
      date: "2025-01-15",
      description: "911 called. Police and forensic team dispatched.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Priya stated: 'I was home working on approved NovaPay projects.'",
      contradictingEvidenceId: "EVIDENCE-09",
      suspectId: "SUSPECT-01",
      confidence: 93,
      explanation:
        "System logs show Priya's admin credentials logged in from her home IP at 11:15 PM and attempted to delete siphon transaction logs. She was not working on approved projects — she was destroying evidence of the theft she orchestrated.",
    },
    {
      id: "CONT-02",
      statementText:
        "Derek stated: 'I didn't open any backdoor.'",
      contradictingEvidenceId: "EVIDENCE-02",
      suspectId: "SUSPECT-02",
      confidence: 96,
      explanation:
        "System logs show Derek's credentials creating a maintenance portal at 9:00 PM. The portal was used for the siphon. Derek's claim that he didn't open a backdoor is directly contradicted by the access logs tied to his credentials.",
    },
    {
      id: "CONT-03",
      statementText:
        "Lisa stated: 'The hack was a complete surprise to me.'",
      contradictingEvidenceId: "EVIDENCE-11",
      suspectId: "SUSPECT-03",
      confidence: 85,
      explanation:
        "Lisa sent a board email at 11:00 PM referencing a 'cyberattack and security incident' — 15 minutes before the breach was officially discovered. She had pre-knowledge of the attack, contradicting her claim of surprise.",
    },
    {
      id: "CONT-04",
      statementText:
        "Tom stated: 'I never created any unauthorized accounts.'",
      contradictingEvidenceId: "EVIDENCE-07",
      suspectId: "SUSPECT-04",
      confidence: 88,
      explanation:
        "A maintenance account 'sys_maint_2021' was created by Tom's credentials 3 years ago with full admin access. The account was used in 3 of the 5 siphon transactions. Tom's denial of creating unauthorized accounts is contradicted by the system audit trail.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-01",
    motive:
      "Priya Sharma orchestrated the $28M siphon to fund her competing startup, Helios Fintech. She had been copying NovaPay's source code for 6 months and needed capital to launch. She used Derek's backdoor (which she诱导 him to create by feeding information about his gambling debts to the lending platform) to execute the siphon. When Omar began tracing the attack and locked onto her IP, she entered the server room and killed him to stop the investigation. She placed the cyanide capsule in his mouth to stage a suicide. The maintenance account used in some transactions was Tom's old account that Priya discovered and exploited.",
    sequenceOfEvents: [
      "Priya begins copying NovaPay's source code 6 months ago for her competing startup.",
      "She needs $28M to launch Helios Fintech and decides to siphon it from NovaPay.",
      "She discovers Derek's gambling debts and connects him with the lending platform.",
      "The lending platform offers Derek debt forgiveness in exchange for a backdoor.",
      "Derek opens the portal at 9:00 PM as agreed.",
      "The siphon executes through the portal from 9:15 PM to 10:30 PM.",
      "Priya also uses Tom's old maintenance account for some transactions.",
      "Omar detects the anomaly and begins tracing the attack at 11:15 PM.",
      "Omar's trace locks onto Priya's home IP at 94% completion.",
      "Priya, realizing she's about to be exposed, enters the server room.",
      "She kills Omar by force-feeding him cyanide and stages it as suicide.",
      "She attempts to delete the siphon logs at 11:15 PM but Omar's trace interrupted her.",
      "Derek discovers Omar's body but panics and doesn't report it.",
      "Lisa, who had pre-knowledge of the breach opportunity, begins covering her accounting fraud.",
    ],
    keyEvidenceIds: ["EVIDENCE-01", "EVIDENCE-09", "EVIDENCE-08", "EVIDENCE-04"],
    redHerringIds: ["EVIDENCE-12"],
    fullNarrative:
      "Priya Sharma, passed over for the CTO position, spent 6 months preparing a competing fintech startup by copying NovaPay's proprietary code. She needed $28M to launch and orchestrated the siphon by exploiting Derek's gambling debts (connecting him with a lending platform that demanded a backdoor in exchange for debt forgiveness) and Tom's forgotten maintenance account. When Omar traced the attack and locked onto her home IP at 94% completion, Priya entered the server room and killed him, staging his death as a suicide with a planted cyanide capsule. Derek, who opened the portal, discovered Omar's body but panicked and left without reporting it — his portal was the mechanism but not the motive. Lisa Zhao, the CFO, discovered the hack at 10:30 PM and recognized it as an opportunity to mask her $15M accounting fraud in the Series D funding round. She didn't kill Omar but actively worked to obscure the truth after his death. Tom Bradley's maintenance account was an unwitting tool — his old backdoor was discovered and exploited by Priya without his direct involvement.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
