import { Case } from "@/types";

export const dinnerPartyDeathCase: Case = {
  metadata: {
    id: "CASE-006",
    title: "The Dinner Party Death",
    description:
      "Billionaire tech investor Richard Slate was poisoned at his own estate during a dinner party he hosted for eight guests. The poison — aconitine — was in his wine glass. Eight guests. One chef. One housekeeper. Every person at the table had a motive. The wine was poured by the housekeeper from a bottle Richard opened himself. No one else touched the bottle.",
    difficulty: "expert",
    location: "Slate Estate, The Hamptons, Long Island",
    date: "August 3, 2024",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "murder",
  },
  victim: {
    name: "Richard Slate",
    age: 58,
    occupation: "Tech Investor / Venture Capitalist",
    description:
      "Aggressive venture capitalist known for hostile takeovers and destroying founders he funded. Built a $4B portfolio by exploiting vulnerable startups. Despised by many, admired by few. Had a habit of humiliating people at dinner parties for entertainment.",
    causeOfDeath: "Aconitine poisoning — derived from monkshood plant",
    lastSeen: "9:45 PM, alive and drinking wine at the head of his table",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Diane Slate",
      age: 52,
      occupation: "Philanthropist / Socialite",
      relationshipToVictim: "Wife of 25 years",
      motive:
        "Richard changed his will 3 months ago, cutting Diane from 50% to 15%. He was also having an affair with their housekeeper. Diane discovered both facts in the same week.",
      alibi: "I was seated to Richard's left. I ate the same food and drank from my own glass. I am fine — the poison was only in Richard's glass.",
      alibiVerified: true,
      knownLocations: [
        "Slate Estate — dining room (entire evening)",
        "Master bedroom (until dinner at 8:00 PM)",
      ],
      communicationHistory: [
        "3:00 PM — Called divorce lawyer (15 min)",
        "8:30 PM — Texted her sister: 'Tonight we find out what he's made of'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-05", "EVIDENCE-10"],
      suspicionScore: 70,
      personality:
        "Refined, patient, has endured decades of Richard's cruelty. Beneath the composure is a woman who has been planning her exit — or his — for years.",
      secrets: [
        "Has been poisoning Richard's food with a mild allergen for months as a test",
        "Knows the monkshood in the estate garden was recently harvested",
        "Has a personal relationship with the estate's gardener",
      ],
      truthfulStatements: [
        "I was seated to Richard's left.",
        "I did not put anything in his wine.",
        "Richard changed the will.",
      ],
      lies: [
        "I had no idea about the affair. (She saw them together 2 weeks ago)",
        "I have never been in the garden shed. (Her fingerprints are on the mortar)",
      ],
      refusesToDiscuss: [
        "The allergen experiments",
        "The gardener relationship",
        "The divorce lawyer call",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Jake Morrison",
      age: 31,
      occupation: "Startup Founder",
      relationshipToVictim: "Former investee — Richard destroyed his company",
      motive:
        "Richard invested in Jake's startup, then orchestrated a hostile takeover that left Jake with nothing. Jake lost his company, his savings, and his reputation. He was invited to this dinner — an apparent act of cruelty by Richard.",
      alibi: "I was seated at the far end of the table. I watched the housekeeper pour wine for everyone. I did not leave my seat.",
      alibiVerified: false,
      knownLocations: [
        "Slate Estate — dining room (seated far end)",
        "Guest bathroom (9:15 PM — verified by housekeeper)",
      ],
      communicationHistory: [
        "7:00 PM — Texted his girlfriend: 'Going to the lion's den tonight'",
        "9:50 PM — Called 911 after Richard collapsed",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-06", "EVIDENCE-08"],
      suspicionScore: 55,
      personality:
        "Bitter but intelligent. Still believes in the startup world despite what Richard did. His anger is real but his methods are words, not weapons.",
      secrets: [
        "Brought a small vial to the dinner (claimed it was heartburn medication)",
        "Was seen near the wine cellar before dinner",
        "Has been researching aconitine online for 2 months",
      ],
      truthfulStatements: [
        "I was seated at the far end.",
        "Richard destroyed my company.",
        "I did not leave my seat during dinner.",
      ],
      lies: [
        "The vial was just heartburn pills. (Lab analysis of the vial residue shows aconitine traces)",
        "I never went near the wine cellar. (CCTV shows him entering the wine cellar at 7:30 PM)",
      ],
      refusesToDiscuss: [
        "The vial's contents",
        "The wine cellar visit",
        "His online research",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Clara Voss",
      age: 44,
      occupation: "Richard's Personal Attorney",
      relationshipToVictim: "Attorney for 10 years",
      motive:
        "Richard discovered Clara had been billing him for fictitious legal services — $340K over 5 years. He confronted her the day before the dinner. She knew he would expose her publicly.",
      alibi: "I was seated to Richard's right. I poured water for him during the first course. I did not touch his wine glass.",
      alibiVerified: true,
      knownLocations: [
        "Slate Estate — dining room (seated right of Richard)",
        "Study (met with Richard at 7:00 PM — 15 min)",
      ],
      communicationHistory: [
        "7:00 PM — Called her office: 'Delete the files I sent yesterday'",
        "9:00 PM — Texted Richard: 'We need to discuss the billing before dessert'",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-07", "EVIDENCE-11"],
      suspicionScore: 65,
      personality:
        "Brilliant lawyer, morally flexible, has survived in a predatory industry by being more predatory. Her loyalty is to herself first.",
      secrets: [
        "Accessed the estate's botanical records 2 weeks ago — researching monkshood",
        "Has a forged Power of Attorney that would transfer Richard's assets to Diane",
        "Knows the poison was in the wine, not the food",
      ],
      truthfulStatements: [
        "I did pour water for Richard.",
        "I was seated to his right.",
        "Richard confronted me about the billing.",
      ],
      lies: [
        "I never accessed the botanical records. (Estate computer logs show her login accessing monkshood research)",
        "The Power of Attorney is legitimate. (It was backdated and forged)",
      ],
      refusesToDiscuss: [
        "The botanist research",
        "The Power of Attorney",
        "The fictitious billing",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Yuki Tanaka",
      age: 38,
      occupation: "Personal Chef",
      relationshipToVictim: "Private chef for 2 years",
      motive:
        "Richard repeatedly humiliated Yuki in front of guests, calling her food 'mediocre' and threatening to replace her. In the last month, Richard discovered Yuki was secretly recording his dinner conversations to sell to a media outlet.",
      alibi: "I prepared the meal and served it. I was in the kitchen during most of dinner, coming out only to serve courses.",
      alibiVerified: false,
      knownLocations: [
        "Kitchen (most of evening)",
        "Dining room (served courses at 8:15, 8:45, 9:15, 9:30 PM)",
      ],
      communicationHistory: [
        "6:00 PM — Texted media contact: 'The main course is tonight'",
        "9:20 PM — Called her brother: 'After tonight, I'm done with this place'",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-09", "EVIDENCE-12"],
      suspicionScore: 60,
      personality:
        "Skilled, proud, has been systematically degraded by Richard. Her cultural pride makes the public humiliation especially cutting. She is capable of precision under pressure.",
      secrets: [
        "Has been recording dinner conversations for 3 months",
        "Accessed the garden shed the day before the dinner",
        "Has a personal mortar and pestle set (consistent with grinding plant material)",
      ],
      truthfulStatements: [
        "I prepared and served the meal.",
        "I was in the kitchen during most of dinner.",
      ],
      lies: [
        "I never went to the garden shed. (Security camera shows her entering at 2:00 PM the day before)",
        "I have no recording device. (3 months of conversations found on a hidden device in the kitchen)",
      ],
      refusesToDiscuss: [
        "The recordings",
        "The garden shed visit",
        "The mortar and pestle",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Margaret Chen",
      age: 55,
      occupation: "Housekeeper",
      relationshipToVictim: "Housekeeper for 8 years, secret affair with Richard",
      statement:
        "I poured wine for all guests from the bottle Richard opened. I used the same bottle, the same pour. Richard's glass was at the head of the table. I did not add anything to any glass. The wine was a 2015 Château Margaux. I poured at 9:35 PM. Richard took his first sip at 9:40 PM and seemed fine. At 9:45 PM he gasped and collapsed.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-03"],
      personality: "Devoted to Richard, devastated by his death, terrified of being blamed.",
    },
    {
      id: "WITNESS-02",
      name: "Dr. Aisha Bello",
      age: 42,
      occupation: "Dinner Guest / Toxicologist",
      relationshipToVictim: "Colleague of Clara's, invited as a plus-one",
      statement:
        "I recognized the symptoms immediately — aconitine poisoning. The rapid onset, the cardiac arrhythmia, the muscle tingling he described before collapsing. Aconitine is derived from monkshood, which I noticed growing in the estate's ornamental garden. It's a beautiful but deadly plant. The poison must have been introduced to the wine specifically — the other glasses were fine.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-04"],
      personality: "Scientific, precise, alarmed by the poisoning but fascinated by the forensic implications.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "Dining Room",
      type: "Room",
      address: "Slate Estate, Main Floor",
      description:
        "Formal dining room with a 14-seat mahogany table. Richard's seat was at the head. Wine glasses were arranged in order. The 2015 Château Margaux was on the sideboard.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-03"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-03"],
    },
    {
      id: "LOC-02",
      name: "Estate Garden",
      type: "Exterior",
      address: "Slate Estate, Rear Grounds",
      description:
        "Includes an ornamental garden with monkshood (Aconitum napellus), a garden shed with tools, and a potting area with mortar and pestle.",
      relevantEvidence: ["EVIDENCE-04", "EVIDENCE-09"],
      relevantSuspects: ["SUSPECT-04"],
    },
    {
      id: "LOC-03",
      name: "Wine Cellar",
      type: "Room",
      address: "Slate Estate, Lower Level",
      description:
        "Temperature-controlled wine cellar with 2,000 bottles. Contains the remaining 2015 Château Margaux. No signs of tampering with other bottles.",
      relevantEvidence: ["EVIDENCE-06"],
      relevantSuspects: ["SUSPECT-02"],
    },
    {
      id: "LOC-04",
      name: "Kitchen",
      type: "Room",
      address: "Slate Estate, Main Floor",
      description:
        "Professional-grade kitchen where Yuki prepared the meal. Contains a hidden recording device and a personal mortar and pestle set in her station.",
      relevantEvidence: ["EVIDENCE-09", "EVIDENCE-12"],
      relevantSuspects: ["SUSPECT-04"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-006",
      title: "Wine Glass — Aconitine Analysis",
      category: "forensic",
      description:
        "Richard's wine glass tested positive for aconitine — a lethal alkaloid derived from monkshood. The concentration was consistent with a single lethal dose dissolved into the wine. No aconitine was found in the wine bottle itself, suggesting the poison was introduced directly to Richard's glass after pouring.",
      timestamp: "2024-08-04T02:00:00",
      location: "Dining Room",
      source: "Forensic Toxicology",
      reliability: "high",
      metadata: {
        Substance: "Aconitine (monkshood-derived)",
        Concentration: "Lethal",
        Location: "Richard's glass only",
        BottleTest: "Negative — no aconitine in bottle",
        Conclusion: "Introduced to glass after pouring",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-006",
      title: "Jake's Vial — Residue Analysis",
      category: "forensic",
      description:
        "A small glass vial found in Jake's jacket pocket contained trace residue of aconitine. Jake claimed it was heartburn medication, but lab analysis confirms the residue matches the aconitine found in Richard's wine glass.",
      timestamp: "2024-08-04T03:00:00",
      location: "Jake's Jacket",
      source: "Forensic Analysis",
      reliability: "high",
      metadata: {
        Item: "Small glass vial",
        Contents: "Aconitine residue",
        Match: "Same compound as in wine glass",
        JakeClaim: "Heartburn medication",
        LabResult: "Confirmed aconitine",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-006",
      title: "Clara's Study Meeting — Notes",
      category: "document",
      description:
        "Clara met with Richard in the study at 7:00 PM — 30 minutes before guests arrived. Notes found on Clara's laptop show she was preparing a defense against Richard's accusation of billing fraud. Richard had given her 48 hours to return the money or he would go public.",
      timestamp: "2024-08-03T19:00:00",
      location: "Study",
      source: "Laptop Forensics",
      reliability: "high",
      metadata: {
        MeetingTime: "7:00 PM — 15 minutes",
        Topic: "Billing fraud defense",
        RichardDemand: "Return money within 48 hours or public exposure",
        ClaraNote: "Need to resolve this before Monday",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-07", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-006",
      title: "Monkshood in Estate Garden",
      category: "forensic",
      description:
        "The estate garden contains mature monkshood plants (Aconitum napellus). Recently harvested stems were found in the garden waste bin. The harvesting was done within the last 48 hours. The garden shed contains a mortar with residue matching monkshood alkaloids.",
      timestamp: "2024-08-04T08:00:00",
      location: "Estate Garden",
      source: "Crime Scene Search",
      reliability: "high",
      metadata: {
        Plant: "Monkshood (Aconitum napellus)",
        Harvested: "Within 48 hours",
        WasteBin: "Fresh stems in garden waste",
        Mortar: "Residue matches aconitine alkaloids",
        Access: "Garden shed — no lock",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-006",
      title: "Diane's Divorce Lawyer Call",
      category: "digital",
      description:
        "Phone records confirm Diane called her divorce lawyer at 3:00 PM on August 3. The 15-minute call discussed asset division strategies. The lawyer later stated Diane asked specifically about the implications of Richard's death on the will.",
      timestamp: "2024-08-03T15:00:00",
      location: "Slate Estate",
      source: "Phone Records + Lawyer Statement",
      reliability: "high",
      metadata: {
        CallTime: "3:00 PM",
        Duration: "15 minutes",
        Topic: "Asset division, death implications",
        LawyerStatement: "Diane asked about will implications",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-10"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-006",
      title: "Jake — Wine Cellar CCTV",
      category: "cctv",
      description:
        "Wine cellar security camera shows Jake entering at 7:30 PM and browsing the wine rack for 8 minutes. He does not handle the 2015 Château Margaux. He picks up two bottles, examines them, puts them back, and leaves. No aconitine-related items observed.",
      timestamp: "2024-08-03T19:30:00",
      location: "Wine Cellar",
      source: "Security Camera",
      reliability: "high",
      metadata: {
        Entry: "7:30 PM",
        Duration: "8 minutes",
        Behavior: "Browsed wine rack",
        ChateauMargaux: "Did not handle",
        ItemsCarried: "None removed",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: true,
      importance: 5,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-006",
      title: "Clara — Botanical Database Access",
      category: "digital",
      description:
        "Estate computer logs show Clara accessed the estate's botanical database 2 weeks before the dinner. She searched specifically for 'monkshood — toxic properties' and 'aconitine — lethal dosage.' The search was made using her guest login credentials.",
      timestamp: "2024-07-20T00:00:00",
      location: "Estate Study",
      source: "Computer Access Logs",
      reliability: "high",
      metadata: {
        Date: "2 weeks before dinner",
        Searches: "Monkshood toxicity, aconitine dosage",
        Credentials: "Clara's guest login",
        Purpose: "No logged justification",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-04"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-006",
      title: "Jake — Online Research History",
      category: "digital",
      description:
        "Jake's laptop shows 47 searches related to aconitine over 2 months: 'aconitine detection methods,' 'aconitine in wine,' 'how long does aconitine stay in system,' 'monkshood garden identification.' He also searched 'Richard Slate health condition' and 'Richard Slate daily routine.'",
      timestamp: "2024-08-01T00:00:00",
      location: "Jake's Laptop",
      source: "Browser Forensics",
      reliability: "high",
      metadata: {
        Searches: "47 aconitine-related searches",
        Timeframe: "2 months",
        SpecificQueries: "Detection, wine, system duration, garden ID",
        RichardSearches: "Health condition, daily routine",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-006",
      title: "Yuki — Garden Shed Access",
      category: "cctv",
      description:
        "Estate security shows Yuki entering the garden shed at 2:00 PM on August 2 — the day before the dinner. She was inside for 12 minutes. She emerged carrying a small bag. Her own mortar and pestle set was found in her kitchen station with matching monkshood residue.",
      timestamp: "2024-08-02T14:00:00",
      location: "Garden Shed",
      source: "Estate Security Camera",
      reliability: "high",
      metadata: {
        Entry: "2:00 PM, August 2",
        Duration: "12 minutes",
        EmergedWith: "Small bag",
        Mortar: "Personal set in kitchen — monkshood residue",
        GardenWaste: "Freshly harvested stems nearby",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-006",
      title: "Richard's Will Change — Timeline",
      category: "document",
      description:
        "Richard changed his will 3 months ago (May 2024), reducing Diane's share from 50% to 15%. The new will leaves 60% to a tech foundation Richard established. Diane was informed by the estate attorney on May 15. She did not contest the change.",
      timestamp: "2024-05-01T00:00:00",
      location: "Legal Records",
      source: "Estate Attorney Records",
      reliability: "high",
      metadata: {
        DateChanged: "May 2024",
        DianeShare: "50% → 15%",
        Beneficiary: "Tech foundation (60%)",
        DianeInformed: "May 15, 2024",
        ContestStatus: "Not contested",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-05"],
      isRedHerring: false,
      importance: 6,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-006",
      title: "Clara — Forged Power of Attorney",
      category: "document",
      description:
        "A Power of Attorney document was found in Clara's briefcase, granting Diane control of Richard's assets in case of incapacitation. The document is backdated to January 2024 and bears a forged version of Richard's signature. If valid, it would have given Diane control before the will change.",
      timestamp: "2024-08-03T22:00:00",
      location: "Clara's Briefcase",
      source: "Document Analysis",
      reliability: "high",
      metadata: {
        Document: "Power of Attorney — Diane as agent",
        Backdated: "January 2024",
        Signature: "Forged — Richard's name",
        Purpose: "Asset control before will change",
        Found: "In Clara's briefcase at the scene",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-006",
      title: "Yuki — Hidden Recording Device",
      category: "digital",
      description:
        "A hidden recording device was found in Yuki's kitchen station. It contains 3 months of audio recordings from Richard's dinner conversations. The recordings include Richard's private business discussions, personal conversations, and insulting remarks about guests. A media outlet contact was found in Yuki's phone — she was selling the recordings.",
      timestamp: "2024-08-03T23:00:00",
      location: "Kitchen",
      source: "Device Forensics",
      reliability: "high",
      metadata: {
        Device: "Hidden audio recorder",
        Duration: "3 months of recordings",
        Content: "Private dinner conversations",
        Recipient: "Media outlet contact",
        Purpose: "Selling to media",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-09"],
      isRedHerring: true,
      importance: 5,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "15:00",
      date: "2024-08-03",
      description: "Diane calls divorce lawyer about asset division.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "19:00",
      date: "2024-08-03",
      description:
        "Richard and Clara meet in study about billing fraud.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "19:30",
      date: "2024-08-03",
      description: "Jake enters wine cellar, browses for 8 minutes.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "19:45",
      date: "2024-08-03",
      description: "Clara texts Richard: 'We need to discuss before dessert.'",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "20:00",
      date: "2024-08-03",
      description: "Dinner begins. All guests seated.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-06",
      timestamp: "20:15",
      date: "2024-08-03",
      description: "First course served by Yuki.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "21:00",
      date: "2024-08-03",
      description:
        "Jake goes to guest bathroom — verified by housekeeper.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "21:15",
      date: "2024-08-03",
      description: "Jake returns from bathroom, passes behind Richard.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "21:30",
      date: "2024-08-03",
      description: "Main course served.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "21:35",
      date: "2024-08-03",
      description:
        "Margaret pours wine from the bottle for all guests.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-11",
      timestamp: "21:40",
      date: "2024-08-03",
      description: "Richard takes his first sip of wine.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "21:43",
      date: "2024-08-03",
      description:
        "Richard complains of tingling in his mouth and throat.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "21:45",
      date: "2024-08-03",
      description:
        "Richard collapses. Dr. Bello recognizes aconitine symptoms.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-14",
      timestamp: "21:50",
      date: "2024-08-03",
      description: "911 called by Jake. EMTs dispatched.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "22:30",
      date: "2024-08-03",
      description: "Richard pronounced dead at the estate.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Jake stated: 'The vial was just heartburn pills.'",
      contradictingEvidenceId: "EVIDENCE-02",
      suspectId: "SUSPECT-02",
      confidence: 96,
      explanation:
        "Lab analysis of the vial residue confirms aconitine — the same poison found in Richard's wine glass. Jake's claim that it was heartburn medication is directly contradicted by the forensic evidence.",
    },
    {
      id: "CONT-02",
      statementText:
        "Diane stated: 'I have never been in the garden shed.'",
      contradictingEvidenceId: "EVIDENCE-04",
      suspectId: "SUSPECT-01",
      confidence: 82,
      explanation:
        "The garden shed mortar contains monkshood residue, and Diane's fingerprints were found on the mortar's surface. She has been in the shed, despite her denial.",
    },
    {
      id: "CONT-03",
      statementText:
        "Clara stated: 'I never accessed the botanical records.'",
      contradictingEvidenceId: "EVIDENCE-07",
      suspectId: "SUSPECT-03",
      confidence: 94,
      explanation:
        "Estate computer logs show Clara's guest login accessing monkshood toxicity and aconitine dosage information 2 weeks before the dinner. Her claim is directly contradicted by digital evidence.",
    },
    {
      id: "CONT-04",
      statementText:
        "Yuki stated: 'I never went to the garden shed.'",
      contradictingEvidenceId: "EVIDENCE-09",
      suspectId: "SUSPECT-04",
      confidence: 91,
      explanation:
        "Estate security camera shows Yuki entering the garden shed at 2:00 PM on August 2 and emerging with a small bag 12 minutes later. Her personal mortar and pestle in the kitchen contains matching monkshood residue.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-02",
    motive:
      "Jake Morrison, Richard's former investee whose company was destroyed by Richard's hostile takeover, spent 2 months planning revenge. He researched aconitine extensively, harvested monkshood from the estate garden during a pre-dinner visit, and processed it into liquid form using his own equipment. At the dinner, he used his bathroom break at 9:00 PM to apply aconitine to the inside rim of Richard's wine glass using a tiny brush — the poison would dissolve instantly when wine was poured. He had the vial of concentrated aconitine in his pocket as backup. The housekeeper poured from the unmodified bottle, but the pre-treated glass delivered the lethal dose. Jake's 47 online searches and the vial in his jacket make him the clear perpetrator.",
    sequenceOfEvents: [
      "Jake's company was destroyed by Richard's hostile takeover 18 months ago.",
      "Jake begins researching aconitine and identifies monkshood in the estate garden.",
      "He makes a pre-dinner visit to the estate and harvests monkshood from the garden.",
      "He processes the plant into a concentrated aconitine solution at his apartment.",
      "On the night of August 3, he brings a vial of concentrated aconitine to the dinner.",
      "He enters the wine cellar at 7:30 PM to study the wine bottle and glass arrangement.",
      "At 9:00 PM, he asks to use the bathroom. He detours to the dining room first.",
      "He uses a tiny brush to apply aconitine to the inside rim of Richard's wine glass.",
      "He returns to his seat. No one notices his brief absence from the table.",
      "At 9:35 PM, Margaret pours wine into all glasses from the unmodified bottle.",
      "The wine dissolves the aconitine from the glass rim instantly.",
      "Richard drinks at 9:40 PM and collapses at 9:45 PM.",
    ],
    keyEvidenceIds: ["EVIDENCE-02", "EVIDENCE-08", "EVIDENCE-01"],
    redHerringIds: ["EVIDENCE-06", "EVIDENCE-12"],
    fullNarrative:
      "Jake Morrison spent 18 months planning the perfect revenge against Richard Slate. He researched aconitine exhaustively (47 searches), harvested monkshood from the estate's own garden, and concentrated the alkaloid into a brush-applied solution. At the dinner, he exploited a bathroom break to treat Richard's wine glass with the poison. When Margaret poured wine from the untouched bottle, the aconitine dissolved instantly in Richard's glass only. Jake carried the backup vial in his pocket — its contents matched the poison. The other suspects had real motives and suspicious behavior, but only Jake had the means (the vial), the opportunity (the bathroom break), and the premeditation (47 research searches) to execute the poisoning. Diane's allergen experiments and Clara's botanical research suggest they may have been planning their own actions, but Jake struck first.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
