import { Case } from "@/types";

export const lighthouseKeeperCase: Case = {
  metadata: {
    id: "CASE-007",
    title: "The Lighthouse Keeper",
    description:
      "Old Tom Weaver, the lighthouse keeper on Sable Island, was found dead at the base of the lighthouse stairs — a 147-foot fall. The island is accessible only by boat. A research team of four arrived by vessel the day before. They were the only people on the island. The lighthouse door was locked from inside. Tom's logbook has a torn page. One of them pushed him.",
    difficulty: "medium",
    location: "Sable Island Lighthouse, Sable Island, Nova Scotia",
    date: "October 5, 2024",
    evidenceCount: 12,
    suspectCount: 3,
    witnessCount: 2,
    status: "unsolved",
    type: "murder",
  },
  victim: {
    name: "Tom Weaver",
    age: 71,
    occupation: "Lighthouse Keeper",
    description:
      "Reclusive lighthouse keeper who has lived on Sable Island for 34 years. Former marine biologist who retreated from society after a research scandal. His logbook contains detailed observations of the island — and secrets about what washed ashore.",
    causeOfDeath: "Blunt force trauma — 147-foot fall from lighthouse gallery",
    lastSeen: "6:00 PM, alive in the lighthouse, per research team member",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Dr. Nina Vasquez",
      age: 42,
      occupation: "Marine Biologist / Research Team Lead",
      relationshipToVictim: "Former colleague from Tom's research days",
      motive:
        "Tom's logbook contains evidence of an illegal dumping site offshore — waste from Nina's current research institution. If the log is published, Nina loses her funding, her reputation, and faces criminal charges.",
      alibi: "I was in the research tent cataloging specimens from 4:00 PM until we found Tom at 7:00 AM the next morning.",
      alibiVerified: false,
      knownLocations: [
        "Research tent (claimed)",
        "Lighthouse — visited at 5:30 PM (per other team member)",
      ],
      communicationHistory: [
        "3:00 PM — Called her institution's director (5 min)",
        "5:45 PM — Sent an email: 'The old man knows about the site. We need a new plan.'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-04", "EVIDENCE-07"],
      suspicionScore: 75,
      personality:
        "Brilliant, ruthless when cornered, has built her career on cutting ethical corners. Genuinely passionate about marine science but willing to compromise principles for results.",
      secrets: [
        "Her institution has been dumping chemical waste offshore for 5 years",
        "She met with Tom at 5:30 PM and argued about the logbook",
        "Has a satellite phone hidden in her equipment — not part of official research kit",
      ],
      truthfulStatements: [
        "I am the research team lead.",
        "I visited the lighthouse at 5:30 PM to speak with Tom.",
      ],
      lies: [
        "I was in the tent all evening. (Another team member saw her heading toward the lighthouse at 5:30 PM)",
        "Tom and I had a friendly conversation. (They were heard arguing loudly)",
      ],
      refusesToDiscuss: [
        "The chemical waste dumping",
        "The satellite phone",
        "The argument with Tom",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Ben Carter",
      age: 35,
      occupation: "Research Assistant / Boat Captain",
      relationshipToVictim: "New to Sable Island, hired for this expedition",
      motive:
        "Ben is an undercover investigator for an environmental group. He has been documenting the illegal dumping and needs Tom's logbook as evidence. If Tom dies before the log is secured, the evidence chain breaks — but if someone else kills Tom, Ben's investigation continues.",
      alibi: "I was on the boat securing equipment. I didn't go to the lighthouse that evening.",
      alibiVerified: false,
      knownLocations: [
        "Research vessel (claimed)",
        "Island shoreline (seen walking at 6:30 PM)",
      ],
      communicationHistory: [
        "4:00 PM — Sent encrypted message to unknown recipient: 'The keeper has the proof. Securing tomorrow.'",
        "7:00 AM — Called emergency services from the boat's radio",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05", "EVIDENCE-08"],
      suspicionScore: 50,
      personality:
        "Principled, focused, operates with moral clarity that can become obsessive. Sees the investigation as more important than any individual — including Tom.",
      secrets: [
        "Undercover investigator — not a real research assistant",
        "Has a hidden camera in his jacket capturing the expedition",
        "Was seen near the lighthouse at 6:30 PM — during the likely time of death",
      ],
      truthfulStatements: [
        "I am here for the research expedition.",
        "I was securing equipment on the boat.",
      ],
      lies: [
        "I didn't go to the lighthouse that evening. (He was seen walking toward the lighthouse at 6:30 PM)",
        "I'm a marine biology assistant. (He is an undercover environmental investigator)",
      ],
      refusesToDiscuss: [
        "The encrypted message",
        "His real identity",
        "His 6:30 PM walk",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Dr. Liam Chen",
      age: 38,
      occupation: "Oceanographer",
      relationshipToVictim: "Met Tom once before, on a previous expedition",
      motive:
        "Liam discovered that Tom's lighthouse sits on a unique geological formation that could be worth millions in rare mineral rights. Tom refused to sell or lease the land. Liam has investors waiting. If Tom dies, the estate goes through probate — and Liam knows how to manipulate that process.",
      alibi: "I was in the geological survey tent processing data. I went to sleep at 9:00 PM.",
      alibiVerified: true,
      knownLocations: [
        "Geological survey tent (confirmed by instruments)",
        "Research tent (until 9:00 PM)",
      ],
      communicationHistory: [
        "2:00 PM — Called his investor: 'The land is within reach. Give me a week.'",
        "8:30 PM — Texted the team group chat: 'Good night all. Early start tomorrow.'",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-06"],
      suspicionScore: 35,
      personality:
        "Analytical, patient, plays long games. Views the world in terms of resource extraction and strategic positioning. Not violent but capable of manipulation.",
      secrets: [
        "Has already filed preliminary mineral rights paperwork",
        "The 'previous expedition' was actually a property survey",
        "Knows the island's tides — could have disposed of evidence at sea",
      ],
      truthfulStatements: [
        "I was in the survey tent processing data.",
        "I went to sleep at 9:00 PM.",
        "I did speak to Tom about the land.",
      ],
      lies: [
        "The previous expedition was routine research. (It was a targeted property survey)",
        "I have no financial interest in the island. (He has mineral rights investors waiting)",
      ],
      refusesToDiscuss: [
        "The mineral rights",
        "The preliminary paperwork",
        "The investor call",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Sarah O'Brien",
      age: 29,
      occupation: "Marine Research Technician",
      relationshipToVictim: "Team member, first to find Tom's body",
      statement:
        "I went to the lighthouse at 7:00 AM to ask Tom about weather conditions. The door was locked. I knocked several times. When there was no answer, I looked up and saw the gallery door was open. I climbed up and saw the gallery was empty. Then I looked down from the gallery and saw Tom at the base of the lighthouse. I called the others immediately.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-09"],
      personality: "Methodical, observant, shaken by finding the body.",
    },
    {
      id: "WITNESS-02",
      name: "GPS Data — Research Vessel",
      age: 0,
      occupation: "Navigation System",
      relationshipToVictim: "Automated witness — vessel tracking",
      statement:
        "The research vessel's GPS shows no movement from 5:00 PM to 8:00 AM. The boat was anchored in the bay. Ben Carter's phone (which he claimed was on the boat) was on the island's shoreline at 6:30 PM, not on the vessel.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05"],
      personality: "Impassive, precise, contradicts Ben's alibi.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "Sable Island Lighthouse",
      type: "Structure",
      address: "Sable Island, Eastern Point",
      description:
        "A 147-foot lighthouse built in 1873. Tom's living quarters are on the ground floor. The gallery at the top provides a 360-degree view of the island. The interior door was locked from inside with a key still in the lock.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-09"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02"],
    },
    {
      id: "LOC-02",
      name: "Research Camp",
      type: "Camp",
      address: "Sable Island, West Beach",
      description:
        "Temporary research camp with three tents: main research tent, geological survey tent, and equipment tent. Located 400 meters from the lighthouse.",
      relevantEvidence: ["EVIDENCE-03", "EVIDENCE-06"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-03"],
    },
    {
      id: "LOC-03",
      name: "Research Vessel",
      type: "Boat",
      address: "Sable Island Bay",
      description:
        "The team's boat, anchored in the bay. GPS tracking shows it did not move all night. Contains communication equipment and Ben's claimed alibi location.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-05"],
      relevantSuspects: ["SUSPECT-02"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-007",
      title: "Lighthouse Lock — Interior Key",
      category: "forensic",
      description:
        "The lighthouse interior door was locked from inside with the key in the lock. The key was found in the lock, on the interior side. Tom's fingerprints were on the key. However, the gallery door at the top was wide open. This suggests someone locked the door after Tom was already on the gallery.",
      timestamp: "2024-10-06T07:30:00",
      location: "Lighthouse Ground Floor",
      source: "Crime Scene Processing",
      reliability: "high",
      metadata: {
        DoorState: "Locked from interior",
        KeyPosition: "In lock, interior side",
        Fingerprints: "Tom's on key",
        GalleryDoor: "Wide open at top",
        Conclusion: "Door locked after Tom went to gallery",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-09"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-007",
      title: "Ben's Phone — GPS Location",
      category: "digital",
      description:
        "Ben's phone GPS shows he was on the island's eastern shoreline at 6:30 PM — not on the boat as he claimed. The lighthouse is a 5-minute walk from the shoreline. At 6:50 PM, the phone moved back toward the boat. Ben was ashore during the estimated time of death (6:00-7:00 PM).",
      timestamp: "2024-10-05T18:30:00",
      location: "Sable Island Shoreline",
      source: "Phone GPS Records",
      reliability: "high",
      metadata: {
        Location630PM: "Eastern shoreline — island, not boat",
        DistanceToLighthouse: "5-minute walk",
        ReturnToBoat: "6:50 PM",
        BoatClaim: "Ben said he was on boat all evening",
        TimeOfDeath: "6:00-7:00 PM (estimated)",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-007",
      title: "Tom's Logbook — Torn Page",
      category: "document",
      description:
        "Tom's handwritten logbook has a page torn out. The page before (October 4) reads: 'Four strangers arrived today. The woman — Dr. Vasquez — she was at the dumping site meeting in 2019. She thinks I don't remember. I remember everything.' The torn page likely contained details about the illegal dumping coordinates.",
      timestamp: "2024-10-04T00:00:00",
      location: "Lighthouse Living Quarters",
      source: "Logbook Analysis",
      reliability: "high",
      metadata: {
        TornPage: "After October 4 entry",
        PreviousEntry: "Identified Nina at dumping site",
        Content: "Likely dumping coordinates",
        TomMemory: "Long-term documentation of illegal activity",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-07"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-007",
      title: "Nina's Satellite Phone",
      category: "digital",
      description:
        "A satellite phone was found hidden in Nina's research equipment. The phone shows calls to her institution's director on October 3 and October 5. The October 5 call (3:00 PM) discussed 'the old man and the records.' Nina did not disclose the satellite phone as part of the research kit.",
      timestamp: "2024-10-05T15:00:00",
      location: "Research Tent",
      source: "Phone Analysis",
      reliability: "high",
      metadata: {
        Device: "Satellite phone — undisclosed",
        Calls: "October 3 and 5 to institution director",
        October5Topic: "'The old man and the records'",
        Disclosure: "Not part of official research kit",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-07"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-007",
      title: "Vessel GPS — Ben's Movement",
      category: "digital",
      description:
        "Research vessel GPS confirms no movement all night. However, Ben's phone left the vessel at 6:15 PM, was on the eastern shoreline at 6:30 PM, and returned to the vessel at 6:50 PM. The vessel's small dinghy was found pulled up on the shore at 7:00 AM — indicating someone used it to reach shore.",
      timestamp: "2024-10-05T18:15:00",
      location: "Research Vessel",
      source: "GPS + Dinghy Evidence",
      reliability: "high",
      metadata: {
        VesselMovement: "Anchored all night",
        BenPhone: "Left vessel 6:15 PM, shore 6:30 PM, back 6:50 PM",
        Dinghy: "Found on shore at 7:00 AM — used by someone",
        Gap: "35 minutes on island during time of death",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-007",
      title: "Liam's Geological Survey Data",
      category: "document",
      description:
        "Liam's survey tent contains detailed geological scans of the lighthouse area. The data shows rare mineral deposits beneath the lighthouse foundation. Liam's notes include a section titled 'Acquisition Strategy' with notes about probate law and mineral rights transfer upon death of current holder.",
      timestamp: "2024-10-03T00:00:00",
      location: "Geological Survey Tent",
      source: "Document Analysis",
      reliability: "high",
      metadata: {
        Findings: "Rare minerals under lighthouse foundation",
        Strategy: "Acquisition through probate manipulation",
        Notes: "Mineral rights transfer on death of holder",
        Investors: "Referenced but not named",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-007",
      title: "Nina's Email — 'We need a new plan'",
      category: "message",
      description:
        "Nina sent an email at 5:45 PM — 15 minutes after visiting Tom — to her institution director: 'The old man knows about the site. We need a new plan. He won't destroy the log.' The email was sent from her personal account, not institutional email.",
      timestamp: "2024-10-05T17:45:00",
      location: "Research Tent",
      source: "Email Forensics",
      reliability: "high",
      metadata: {
        To: "Institution director",
        Time: "5:45 PM — 15 min after lighthouse visit",
        Content: "'The old man knows about the site. We need a new plan.'",
        Account: "Personal — not institutional",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-04"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-007",
      title: "Ben's Hidden Camera Footage",
      category: "cctv",
      description:
        "A hidden camera in Ben's jacket captured footage from the island. At 6:25 PM, the camera shows the lighthouse in the distance. At 6:32 PM, the camera captures a figure at the base of the lighthouse — it appears to be Nina, not Ben. Ben's camera was on the shoreline but he was not at the lighthouse himself.",
      timestamp: "2024-10-05T18:25:00",
      location: "Eastern Shoreline",
      source: "Hidden Camera",
      reliability: "medium",
      metadata: {
        CameraLocation: "Ben's jacket",
        Footage630PM: "Lighthouse in distance",
        Footage632PM: "Figure at lighthouse base — appears to be Nina",
        BenLocation: "On shoreline, not at lighthouse",
        Resolution: "Medium — partially obscured",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-05"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-007",
      title: "Lighthouse Gallery — Forensic Analysis",
      category: "forensic",
      description:
        "The gallery railing shows Tom's fingerprints on the top rail — consistent with someone climbing over. However, there are also two sets of additional fingerprints on the inner side of the railing: one matches Nina, one is unknown. The railing height is 42 inches — Tom would need to climb over voluntarily or be pushed.",
      timestamp: "2024-10-06T08:00:00",
      location: "Lighthouse Gallery",
      source: "Forensic Analysis",
      reliability: "high",
      metadata: {
        TomFingerprints: "Top rail — climbing over",
        NinaFingerprints: "Inner side of railing",
        UnknownPrints: "Second set on inner railing",
        RailingHeight: "42 inches",
        Conclusion: "Tom climbed or was pushed over",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-007",
      title: "Nina's Argument with Tom — Audio Evidence",
      category: "audio",
      description:
        "Ben's hidden camera, while on the shoreline, picked up faint audio from the lighthouse direction at 5:35 PM. Analysis reveals a heated argument between a man (Tom) and a woman (Nina). Key phrases: 'You can't bury this' (Tom) and 'I'll do whatever it takes' (Nina).",
      timestamp: "2024-10-05T17:35:00",
      location: "Lighthouse",
      source: "Audio Enhancement",
      reliability: "medium",
      metadata: {
        Time: "5:35 PM",
        Speakers: "Tom and Nina (voice-identified)",
        TomPhrase: "'You can't bury this'",
        NinaPhrase: "'I'll do whatever it takes'",
        Quality: "Faint — enhanced from shoreline distance",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-07", "EVIDENCE-03"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-007",
      title: "Tidal Analysis — Evidence Disposal Window",
      category: "document",
      description:
        "Nova Scotia tidal charts show that the island's eastern shore has a high tide at 11:00 PM. Any items disposed of in the water between 9:00 PM and midnight would be carried out to sea. This window would be ideal for disposing of the torn logbook page.",
      timestamp: "2024-10-05T23:00:00",
      location: "Sable Island Shoreline",
      source: "Tidal Chart Analysis",
      reliability: "high",
      metadata: {
        HighTide: "11:00 PM",
        DisposalWindow: "9:00 PM to midnight",
        Direction: "Out to sea from eastern shore",
        ItemsDisposed: "Likely torn logbook page",
        Evidence: "None recovered from water",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-03"],
      isRedHerring: false,
      importance: 6,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-007",
      title: "Nina's Boots — Mud Analysis",
      category: "forensic",
      description:
        "Nina's boots, found in the research tent, show fresh mud on the soles matching the soil composition around the lighthouse base. The mud contains traces of lichen found only on the northern lighthouse path — a path Nina claimed she never took.",
      timestamp: "2024-10-06T09:00:00",
      location: "Research Tent",
      source: "Soil Analysis",
      reliability: "high",
      metadata: {
        BootLeft: "Fresh mud — lighthouse base soil",
        BootRight: "Matching composition",
        Lichen: "Northern path — unique to that route",
        NinaClaim: "Never took northern path",
        Conclusion: "Nina was at the lighthouse base",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-09", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 9,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "09:00",
      date: "2024-10-05",
      description:
        "Research team arrives by boat. Tom meets them at the dock.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "14:00",
      date: "2024-10-05",
      description:
        "Liam calls investor about mineral rights.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "15:00",
      date: "2024-10-05",
      description:
        "Nina calls institution director about 'the old man and the records.'",
      evidenceIds: ["EVIDENCE-04"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "16:00",
      date: "2024-10-05",
      description:
        "Nina enters research tent, begins cataloging specimens.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "17:30",
      date: "2024-10-05",
      description:
        "Nina leaves research tent, walks to lighthouse.",
      evidenceIds: ["EVIDENCE-10"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "17:35",
      date: "2024-10-05",
      description:
        "Nina and Tom argue at the lighthouse. 'You can't bury this.'",
      evidenceIds: ["EVIDENCE-10"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "17:45",
      date: "2024-10-05",
      description:
        "Nina sends email: 'The old man knows about the site. We need a new plan.'",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "18:00",
      date: "2024-10-05",
      description:
        "Tom last seen alive in the lighthouse, per team member.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-09",
      timestamp: "18:15",
      date: "2024-10-05",
      description:
        "Ben takes dinghy from boat to shoreline.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "18:25",
      date: "2024-10-05",
      description:
        "Ben's hidden camera captures lighthouse in distance.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "18:32",
      date: "2024-10-05",
      description:
        "Ben's camera captures figure at lighthouse base — appears to be Nina.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "18:30",
      date: "2024-10-05",
      description:
        "Estimated time of Tom's fall from the gallery.",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: [],
      verified: false,
      locationId: "LOC-01",
    },
    {
      id: "TL-13",
      timestamp: "18:50",
      date: "2024-10-05",
      description:
        "Ben returns to boat via dinghy.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-14",
      timestamp: "20:30",
      date: "2024-10-05",
      description:
        "Liam texts group chat: 'Good night all.'",
      evidenceIds: [],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "21:00",
      date: "2024-10-05",
      description:
        "Liam goes to sleep in geological survey tent.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-16",
      timestamp: "23:00",
      date: "2024-10-05",
      description:
        "High tide — disposal window for torn logbook page.",
      evidenceIds: ["EVIDENCE-11"],
      suspectIds: [],
      verified: false,
    },
    {
      id: "TL-17",
      timestamp: "07:00",
      date: "2024-10-06",
      description:
        "Sarah finds Tom's body at base of lighthouse.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Nina stated: 'I was in the tent cataloging specimens from 4:00 PM.'",
      contradictingEvidenceId: "EVIDENCE-08",
      suspectId: "SUSPECT-01",
      confidence: 88,
      explanation:
        "Ben's hidden camera captures a figure matching Nina's appearance at the lighthouse base at 6:32 PM — 2.5 hours after she claims to have entered the tent. Additionally, her boots contain mud from the lighthouse base with unique lichen from the northern path.",
    },
    {
      id: "CONT-02",
      statementText:
        "Ben stated: 'I was on the boat securing equipment.'",
      contradictingEvidenceId: "EVIDENCE-05",
      suspectId: "SUSPECT-02",
      confidence: 93,
      explanation:
        "GPS data shows Ben's phone was on the island's eastern shoreline from 6:15 PM to 6:50 PM — the dinghy was found on shore at 7:00 AM. He was on the island during the estimated time of death, not on the boat.",
    },
    {
      id: "CONT-03",
      statementText:
        "Liam stated: 'The previous expedition was routine research.'",
      contradictingEvidenceId: "EVIDENCE-06",
      suspectId: "SUSPECT-03",
      confidence: 80,
      explanation:
        "Liam's geological survey data includes a section titled 'Acquisition Strategy' about mineral rights under the lighthouse. His previous expedition was actually a targeted property survey — not routine research.",
    },
    {
      id: "CONT-04",
      statementText:
        "Nina stated: 'Tom and I had a friendly conversation.'",
      contradictingEvidenceId: "EVIDENCE-10",
      suspectId: "SUSPECT-01",
      confidence: 85,
      explanation:
        "Audio captured from Ben's camera reveals a heated argument between Tom and Nina at 5:35 PM. Tom said 'You can't bury this' and Nina responded 'I'll do whatever it takes' — this was not a friendly conversation.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-01",
    motive:
      "Dr. Nina Vasquez, upon learning that Tom's logbook documented the illegal chemical dumping by her institution, realized her career and freedom were at stake. She confronted Tom at 5:30 PM, demanding he surrender the logbook. He refused. She returned to the lighthouse at approximately 6:20 PM, followed Tom to the gallery under the pretense of continuing their discussion, and pushed him over the railing. She locked the lighthouse door from inside using Tom's key (which she took temporarily), then exited through the gallery. She disposed of the torn logbook page at high tide (11:00 PM). Her boots, email, and the fingerprints on the gallery railing all place her at the scene.",
    sequenceOfEvents: [
      "Nina's institution has been dumping chemical waste offshore for 5 years.",
      "Tom's logbook documented the dumping site and the people involved.",
      "Nina visits Tom at 5:30 PM and argues about the logbook.",
      "She sends an email to her director at 5:45 PM: 'We need a new plan.'",
      "She returns to the lighthouse at approximately 6:20 PM.",
      "Tom is on the gallery. She follows him up.",
      "She pushes Tom over the railing at approximately 6:30 PM.",
      "She goes downstairs, locks the door from inside with Tom's key, and exits through the gallery.",
      "She returns to the research tent, leaving muddy boots that match the lighthouse base.",
      "At 11:00 PM, she disposes of the torn logbook page at high tide.",
      "Ben was on the shoreline at 6:30 PM filming for his undercover investigation — he captured Nina at the lighthouse base but didn't realize the significance.",
    ],
    keyEvidenceIds: ["EVIDENCE-09", "EVIDENCE-12", "EVIDENCE-08", "EVIDENCE-07"],
    redHerringIds: [],
    fullNarrative:
      "Dr. Nina Vasquez killed Tom Weaver to destroy evidence of her institution's illegal chemical dumping. Tom's logbook was the only comprehensive record of the dumping site, and Nina had been identified by Tom as someone involved in the 2019 dumping meeting. After their argument at 5:30 PM, Nina returned to the lighthouse and pushed Tom from the gallery. She locked the door from inside using his key to create the appearance of an impossible crime. Her email to her director, her fingerprints on the gallery railing, her muddy boots matching the lighthouse base, and Ben's hidden camera footage all converge on Nina as the killer. The torn logbook page was disposed of at high tide, removing the most direct evidence. Ben's presence on the shoreline was for his own undercover investigation — he was an environmental investigator, not a research assistant — and his camera inadvertently captured Nina at the scene.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
