import { Case } from "@/types";

export const lockedRoomCase: Case = {
  metadata: {
    id: "CASE-001",
    title: "The Locked Room",
    description:
      "A wealthy art collector is found dead in his private study — a room locked from the inside. No signs of forced entry. The security system was active. Three people had access to the building that evening. One of them is lying.",
    difficulty: "easy",
    location: "Ashworth Manor, Greenwich Village, New York",
    date: "March 15, 2024",
    evidenceCount: 12,
    suspectCount: 3,
    witnessCount: 2,
    status: "unsolved",
    type: "murder",
  },
  victim: {
    name: "Harold Ashworth",
    age: 67,
    occupation: "Art Collector & Gallery Owner",
    description:
      "Wealthy art collector known for his extensive private collection. Recently changed his will, cutting out his nephew. Had a reputation for being difficult and secretive.",
    causeOfDeath: "Poisoning — digitalis derived compound found in evening brandy",
    lastSeen: "8:45 PM by his housekeeper, entering his study",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Victoria Ashworth",
      age: 42,
      occupation: "Art Dealer",
      relationshipToVictim: "Wife (second marriage)",
      motive:
        "Stands to inherit the entire estate after the will change. Recent argument about selling a rare painting worth $2.3M.",
      alibi: "I was in the bedroom reading. I went to sleep around 9:30 PM.",
      alibiVerified: false,
      knownLocations: [
        "Ashworth Manor — Bedroom (2nd floor)",
        "Metropolitan Gallery (afternoon)",
      ],
      communicationHistory: [
        "8:12 PM — Called her lawyer (3 min call)",
        "9:01 PM — Texted friend: 'Tonight everything changes'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-03", "EVIDENCE-07"],
      suspicionScore: 65,
      personality:
        "Calm, composed, occasionally cold. Speaks precisely. Avoids emotional topics. Gets defensive when questioned about finances.",
      secrets: [
        "Has a secret bank account in the Cayman Islands",
        "Was planning to leave Harold before the will change",
      ],
      truthfulStatements: [
        "I did argue with Harold about the painting.",
        "I was in the bedroom that evening.",
      ],
      lies: [
        "I was asleep by 9:30 PM. (Phone records show activity at 10:15 PM)",
        "I had no idea about the will change. (She was informed by the lawyer on March 10)",
      ],
      refusesToDiscuss: [
        "The Cayman Islands bank account",
        "Her relationship with Dr. Reeves",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Marcus Ashworth",
      age: 28,
      occupation: "Unemployed Artist",
      relationshipToVictim: "Nephew (son of Harold's late brother)",
      motive:
        "Recently cut out of the will. Had $40,000 in gambling debts. Was seen arguing with Harold two days before the murder.",
      alibi: "I left the manor at 8:30 PM. I was at O'Malley's Bar until closing.",
      alibiVerified: false,
      knownLocations: [
        "Ashworth Manor (visited that evening)",
        "O'Malley's Bar (claimed)",
        "Apartment in Brooklyn",
      ],
      communicationHistory: [
        "7:45 PM — Texted Harold: 'We need to talk Uncle H'",
        "8:22 PM — Called friend Danny (2 min)",
        "11:30 PM — Texted Danny: 'Bad night'",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05", "EVIDENCE-08"],
      suspicionScore: 58,
      personality:
        "Nervous, fidgety, talks too much when anxious. Quick to blame others. Has a good heart underneath but makes terrible decisions.",
      secrets: [
        "Borrowed money from a dangerous lender",
        "Saw something at the manor but is afraid to say what",
      ],
      truthfulStatements: [
        "I did argue with Uncle Harold about money.",
        "I was at O'Malley's that night.",
        "I left the manor at 8:30 PM.",
      ],
      lies: [
        "I didn't go back to the manor after leaving. (But his jacket was found in the study hallway)",
        "I don't know anything about the will. (He was told about being cut out)",
      ],
      refusesToDiscuss: [
        "How much he owes",
        "What he saw in the hallway",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Dr. Eleanor Reeves",
      age: 55,
      occupation: "Personal Physician",
      relationshipToVictim: "Harold's doctor for 12 years",
      motive:
        "Harold discovered she had been overcharging him for years and threatened to report her to the medical board. Could lose her license.",
      alibi: "I visited Harold at 7:00 PM for a routine check-up. I left at 8:15 PM.",
      alibiVerified: true,
      knownLocations: [
        "Ashworth Manor (7:00 PM — 8:15 PM)",
        "Greenwich Medical Center (until 6:30 PM)",
        "Her apartment (after 9:00 PM)",
      ],
      communicationHistory: [
        "6:55 PM — Called Harold's landline (1 min)",
        "8:20 PM — Called Victoria (unanswered)",
        "10:45 PM — Called hospital (5 min)",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-06", "EVIDENCE-09", "EVIDENCE-11"],
      suspicionScore: 72,
      personality:
        "Professional, authoritative, slightly arrogant. Uses medical knowledge to deflect suspicion. Gets flustered when her competence is questioned.",
      secrets: [
        "Has been overbilling Harold for 3 years",
        "Has a personal relationship with Victoria",
        "Has access to digitalis through her practice",
      ],
      truthfulStatements: [
        "I did visit Harold at 7:00 PM.",
        "I left at 8:15 PM.",
        "I am his personal physician.",
      ],
      lies: [
        "The visit was routine. (She was actually confronted about the overbilling)",
        "I have no reason to harm Harold. (He threatened to report her)",
        "I don't know anything about the will changes. (Victoria told her about it)",
      ],
      refusesToDiscuss: [
        "The overbilling accusation",
        "Her relationship with Victoria",
        "Her access to digitalis",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "James Patterson",
      age: 45,
      occupation: "Security Guard",
      relationshipToVictim: "Night security at Ashworth Manor for 5 years",
      statement:
        "I saw Dr. Reeves leave at 8:15 PM. Marcus left around 8:30 PM. Victoria's light was off by 9:45 PM. At 10:30 PM, I noticed the study light was still on, which was unusual — Harold usually turned it off by 10. I didn't check because he had strict orders never to disturb him in the study.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-02", "EVIDENCE-10"],
      personality: "Dutiful, observant, nervous about being involved.",
    },
    {
      id: "WITNESS-02",
      name: "Doris Chen",
      age: 34,
      occupation: "Housekeeper",
      relationshipToVictim: "Housekeeper at Ashworth Manor for 3 years",
      statement:
        "I served Mr. Ashworth his evening brandy at 8:40 PM in the study. He was alive and well. He seemed agitated — kept looking at his watch. I left the brandy and a glass on his desk. The study door was closed but not locked when I left.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-06", "EVIDENCE-12"],
      personality: "Meticulous, quiet, noticed more than she lets on.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "Private Study",
      type: "Room",
      address: "Ashworth Manor, 1st Floor East Wing",
      description:
        "Harold's private study. Heavy oak door with a deadbolt lock (key-only, from inside). Contains his personal desk, art collection records, and a small bar cart. The room has one window, which was locked and latched from inside.",
      relevantEvidence: ["EVIDENCE-03", "EVIDENCE-06", "EVIDENCE-12"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-03"],
    },
    {
      id: "LOC-02",
      name: "Main Hallway",
      type: "Corridor",
      address: "Ashworth Manor, 1st Floor",
      description:
        "The main hallway connecting the study, living room, and front entrance. Contains one security camera (north entrance).",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-02", "EVIDENCE-10"],
      relevantSuspects: ["SUSPECT-02"],
    },
    {
      id: "LOC-03",
      name: "Guest Bedroom",
      type: "Room",
      address: "Ashworth Manor, 2nd Floor",
      description:
        "Victoria's bedroom. Contains personal items, a phone charger, and a window facing the garden.",
      relevantEvidence: ["EVIDENCE-07"],
      relevantSuspects: ["SUSPECT-01"],
    },
    {
      id: "LOC-04",
      name: "Kitchen",
      type: "Room",
      address: "Ashworth Manor, Ground Floor",
      description:
        "Where Doris prepared the evening brandy. Contains poison-free supplies, but has access to the garden shed.",
      relevantEvidence: ["EVIDENCE-06", "EVIDENCE-09"],
      relevantSuspects: ["SUSPECT-03"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-001",
      title: "Security Camera — North Entrance",
      category: "cctv",
      description:
        "CCTV footage from the north entrance shows Dr. Reeves leaving at 8:15 PM and Marcus leaving at 8:30 PM. At 10:12 PM, the camera captures a figure re-entering through the north entrance, but the image is too dark to identify clearly.",
      timestamp: "2024-03-15T22:12:00",
      location: "North Entrance",
      source: "Building Security Camera",
      reliability: "high",
      metadata: {
        Camera: "North Entrance CAM-02",
        Resolution: "720p",
        Lighting: "Low (night mode)",
        Duration: "3 hours",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-001",
      title: "Marcus's Phone Records",
      category: "digital",
      description:
        "Phone records show Marcus called Danny at 8:22 PM (2 minutes). His phone was at the manor location until 8:35 PM. His phone then pinged a tower near O'Malley's Bar from 8:55 PM onward. However, there is a gap — his phone went dark from 8:35 PM to 8:55 PM.",
      timestamp: "2024-03-15T20:35:00",
      location: "Mobile Network",
      source: "Phone Carrier Records",
      reliability: "high",
      metadata: {
        Carrier: "Verizon",
        Tower1: "Greenwich Village Tower A",
        Tower2: "O'Malley's Vicinity Tower",
        Gap: "20 minutes (8:35 PM - 8:55 PM)",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-05"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-001",
      title: "Brandy Glass — Toxicology Report",
      category: "forensic",
      description:
        "The brandy glass found on Harold's desk contained traces of digitalis — a cardiac glycoside that in high doses causes fatal heart arrhythmia. The concentration was lethal. No fingerprints other than Harold's and Doris's were found on the glass.",
      timestamp: "2024-03-16T09:00:00",
      location: "Private Study",
      source: "Forensic Lab Report",
      reliability: "high",
      metadata: {
        Substance: "Digitalis (digoxin derivative)",
        Concentration: "Lethal (0.08 mg/mL)",
        Fingerprints: "Harold Ashworth, Doris Chen",
        GlassType: "Crystal brandy snifter",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-06", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-001",
      title: "Dr. Reeves' Medical Supply Log",
      category: "document",
      description:
        "Dr. Reeves' practice keeps records of controlled substances. The log shows digitalis prescriptions for patients, but there is an unexplained discrepancy: 3 fewer vials of digoxin in inventory than accounted for by prescriptions. The discrepancy spans the last 6 months.",
      timestamp: "2024-03-16T14:00:00",
      location: "Greenwich Medical Center",
      source: "Medical Board Audit",
      reliability: "high",
      metadata: {
        MissingVials: "3",
        Substance: "Digoxin 0.25mg/mL",
        Period: "September 2023 — March 2024",
        AuditBy: "NY Medical Board",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-001",
      title: "Marcus's Jacket",
      category: "object",
      description:
        "A leather jacket belonging to Marcus was found draped over a chair in the hallway outside the study. Marcus claims he left at 8:30 PM and did not return. The jacket has a faint smell of cigarette smoke and contains a matchbook from O'Malley's Bar.",
      timestamp: "2024-03-16T07:30:00",
      location: "Main Hallway",
      source: "Crime Scene Processing",
      reliability: "medium",
      metadata: {
        Item: "Brown leather jacket, size M",
        Condition: "Clean, no damage",
        Contents: "Matchbook from O'Malley's Bar",
        FoundBy: "Officer Martinez",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-001",
      title: "Kitchen Bar Cart Log",
      category: "document",
      description:
        "Doris keeps a handwritten log of drinks served. She recorded serving brandy to Harold at 8:40 PM. The brandy bottle was from a sealed decanter that Doris opened that evening. The decanter was not tampered with — the poison was not in the bottle.",
      timestamp: "2024-03-15T20:40:00",
      location: "Kitchen",
      source: "Housekeeper's Records",
      reliability: "medium",
      metadata: {
        Drink: "Brandy (VSOP cognac)",
        Time: "8:40 PM",
        Decanter: "Sealed, no tampering",
        Notes: "Standard evening serving",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-001",
      title: "Victoria's Phone Activity",
      category: "digital",
      description:
        "Victoria's phone records show a call to her lawyer at 8:12 PM (3 minutes). At 9:01 PM she texted a friend: 'Tonight everything changes.' At 10:15 PM, her phone shows a web search for 'how long does poison take to work.'",
      timestamp: "2024-03-15T22:15:00",
      location: "Bedroom (2nd Floor)",
      source: "Phone Forensic Extraction",
      reliability: "high",
      metadata: {
        Calls: "Lawyer — 8:12 PM (3 min)",
        Text: "9:01 PM — 'Tonight everything changes'",
        WebSearch: "10:15 PM — 'how long does poison take to work'",
        Device: "iPhone 15 Pro",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-001",
      title: "Gambling Debt Records",
      category: "financial",
      description:
        "Bank records and loan documents show Marcus owes $40,000 to a private lender known as 'Vegas Tony.' The lender has been threatening Marcus. The debt was due on March 20 — five days after the murder.",
      timestamp: "2024-03-10T00:00:00",
      location: "Brooklyn, NY",
      source: "Financial Investigation",
      reliability: "high",
      metadata: {
        Amount: "$40,000",
        Lender: "Vegas Tony (private)",
        DueDate: "March 20, 2024",
        Threats: "Multiple threatening messages",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-05"],
      isRedHerring: true,
      importance: 5,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-001",
      title: "Garden Shed — Digitalis Plant",
      category: "forensic",
      description:
        "The garden at Ashworth Manor contains foxglove plants (Digitalis purpurea), which naturally produce digitalis compounds. The garden shed contains gardening tools and a grinding mortar. Recent use of the mortar is noted — within the last week.",
      timestamp: "2024-03-16T11:00:00",
      location: "Garden Shed",
      source: "Crime Scene Search",
      reliability: "medium",
      metadata: {
        Plant: "Foxglove (Digitalis purpurea)",
        Mortar: "Recently used (within 7 days)",
        Access: "Kitchen door leads to garden",
        Notes: "Anyone with garden access could harvest digitalis",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-04"],
      isRedHerring: true,
      importance: 6,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-001",
      title: "Window Lock Analysis",
      category: "forensic",
      description:
        "The study window was locked from the inside. Forensic analysis confirms the latch was engaged and the window had not been opened recently. No tool marks. The window is too narrow for an adult to climb through.",
      timestamp: "2024-03-16T08:00:00",
      location: "Private Study",
      source: "Forensic Analysis",
      reliability: "high",
      metadata: {
        Window: "Casement, 24 inches wide",
        LockState: "Latched from inside",
        ToolMarks: "None",
        Conclusion: "Window was not used as entry/exit",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-12"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-001",
      title: "Victoria & Eleanor's Communication",
      category: "message",
      description:
        "Extracted text messages reveal Victoria and Dr. Reeves have been in regular contact. Messages discuss 'the plan,' 'after it's done,' and 'the will.' The most recent message from Victoria to Eleanor at 8:20 PM reads: 'He knows. We need to move tonight.'",
      timestamp: "2024-03-15T20:20:00",
      location: "Digital Communication",
      source: "Phone Forensic Extraction",
      reliability: "high",
      metadata: {
        From: "Victoria Ashworth",
        To: "Dr. Eleanor Reeves",
        Time: "8:20 PM",
        Message: "'He knows. We need to move tonight.'",
        Context: "Part of ongoing conversation thread",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-07", "EVIDENCE-04"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-001",
      title: "Study Door Lock — Forensic Report",
      category: "forensic",
      description:
        "The study door deadbolt was locked from the inside using a key. The key was found in the lock, on the interior side. Only two keys exist for this lock — one was found on Harold's body, the other is missing. No signs of picking or forced entry.",
      timestamp: "2024-03-16T10:00:00",
      location: "Private Study",
      source: "Forensic Locksmith Report",
      reliability: "high",
      metadata: {
        LockType: "Yale deadbolt, single-cylinder",
        KeyPosition: "Interior side of door",
        KeysExisting: "2 (1 found on victim, 1 missing)",
        ForcedEntry: "None",
        Picking: "No marks",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-10", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 10,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "18:30",
      date: "2024-03-15",
      description: "Doris arrives for evening shift. Prepares study for Harold.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: [],
      locationId: "LOC-04",
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "19:00",
      date: "2024-03-15",
      description: "Dr. Reeves arrives for routine check-up.",
      evidenceIds: ["EVIDENCE-04"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "19:00",
      date: "2024-03-15",
      description:
        "Harold calls landline to confirm appointment with Dr. Reeves.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "19:15",
      date: "2024-03-15",
      description:
        "Dr. Reeves confronts Harold about the overbilling accusation.",
      evidenceIds: ["EVIDENCE-11"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-05",
      timestamp: "19:30",
      date: "2024-03-15",
      description: "Marcus arrives at the manor. Argument with Harold.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "20:12",
      date: "2024-03-15",
      description: "Victoria calls her lawyer. Discusses estate matters.",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "20:15",
      date: "2024-03-15",
      description: "Dr. Reeves leaves the manor. Seen by security.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "20:20",
      date: "2024-03-15",
      description:
        "Victoria texts Eleanor: 'He knows. We need to move tonight.'",
      evidenceIds: ["EVIDENCE-11"],
      suspectIds: ["SUSPECT-01", "SUSPECT-03"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "20:22",
      date: "2024-03-15",
      description: "Marcus calls Danny (2 min).",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "20:30",
      date: "2024-03-15",
      description: "Marcus leaves the manor. Security sees him exit.",
      evidenceIds: ["EVIDENCE-01", "EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "20:35",
      date: "2024-03-15",
      description: "Marcus's phone goes dark (leaves manor area).",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "20:40",
      date: "2024-03-15",
      description: "Doris serves Harold evening brandy in the study.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "20:45",
      date: "2024-03-15",
      description: "Harold enters study with brandy. Door is closed but not locked.",
      evidenceIds: ["EVIDENCE-12"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-14",
      timestamp: "21:01",
      date: "2024-03-15",
      description: "Victoria texts friend: 'Tonight everything changes.'",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "21:30",
      date: "2024-03-15",
      description: "Victoria's bedroom light goes off. Security confirms.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-16",
      timestamp: "22:03",
      date: "2024-03-15",
      description: "UNEXPLAINED GAP — No verified activity.",
      evidenceIds: [],
      suspectIds: [],
      verified: false,
      isGap: true,
      gapStart: "21:30",
      gapEnd: "22:12",
    },
    {
      id: "TL-17",
      timestamp: "22:12",
      date: "2024-03-15",
      description: "CCTV captures unknown figure re-entering north entrance.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-18",
      timestamp: "22:15",
      date: "2024-03-15",
      description: "Victoria's phone: web search for poison timing.",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-19",
      timestamp: "22:30",
      date: "2024-03-15",
      description: "Study light noted as still on by security (unusual).",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-20",
      timestamp: "23:00",
      date: "2024-03-15",
      description:
        "Estimated time of death based on toxicology. Harold consumes poisoned brandy.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: false,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Marcus stated: 'I left at 8:30 PM and did not return to the manor.'",
      contradictingEvidenceId: "EVIDENCE-05",
      suspectId: "SUSPECT-02",
      confidence: 78,
      explanation:
        "Marcus's jacket was found in the hallway outside the study. If he left at 8:30 PM and never returned, his jacket would not be there. He likely returned to the manor later that evening.",
    },
    {
      id: "CONT-02",
      statementText:
        "Victoria stated: 'I was asleep by 9:30 PM.'",
      contradictingEvidenceId: "EVIDENCE-07",
      suspectId: "SUSPECT-01",
      confidence: 94,
      explanation:
        "Victoria's phone shows a web search at 10:15 PM. If she was asleep, she would not have been using her phone. She was awake and searching for information about poison timing.",
    },
    {
      id: "CONT-03",
      statementText:
        "Dr. Reeves stated: 'The visit was routine.'",
      contradictingEvidenceId: "EVIDENCE-11",
      suspectId: "SUSPECT-03",
      confidence: 89,
      explanation:
        "Victoria's text at 8:20 PM says 'He knows. We need to move tonight.' This suggests the visit was not routine — Harold had discovered something and confronted Dr. Reeves about it.",
    },
    {
      id: "CONT-04",
      statementText:
        "Victoria stated: 'I had no idea about the will change.'",
      contradictingEvidenceId: "EVIDENCE-11",
      suspectId: "SUSPECT-01",
      confidence: 85,
      explanation:
        "Communications between Victoria and Dr. Reeves reference 'the will' and 'after it's done,' indicating Victoria was fully aware of the will changes and was planning accordingly.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-03",
    motive:
      "Dr. Reeves was being blackmailed by Harold after he discovered her systematic overbilling. She conspired with Victoria — who she was having a relationship with — to poison Harold. Victoria provided the opportunity (she knew the study layout and key locations), while Eleanor provided the means (digitalis from her medical practice, processed using the garden mortar and foxglove). Eleanor administered the poison to the brandy glass after Doris served it, using a small syringe she brought in her medical bag. The missing key was copied by Victoria. The study was then locked from inside using the copied key, which was removed through a tiny gap in the old door frame — a detail only someone with intimate knowledge of the house would know.",
    sequenceOfEvents: [
      "Victoria and Eleanor plan the murder over several weeks after Harold discovers the overbilling and threatens to report Eleanor.",
      "Victoria obtains a copy of the study key from Harold's key ring.",
      "Eleanor harvests digitalis from the manor's foxglove garden and processes it using the garden mortar.",
      "On the evening of March 15, Eleanor visits Harold for a 'routine check-up' and confronts him about the overbilling accusation. Harold confirms he will report her.",
      "Eleanor leaves at 8:15 PM. Victoria texts her: 'He knows. We need to move tonight.'",
      "Marcus arrives and argues with Harold, then leaves at 8:30 PM — but returns later to retrieve his jacket (his phone gap suggests this).",
      "Doris serves Harold brandy at 8:40 PM and leaves. The study door is closed but not locked.",
      "Victoria waits until the house is quiet. At approximately 10:00 PM, she enters the study using her copied key. Harold is alive, drinking his brandy.",
      "Victoria administers the digitalis to the brandy using a syringe (this is when the poison enters — explaining why no foreign fingerprints are on the glass; she used a syringe, not direct contact).",
      "Harold drinks more of the poisoned brandy and dies around 11:00 PM from cardiac arrhythmia.",
      "Victoria locks the study door from the inside using the copied key, then removes the key through the door frame gap.",
      "Victoria returns to her bedroom and searches 'how long does poison take to work' at 10:15 PM — this is actually BEFORE the poison fully takes effect, showing her anxiety.",
      "Marcus's return at 10:12 PM (seen on CCTV) is unrelated to the murder — he came back to get his jacket and saw something in the hallway that scared him, which is why he left his jacket behind and texted Danny 'Bad night.'",
    ],
    keyEvidenceIds: ["EVIDENCE-11", "EVIDENCE-07", "EVIDENCE-12", "EVIDENCE-04"],
    redHerringIds: ["EVIDENCE-08", "EVIDENCE-09"],
    fullNarrative:
      "Dr. Eleanor Reeves and Victoria Ashworth conspired to murder Harold Ashworth. Eleanor had been overbilling Harold for years, and when he discovered this and threatened to report her to the medical board, she faced losing her medical license. Victoria, who was having a secret relationship with Eleanor, saw an opportunity to inherit Harold's entire estate. Together, they planned the murder using digitalis derived from the manor's foxglove garden. On the evening of March 15, Eleanor administered the poison to Harold's brandy after Doris served it. Victoria used a copied key to lock the study door from inside and remove the key through a door frame gap. The 'locked room' was an elaborate staging to suggest suicide or an impossible crime. Marcus's presence was coincidental — he returned for his jacket and witnessed something that frightened him into silence.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};

export const allCases: Case[] = [lockedRoomCase];
