import { Case } from "@/types";

export const midtownArsonCase: Case = {
  metadata: {
    id: "CASE-003",
    title: "The Midtown Arson",
    description:
      "A three-alarm fire engulfed the 12th floor of the Kellner Building at 2:15 AM on a Tuesday. One person was found dead — the night security guard. The fire was ruled arson. Accelerant traces found. The building was scheduled for demolition in 30 days. Insurance payout: $47 million. The developer, the tenant, the insurance broker, and the union rep all had reason to want that building burning.",
    difficulty: "hard",
    location: "Kellner Building, 450 West 34th Street, Midtown Manhattan",
    date: "September 3, 2024",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "arson",
  },
  victim: {
    name: "Frank Bellini",
    age: 61,
    occupation: "Night Security Guard",
    description:
      "Retired firefighter turned security guard. Worked the night shift at the Kellner Building for 4 years. Well-liked, no enemies. His shift was supposed to end at 6 AM. He was found in the stairwell on the 11th floor, killed by smoke inhalation before the fire reached that level.",
    causeOfDeath: "Smoke inhalation — unconscious before fire reached his location",
    lastSeen: "2:05 AM on security camera in the ground floor lobby",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Gregory Kellner",
      age: 52,
      occupation: "Real Estate Developer",
      relationshipToVictim: "Building Owner",
      motive:
        "The $47M insurance payout is worth more than the building's current value. The demolition was facing delays from the tenant's lease dispute. If the building burned before demolition, the insurance claim would be cleaner.",
      alibi: "I was at home in Greenwich, Connecticut. My wife can confirm.",
      alibiVerified: false,
      knownLocations: [
        "Home in Greenwich, CT",
        "Developer's office in Midtown",
      ],
      communicationHistory: [
        "8:00 PM — Called insurance broker Martin Hale (7 min)",
        "1:45 AM — Called his assistant: 'Make sure the demolition crew is ready for next week'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-05", "EVIDENCE-10"],
      suspicionScore: 72,
      personality:
        "Polished, ambitious, treats buildings as numbers on a spreadsheet. Genuine charm but zero sentimentality about property or people.",
      secrets: [
        "Has a second insurance policy not disclosed to the primary carrier",
        "Was in financial trouble — three other projects failing",
        "Met with a known arson-for-hire intermediary two weeks before the fire",
      ],
      truthfulStatements: [
        "The building was scheduled for demolition.",
        "The insurance payout was $47 million.",
      ],
      lies: [
        "I had no financial motive. (He was facing bankruptcy without the payout)",
        "I was in Greenwich all night. (Phone towers show his phone near the Kellner Building at 1:30 AM)",
      ],
      refusesToDiscuss: [
        "The second insurance policy",
        "The meeting with the intermediary",
        "His financial situation",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Rachel Stein",
      age: 39,
      occupation: "Tenant — Tech Startup CEO",
      relationshipToVictim: "Leaseholder, 12th floor",
      motive:
        "Rachel's startup was evicted when the demolition was announced. She had 60 days to vacate but no new location secured. If the building burned, the demolition would be delayed and she could claim insurance as a displaced tenant.",
      alibi: "I was at a tech conference in Austin. I flew back that morning.",
      alibiVerified: true,
      knownLocations: [
        "Austin Convention Center (verified by conference badge scan)",
        "Hilton Austin (hotel keycard records)",
      ],
      communicationHistory: [
        "7:30 PM — Texted her CTO: 'We need to find space by Friday or we're done'",
        "11:00 PM — Called her lawyer about the eviction",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-07"],
      suspicionScore: 40,
      personality:
        "Intense, driven, fighting for her company's survival. Not above bending rules but has a line she won't cross. She is genuinely grieving Frank — he always held the door open for her team.",
      secrets: [
        "Hired someone to sabotage the demolition equipment (non-violent)",
        "Has a key to the 12th floor from before eviction",
      ],
      truthfulStatements: [
        "I was at the conference in Austin.",
        "I did not want the building to burn.",
        "I was being evicted.",
      ],
      lies: [
        "I returned my keycard after the eviction notice. (She kept a copy of the 12th floor keycard)",
      ],
      refusesToDiscuss: [
        "The demolition equipment sabotage",
        "The keycard she kept",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Martin Hale",
      age: 48,
      occupation: "Insurance Broker",
      relationshipToVictim: "Brokered the Kellner Building policy",
      motive:
        "Martin earns a 3% commission on the policy — $1.41 million if the claim pays out. He also has a side arrangement with Kellner for referrals on other buildings. The more claims that pay, the more business flows his way.",
      alibi: "I was at a charity gala until midnight. Then home in Westchester.",
      alibiVerified: false,
      knownLocations: [
        "Plaza Hotel (gala, until midnight)",
        "Home in Westchester",
        "Kellner Building — visited 3 days before fire",
      ],
      communicationHistory: [
        "8:07 PM — Call from Kellner (7 min) — discussed policy renewal",
        "9:00 PM — Texted his wife: 'Leaving the gala early, tired'",
        "12:30 AM — Called Kellner (missed call, no voicemail)",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-06", "EVIDENCE-09"],
      suspicionScore: 58,
      personality:
        "Smooth-talking, numbers-oriented, morally flexible within the boundaries of 'what everyone does.' Would never get his hands dirty but facilitates those who will.",
      secrets: [
        "Advised Kellner on how to maximize the insurance claim",
        "Visited the Kellner Building 3 days before the fire and was seen near the basement electrical room",
        "Has a personal gambling problem — $200K in debt",
      ],
      truthfulStatements: [
        "I did broker the policy.",
        "I spoke to Kellner that evening.",
        "I was at the gala.",
      ],
      lies: [
        "I went straight home after the gala. (His phone shows he drove through Midtown at 12:45 AM)",
        "I have no financial interest in the claim beyond my commission. (He has a side deal with Kellner)",
      ],
      refusesToDiscuss: [
        "The basement visit",
        "His gambling debts",
        "The side arrangement with Kellner",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Tommy 'Bricks' Rourke",
      age: 44,
      occupation: "Union Representative — Building Trades",
      relationshipToVictim: "Represented demolition crew workers",
      motive:
        "The demolition crew was promised $2.1M for the project. If the building burned, the cleanup contract (hazardous materials, structural assessment) would add another $800K in union wages. Tommy personally benefits from the extended timeline.",
      alibi: "I was at the union hall until 10 PM. Then home in Brooklyn.",
      alibiVerified: false,
      knownLocations: [
        "Union Hall, Lower Manhattan",
        "Home in Brooklyn",
        "Construction site (afternoon)",
      ],
      communicationHistory: [
        "10:15 PM — Texted a demolition crew member: 'Sit tight, something's coming'",
        "2:30 AM — Called union lawyer (no answer)",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-08", "EVIDENCE-11"],
      suspicionScore: 55,
      personality:
        "Blue-collar, loyal to his workers, distrusts developers. Uses tough language but genuinely cares about his crew's livelihoods. Has a history of aggressive negotiations.",
      secrets: [
        "Was approached by Kellner to 'help' with the demolition timeline",
        "Has connections to people who do 'off-the-books' work",
        "Was at the construction site the afternoon of the fire — removing accelerant-resistant materials from storage",
      ],
      truthfulStatements: [
        "The crew was promised $2.1M.",
        "I was at the union hall until 10 PM.",
      ],
      lies: [
        "I had nothing to do with the fire. (He was approached by Kellner and has been in contact about the demolition)",
        "I went straight home after the union hall. (His car was spotted near the Kellner Building at 1:00 AM)",
      ],
      refusesToDiscuss: [
        "The conversation with Kellner",
        "The afternoon visit to the site",
        "His 'off-the-books' connections",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Maria Santos",
      age: 31,
      occupation: "24-Hour Deli Worker",
      relationshipToVictim: "Works across the street from Kellner Building",
      statement:
        "Around 1:30 AM I saw a dark SUV parked on the south side of the building for about 20 minutes. A man got out, went toward the building's loading dock area, and came back about 10 minutes later. The SUV left east on 34th Street. I didn't see the plate — it was dark.",
      reliability: "medium",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-05"],
      personality: "Alert, works odd hours, doesn't want trouble with anyone.",
    },
    {
      id: "WITNESS-02",
      name: "Derek Osei",
      age: 27,
      occupation: "NYFD Fire Investigator",
      relationshipToVictim: "Lead arson investigator",
      statement:
        "The point of origin was the 12th floor electrical room. Accelerant (gasoline-based) was used. The fire spread was consistent with multiple ignition points. The stairwell fire door on the 11th floor was propped open with a fire extinguisher — this allowed smoke to reach Frank Bellini. This was deliberate. Someone wanted Frank dead or wanted him unable to respond.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-04", "EVIDENCE-12"],
      personality: "Methodical, authoritative, outraged at the killing of a fellow first responder.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "12th Floor Electrical Room",
      type: "Room",
      address: "Kellner Building, 12th Floor",
      description:
        "The fire's point of origin. Contains the floor's electrical panel, backup generators, and a storage closet with old office equipment. Door was locked but the lock was bypassed.",
      relevantEvidence: ["EVIDENCE-03", "EVIDENCE-04"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-03"],
    },
    {
      id: "LOC-02",
      name: "Ground Floor Lobby",
      type: "Room",
      address: "Kellner Building, Ground Floor",
      description:
        "Contains the security desk, visitor log, and main elevator bank. Frank Bellini's last known location before the fire.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-12"],
      relevantSuspects: [],
    },
    {
      id: "LOC-03",
      name: "Loading Dock",
      type: "Exterior",
      address: "Kellner Building, South Side",
      description:
        "The building's loading dock, accessible from 33rd Street. Used for deliveries. Has a secondary entrance to the basement.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-05"],
      relevantSuspects: ["SUSPECT-01"],
    },
    {
      id: "LOC-04",
      name: "11th Floor Stairwell",
      type: "Corridor",
      address: "Kellner Building, 11th Floor",
      description:
        "Where Frank Bellini was found. The fire door was propped open, allowing smoke to fill the stairwell. Frank was wearing his gear but was overcome before he could reach an exit.",
      relevantEvidence: ["EVIDENCE-04", "EVIDENCE-12"],
      relevantSuspects: [],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-003",
      title: "Loading Dock CCTV — Dark SUV",
      category: "cctv",
      description:
        "Loading dock camera shows a dark SUV arriving at 1:32 AM. A figure exits, approaches the loading dock door (which was unlocked), enters the building for 8 minutes, and returns to the vehicle. The camera's resolution is too low to identify the person, but the vehicle matches a 2021 Ford Explorer — Gregory Kellner drives one.",
      timestamp: "2024-09-03T01:32:00",
      location: "Loading Dock",
      source: "Building Security Camera",
      reliability: "medium",
      metadata: {
        Vehicle: "Dark SUV — 2021 Ford Explorer (possible match)",
        TimeInBuilding: "8 minutes",
        ID: "Unidentifiable — low resolution",
        CameraAngle: "South-facing, partially obstructed",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-003",
      title: "Frank Bellini — Security Camera Last Appearance",
      category: "cctv",
      description:
        "Lobby camera shows Frank at 2:05 AM doing his rounds. He appears calm, not alarmed. He walks toward the stairwell on the east side. He does not appear on any camera after this. The stairwell camera on the 11th floor shows the door was already propped open when he would have arrived.",
      timestamp: "2024-09-03T02:05:00",
      location: "Ground Floor Lobby",
      source: "Building Security Camera",
      reliability: "high",
      metadata: {
        LastSeen: "2:05 AM — walking toward east stairwell",
        Demeanor: "Calm, routine patrol",
        StairwellDoor: "Already propped open",
        FireAlarm: "Triggered at 2:15 AM",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-003",
      title: "Arson Investigation — Accelerant Analysis",
      category: "forensic",
      description:
        "Gasoline-based accelerant found at three ignition points on the 12th floor: the electrical room, the east hallway, and the stairwell landing. The fire door on the 11th floor was propped with a fire extinguisher. The accelerant was standard pump-grade gasoline — available at any gas station.",
      timestamp: "2024-09-03T08:00:00",
      location: "12th Floor",
      source: "NYFD Arson Investigation",
      reliability: "high",
      metadata: {
        Accelerant: "Gasoline (pump-grade)",
        IgnitionPoints: "3 — electrical room, east hallway, stairwell",
        DoorPropped: "11th floor fire door — fire extinguisher",
        Trail: "Gasoline trail from electrical room to stairwell",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-003",
      title: "11th Floor Stairwell — Fire Door Analysis",
      category: "forensic",
      description:
        "The fire extinguisher used to prop the door was from the 12th floor equipment closet — not the 11th. This means someone carried it from the 12th floor to the 11th to prop the door open. Fingerprints on the extinguisher: smudged, partially recovered — partial print matches Martin Hale's right index finger.",
      timestamp: "2024-09-03T10:00:00",
      location: "11th Floor Stairwell",
      source: "Forensic Analysis",
      reliability: "high",
      metadata: {
        ExtinguisherOrigin: "12th floor equipment closet",
        Fingerprints: "Partial — Martin Hale (right index)",
        DoorState: "Propped open from 12th floor side",
        Conclusion: "Deliberately disabled to allow smoke passage",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-003",
      title: "Gregory Kellner — Phone Tower Records",
      category: "digital",
      description:
        "Kellner's phone pinged a tower near the Kellner Building at 1:28 AM and again at 1:48 AM. His home tower in Greenwich shows his phone was not there during this window. His phone was at the Greenwich tower from 10:00 PM to 1:15 AM, then moved to the Midtown tower, then returned to Greenwich by 2:15 AM.",
      timestamp: "2024-09-03T01:28:00",
      location: "Mobile Network",
      source: "Phone Carrier Records",
      reliability: "high",
      metadata: {
        HomeTower: "Greenwich, CT — 10:00 PM to 1:15 AM",
        MidtownTower: "1:28 AM to 1:48 AM",
        ReturnHome: "Greenwich tower by 2:15 AM",
        Gap: "Midtown presence during fire preparation",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-003",
      title: "Martin Hale — Gala Departure & Drive",
      category: "digital",
      description:
        "Gala records show Martin's badge was scanned out at 11:58 PM. His car (a black BMW) was captured on traffic cameras heading east on 42nd Street at 12:05 AM, then south on 8th Avenue at 12:15 AM — consistent with driving toward the Kellner Building area. His home in Westchester is north, not east.",
      timestamp: "2024-09-03T00:05:00",
      location: "Manhattan Streets",
      source: "Traffic Camera Network",
      reliability: "high",
      metadata: {
        GalaExit: "11:58 PM",
        CarDirection: "East on 42nd, south on 8th — toward Kellner",
        HomeDirection: "North — inconsistent with route",
        Car: "Black BMW 5 Series",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-003",
      title: "Rachel Stein — Austin Conference Verification",
      category: "document",
      description:
        "Rachel Stein's conference badge was scanned at 2:30 AM CST (3:30 AM EST) for a late-night networking event in Austin. She was also captured on the hotel's lobby camera at 10:00 PM CST returning to her room. Flight records confirm she flew from Austin to JFK, landing at 11:00 AM on September 3.",
      timestamp: "2024-09-03T03:30:00",
      location: "Austin, TX",
      source: "Conference + Hotel Records",
      reliability: "high",
      metadata: {
        BadgeScan: "2:30 AM CST (3:30 AM EST)",
        HotelCamera: "10:00 PM CST",
        Flight: "Austin to JFK — 11:00 AM arrival",
        DistanceFromNYC: "1,500 miles",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: [],
      isRedHerring: false,
      importance: 6,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-003",
      title: "Tommy Rourke — Union Hall Security",
      category: "cctv",
      description:
        "Union hall security camera shows Tommy leaving at 9:45 PM. His car (a red Dodge Ram) was captured on a traffic camera at 1:05 AM on 11th Avenue near 34th Street — four blocks from the Kellner Building. His phone was also in the area at that time.",
      timestamp: "2024-09-03T01:05:00",
      location: "Near Kellner Building",
      source: "Traffic Camera + Phone Records",
      reliability: "medium",
      metadata: {
        UnionHallExit: "9:45 PM",
        CarLocation: "11th Ave at 34th — 4 blocks from Kellner",
        PhoneLocation: "Same area",
        Time: "1:05 AM — 27 minutes before fire",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-003",
      title: "Martin Hale — Kellner Building Visit (3 days prior)",
      category: "cctv",
      description:
        "Building security shows Martin Hale visiting the Kellner Building on August 31 — 3 days before the fire. He signed in as 'insurance inspection' but was seen on the basement camera near the electrical room, not the upper floors. He spent 22 minutes in the basement.",
      timestamp: "2024-08-31T14:00:00",
      location: "Kellner Building Basement",
      source: "Building Security Camera",
      reliability: "high",
      metadata: {
        StatedPurpose: "Insurance inspection (upper floors)",
        ActualLocation: "Basement — near electrical systems",
        Duration: "22 minutes",
        Camera: "Basement hallway — north corridor",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-003",
      title: "Kellner's Second Insurance Policy",
      category: "document",
      description:
        "A secondary insurance policy was discovered, taken out 6 months before the fire with a different carrier. This policy covers an additional $12 million in 'contents and structural improvements' — none of which existed in the building. The broker on this policy: Martin Hale.",
      timestamp: "2024-09-04T09:00:00",
      location: "Insurance Records",
      source: "Insurance Fraud Investigation",
      reliability: "high",
      metadata: {
        SecondaryPolicy: "$12 million",
        Carrier: "Atlantic Underwriters",
        Broker: "Martin Hale",
        ContentsClaimed: "Non-existent improvements",
        TakenOut: "6 months before fire",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-003",
      title: "Tommy's Text — 'Sit Tight'",
      category: "digital",
      description:
        "Tommy texted demolition crew member Rick Delgado at 10:15 PM on September 2: 'Sit tight, something's coming.' Delgado's phone was near the Kellner Building that night. Tommy later claimed this referred to union negotiations, but Delgado has a prior conviction for arson.",
      timestamp: "2024-09-02T22:15:00",
      location: "Digital Communication",
      source: "Phone Records",
      reliability: "medium",
      metadata: {
        From: "Tommy Rourke",
        To: "Rick Delgado",
        Message: "Sit tight, something's coming",
        DelgadoRecord: "Prior arson conviction (2018)",
        DelgadoPhone: "Near Kellner Building night of fire",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-08"],
      isRedHerring: true,
      importance: 6,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-003",
      title: "Frank Bellini — Personal Effects",
      category: "object",
      description:
        "Frank was found with a personal notebook. His last entry (September 2, 11:00 PM) reads: 'Strange visitor today — the insurance guy in the basement. Told him to leave, he said he had an appointment with management. Filed report with building manager. No response.' This report was never filed.",
      timestamp: "2024-09-02T23:00:00",
      location: "11th Floor Stairwell",
      source: "Victim's Personal Effects",
      reliability: "high",
      metadata: {
        Entry: "Insurance guy seen in basement",
        Time: "September 2, 11:00 PM",
        Action: "Reported to building manager",
        Response: "No response received",
        ReportFiled: "Claimed but not found in records",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-09", "EVIDENCE-04"],
      isRedHerring: false,
      importance: 9,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "21:00",
      date: "2024-09-02",
      description: "Frank Bellini begins his night shift.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "21:30",
      date: "2024-09-02",
      description: "Martin Hale visits the Kellner Building (basement).",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "21:52",
      date: "2024-09-02",
      description: "Frank notices Martin in the basement and confronts him.",
      evidenceIds: ["EVIDENCE-12"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-04",
      timestamp: "22:15",
      date: "2024-09-02",
      description: "Tommy texts Delgado: 'Sit tight, something's coming.'",
      evidenceIds: ["EVIDENCE-11"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "23:00",
      date: "2024-09-02",
      description: "Frank writes in his notebook about the insurance man.",
      evidenceIds: ["EVIDENCE-12"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "00:05",
      date: "2024-09-03",
      description: "Martin Hale's car seen driving toward Kellner Building.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "01:05",
      date: "2024-09-03",
      description: "Tommy's car spotted 4 blocks from the Kellner Building.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "01:28",
      date: "2024-09-03",
      description: "Kellner's phone pings Midtown tower.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "01:32",
      date: "2024-09-03",
      description: "Dark SUV arrives at loading dock. Figure enters building.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "01:40",
      date: "2024-09-03",
      description: "Figure returns to SUV. Vehicle departs east on 34th.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "01:45",
      date: "2024-09-03",
      description:
        "11th floor fire door propped open with 12th floor extinguisher.",
      evidenceIds: ["EVIDENCE-04"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-04",
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "01:48",
      date: "2024-09-03",
      description: "Kellner's phone leaves Midtown tower.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "02:00",
      date: "2024-09-03",
      description:
        "Accelerant ignited at three points on 12th floor (estimated).",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-14",
      timestamp: "02:05",
      date: "2024-09-03",
      description: "Frank Bellini last seen on lobby camera, walking to stairwell.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "02:10",
      date: "2024-09-03",
      description:
        "Smoke reaches 11th floor through propped door. Frank is overcome.",
      evidenceIds: ["EVIDENCE-04", "EVIDENCE-12"],
      suspectIds: [],
      verified: false,
    },
    {
      id: "TL-16",
      timestamp: "02:15",
      date: "2024-09-03",
      description: "Fire alarm triggers. Three-alarm fire declared.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-17",
      timestamp: "02:15",
      date: "2024-09-03",
      description: "Kellner's phone back in Greenwich tower.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Kellner stated: 'I was in Greenwich all night. My wife can confirm.'",
      contradictingEvidenceId: "EVIDENCE-05",
      suspectId: "SUSPECT-01",
      confidence: 91,
      explanation:
        "Phone tower records show Kellner's phone was in Midtown Manhattan from 1:28 AM to 1:48 AM — 30 minutes before the fire was set. His phone left the Greenwich tower at 1:15 AM and returned by 2:15 AM. His wife may not have noticed his absence during those hours.",
    },
    {
      id: "CONT-02",
      statementText:
        "Martin Hale stated: 'I went straight home after the gala.'",
      contradictingEvidenceId: "EVIDENCE-06",
      suspectId: "SUSPECT-03",
      confidence: 87,
      explanation:
        "Traffic cameras show his car heading toward the Kellner Building at 12:05 AM and 12:15 AM — east and south, not north toward Westchester. His route is inconsistent with going home.",
    },
    {
      id: "CONT-03",
      statementText:
        "Tommy Rourke stated: 'I had nothing to do with the fire.'",
      contradictingEvidenceId: "EVIDENCE-08",
      suspectId: "SUSPECT-04",
      confidence: 76,
      explanation:
        "Tommy's car and phone were near the Kellner Building at 1:05 AM — 27 minutes before the fire. He claimed he was at home in Brooklyn, but the traffic camera and phone tower data contradict this.",
    },
    {
      id: "CONT-04",
      statementText:
        "Martin Hale stated: 'I have no financial interest in the claim beyond my commission.'",
      contradictingEvidenceId: "EVIDENCE-10",
      suspectId: "SUSPECT-03",
      confidence: 93,
      explanation:
        "Martin brokered a secondary $12 million insurance policy for Kellner covering non-existent improvements. This creates a massive financial incentive for him personally — the combined commissions from both policies are substantial, and he would earn from any fraud settlement.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-01",
    motive:
      "Gregory Kellner was facing bankruptcy — three failed developments and $8M in debts. He orchestrated the arson to claim $59M in combined insurance payouts ($47M primary + $12M secondary). He used Martin Hale's greed (commission incentives) and Tommy Rourke's connections (Demolition delay = more union work) to create a network of people with overlapping motives, muddying the investigation. Kellner entered the building through the loading dock, set the accelerant on the 12th floor, and propped the stairwell door. Frank Bellini was not supposed to die — he was supposed to be on the ground floor. But Frank's routine patrol took him to the stairwell, and the propped door allowed smoke to kill him. Kellner didn't plan for a murder investigation.",
    sequenceOfEvents: [
      "Kellner meets with Martin Hale to discuss maximizing insurance value. Hale suggests the secondary policy.",
      "Kellner hires Tommy Rourke's off-the-books crew to prepare the building — removing fire suppressants from the 12th floor.",
      "Frank Bellini spots Martin Hale in the basement on Sept 2 and reports it. The report is ignored.",
      "On the night of Sept 2-3, Kellner drives from Greenwich to Manhattan at 1:15 AM.",
      "Tommy Rourke is positioned nearby as a lookout and backup.",
      "Kellner enters through the loading dock at 1:32 AM with gasoline canisters.",
      "He sets accelerant at three points on the 12th floor and props the 11th floor stairwell door.",
      "He exits at 1:40 AM and drives back to Greenwich.",
      "The accelerant is ignited at approximately 2:00 AM (timer mechanism).",
      "Frank Bellini, on routine patrol, enters the stairwell at 2:05 AM and is overcome by smoke from the propped door.",
      "The fire alarm sounds at 2:15 AM. Three-alarm response.",
      "Kellner arrives home and his wife believes he never left.",
    ],
    keyEvidenceIds: ["EVIDENCE-05", "EVIDENCE-04", "EVIDENCE-01", "EVIDENCE-10"],
    redHerringIds: ["EVIDENCE-11"],
    fullNarrative:
      "Gregory Kellner, facing financial ruin, planned to burn the Kellner Building for $59M in combined insurance payouts. He recruited Martin Hale to structure the secondary policy and served as the insurance 'expert' who could legitimize the claim. He used Tommy Rourke's union connections to prepare the building and create a lookout presence. On the night of September 2-3, Kellner personally entered the building through the loading dock, set gasoline accelerant at three ignition points on the 12th floor, and propped the 11th floor stairwell door to disable the fire barrier. Security guard Frank Bellini was not part of the plan — his routine patrol took him into the stairwell just as smoke filled it through the propped door. Kellner's greed turned an insurance fraud into a murder case. Martin Hale's partial fingerprint on the fire extinguisher and his secret visit to the basement 3 days prior suggest he may have helped prepare the 11th floor door in advance, but Kellner was the one who set the fire.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
