import { Case } from "@/types";

export const museumHeistCase: Case = {
  metadata: {
    id: "CASE-005",
    title: "The Museum Heist",
    description:
      "Three paintings worth $42M were stolen from the Whitmore Museum of Art during a private after-hours event. The heist was discovered at 11:45 PM when the night guard found empty frames. The security system was active but recorded a 17-minute blackout from 10:52 PM to 11:09 PM. 12 people were at the event. The alarm never triggered. Inside job.",
    difficulty: "hard",
    location: "Whitmore Museum of Art, 82nd & Fifth Avenue, New York",
    date: "December 20, 2024",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "theft",
  },
  victim: {
    name: "The Whitmore Museum",
    age: 0,
    occupation: "Cultural Institution",
    description:
      "A prestigious museum housing a $500M collection. Founded in 1923. The three stolen paintings are from the museum's most valuable wing. Insurance covers 80% of the value, but the reputational damage could threaten the museum's upcoming capital campaign.",
    causeOfDeath: "Theft — $42M in artwork",
    lastSeen: "Paintings last seen on security camera at 10:50 PM",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Helena Cross",
      age: 45,
      occupation: "Museum Curator — Head of European Art",
      relationshipToVictim: "15-year employee, senior curator",
      motive:
        "Helena was passed over for director last month. She also has a secret arrangement with a private collector who has been buying stolen art. She knows the security system intimately and has after-hours access to every room.",
      alibi: "I was in the east wing gallery socializing with donors until 10:30 PM. Then I went to my office to get my coat.",
      alibiVerified: false,
      knownLocations: [
        "East Wing Gallery (until 10:30 PM)",
        "Curator's Office (claimed 10:30-10:45 PM)",
        "West Wing (where paintings were — no alibi for this period)",
      ],
      communicationHistory: [
        "10:15 PM — Texted an unknown number: 'The east wing camera loop is ready'",
        "10:30 PM — Called her personal phone from office (3 min — no one answered)",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-04", "EVIDENCE-09"],
      suspicionScore: 82,
      personality:
        "Sophisticated, passionate about art, bitter about being overlooked. Her knowledge of the collection is unmatched. She sees the art world as corrupted by money but participates in it anyway.",
      secrets: [
        "Has been selling forgeries to a private collector and replacing originals",
        "Knows the exact wiring of the security system",
        "Has a spare key to the conservation lab where restoration tools could cut paintings from frames",
      ],
      truthfulStatements: [
        "I was in the east wing gallery until 10:30 PM.",
        "I was passed over for director.",
      ],
      lies: [
        "I went straight to my office after 10:30 PM. (Security gap shows she had 15 unaccounted minutes)",
        "I have no connection to the art black market. (Text message evidence contradicts this)",
      ],
      refusesToDiscuss: [
        "The unknown number she texted",
        "The security system details",
        "Her relationship with private collectors",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Victor Hamill",
      age: 38,
      occupation: "Museum Security Director",
      relationshipToVictim: "Head of security for 5 years",
      motive:
        "Victor is $180K in debt from a divorce settlement. He designed the current security system and is the only one who can create a blind spot without triggering alerts. He also has insurance as a beneficiary — $200K if the museum makes a successful claim.",
      alibi: "I was monitoring the security feed in my office. I stepped out at 11:00 PM for a bathroom break.",
      alibiVerified: false,
      knownLocations: [
        "Security office (until 11:00 PM)",
        "Bathroom (claimed 11:00-11:10 PM)",
      ],
      communicationHistory: [
        "10:50 PM — Texted his ex-wife: 'It's almost done. You'll get your payment.'",
        "11:15 PM — Called museum director: 'We have a problem.'",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05", "EVIDENCE-10"],
      suspicionScore: 75,
      personality:
        "Professional, methodical,resentful about the divorce. Views the security system as his creation. Would be capable of orchestrated theft but would need help removing the art.",
      secrets: [
        "Created the 17-minute security blackout using a firmware update he scheduled",
        "Has been selling copies of security footage to art thieves",
        "The bathroom break was a cover for initiating the blackout sequence",
      ],
      truthfulStatements: [
        "I was in the security office until 11:00 PM.",
        "I designed the security system.",
      ],
      lies: [
        "I took a normal bathroom break at 11:00 PM. (He initiated the blackout remotely from the bathroom)",
        "I have no idea how the blackout happened. (He scheduled a 'firmware update' that disabled recording)",
        "I didn't tell my ex-wife anything about the heist. (Text evidence suggests she was aware)",
      ],
      refusesToDiscuss: [
        "The firmware update",
        "His ex-wife's payment",
        "The security footage sales",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Isla Fontaine",
      age: 28,
      occupation: "Art Restoration Specialist",
      relationshipToVictim: "Contract restorer for the museum",
      motive:
        "Isla is an undocumented immigrant working under a false identity. If exposed, she faces deportation. A private collector offered her $500K to facilitate the theft — she has the skills to remove paintings from frames without damage, which is critical for resale value.",
      alibi: "I was at the event as a guest. I left at 10:45 PM.",
      alibiVerified: false,
      knownLocations: [
        "Event reception (until 10:45 PM)",
        "Conservation lab (accessed at 10:55 PM per badge log)",
      ],
      communicationHistory: [
        "9:00 PM — Texted her sister: 'Tonight I secure our future'",
        "10:48 PM — Called an unlisted number (2 min)",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-06", "EVIDENCE-11"],
      suspicionScore: 68,
      personality:
        "Talented, desperate, caught between loyalty to the museum and survival. Her technical skills make her the only person who could remove the paintings intact. She hates what she's doing but sees no other way.",
      secrets: [
        "Has the tools and skills to remove paintings cleanly",
        "Used her conservation lab access during the blackout",
        "The unlisted number belongs to the private collector",
      ],
      truthfulStatements: [
        "I was at the event until 10:45 PM.",
        "I have conservation tools in the lab.",
      ],
      lies: [
        "I left the building at 10:45 PM. (Badge log shows her entering conservation lab at 10:55 PM)",
        "I don't know anything about the theft. (She accessed the lab during the blackout window)",
      ],
      refusesToDiscuss: [
        "The unlisted number she called",
        "Her identity documents",
        "The conservation lab access",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Raymond Whitmore III",
      age: 62,
      occupation: "Museum Board Chairman / Whitmore Family Heir",
      relationshipToVictim: "Board chairman and family descendant",
      motive:
        "Raymond's family trust is broke. He's been embezzling from the museum's operating fund to maintain his lifestyle. The theft allows him to claim insurance proceeds to cover the embezzlement, and the under-insurance on the paintings means the museum would need a bailout — which the family trust could provide at high interest.",
      alibi: "I was at the event the entire evening. I gave the closing toast at 11:00 PM.",
      alibiVerified: true,
      knownLocations: [
        "Event reception (entire evening)",
        "Main hall (closing toast at 11:00 PM)",
      ],
      communicationHistory: [
        "8:00 PM — Texted his financial advisor: 'After tonight, the fund is balanced'",
        "9:30 PM — Called an art dealer in Geneva (4 min)",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-07", "EVIDENCE-12"],
      suspicionScore: 50,
      personality:
        "Old money charm masking financial desperation. Sees himself as the museum's savior and believes the theft is a necessary evil to save the institution.",
      secrets: [
        "Has been embezzling $200K/year from the museum for 3 years",
        "Arranged the under-insurance policy personally",
        "The Geneva art dealer is connected to the private collector",
      ],
      truthfulStatements: [
        "I was at the event the entire evening.",
        "I gave the closing toast at 11:00 PM.",
      ],
      lies: [
        "I had no involvement in the theft. (His embezzlement created the motive, and he facilitated the under-insurance)",
        "The insurance policy was set by the board. (He personally negotiated the 80% coverage, knowing it was below value)",
      ],
      refusesToDiscuss: [
        "The museum's financial state",
        "The embezzlement",
        "The insurance policy details",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Tom Harris",
      age: 35,
      occupation: "Night Security Guard",
      relationshipToVictim: "Guard on duty the night of the heist",
      statement:
        "I did my rounds at 10:45 PM — everything was fine. I was in the lobby checking the front door cameras when the monitors went to static at 10:52 PM. I thought it was a glitch. I tried to call Victor but he didn't answer. The feeds came back at 11:09 PM. I did my next round at 11:30 PM and found the empty frames in the west wing. I immediately called 911 and Victor.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-05"],
      personality: "Dutiful, new to the job, confused and scared by the incident.",
    },
    {
      id: "WITNESS-02",
      name: "Dr. Nadia Petrova",
      age: 52,
      occupation: "Donor / Art Collector",
      relationshipToVictim: "Major donor attending the private event",
      statement:
        "I saw Helena leave the east wing around 10:30 PM, heading west. I thought nothing of it — she's the curator. Around 10:50 PM I saw Isla near the conservation lab corridor, looking nervous. She told me she was looking for the restroom.",
      reliability: "medium",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-06"],
      personality: "Observant art world insider, enjoys knowing everyone's business.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "West Wing Gallery",
      type: "Gallery",
      address: "Whitmore Museum, West Wing, 2nd Floor",
      description:
        "Houses the museum's most valuable paintings. Three empty frames remain. The paintings were removed with professional precision — no damage to frames or canvas mounting.",
      relevantEvidence: ["EVIDENCE-03", "EVIDENCE-05"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-03"],
    },
    {
      id: "LOC-02",
      name: "Security Office",
      type: "Room",
      address: "Whitmore Museum, Ground Floor",
      description:
        "Victor's office with multiple monitor screens, server racks, and the security system control panel. Contains the firmware update scheduler.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-10"],
      relevantSuspects: ["SUSPECT-02"],
    },
    {
      id: "LOC-03",
      name: "Conservation Lab",
      type: "Room",
      address: "Whitmore Museum, Lower Level",
      description:
        "Where paintings are restored. Contains professional tools for canvas removal, cleaning supplies, and a climate-controlled storage area. Badge-accessed.",
      relevantEvidence: ["EVIDENCE-06", "EVIDENCE-11"],
      relevantSuspects: ["SUSPECT-03"],
    },
    {
      id: "LOC-04",
      name: "Main Reception Hall",
      type: "Room",
      address: "Whitmore Museum, Ground Floor",
      description:
        "Where the private event was held. All 12 guests were present at various times throughout the evening.",
      relevantEvidence: ["EVIDENCE-04"],
      relevantSuspects: ["SUSPECT-04"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-005",
      title: "Helena's Text to Unknown Number",
      category: "message",
      description:
        "Helena's phone shows a text at 10:15 PM to an unsaved number: 'The east wing camera loop is ready.' The number traces to a prepaid phone purchased with cash at a bodega in the Bronx. The same phone received a call from Geneva at 9:30 PM — matching Raymond's call to the Geneva art dealer.",
      timestamp: "2024-12-20T22:15:00",
      location: "East Wing Gallery",
      source: "Phone Forensics",
      reliability: "high",
      metadata: {
        Text: "'The east wing camera loop is ready'",
        To: "Prepaid phone — Bronx purchase",
        GenevaCall: "9:30 PM — from Raymond's phone",
        Connection: "Prepaid phone linked to Geneva dealer",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-04", "EVIDENCE-09"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-005",
      title: "Security System — Firmware Update Log",
      category: "digital",
      description:
        "The security system's firmware update scheduler shows a manual override at 10:50 PM — 2 minutes before the blackout. The override was initiated from the security office terminal, but at 11:00 PM the terminal shows a login from the bathroom WiFi access point. Victor was the only one who left the security office during that window.",
      timestamp: "2024-12-20T22:50:00",
      location: "Security Office",
      source: "Security System Logs",
      reliability: "high",
      metadata: {
        FirmwareOverride: "10:50 PM — manual",
        InitiatedFrom: "Security office terminal",
        RemoteAccess: "11:00 PM — bathroom WiFi",
        BlackoutDuration: "17 minutes (10:52-11:09 PM)",
        VictorOnly: "Only person who left during window",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-05", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-005",
      title: "West Wing — Professional Removal Analysis",
      category: "forensic",
      description:
        "Art crime experts confirm the paintings were removed by someone with professional conservation training. The canvas was separated from the stretcher bars using a heated spatula — a tool found in the conservation lab. The removal left no damage, preserving resale value. Only a trained restorer could achieve this.",
      timestamp: "2024-12-21T09:00:00",
      location: "West Wing Gallery",
      source: "Art Crime Expert Analysis",
      reliability: "high",
      metadata: {
        RemovalMethod: "Heated spatula — conservation tool",
        SkillLevel: "Expert — museum-grade restoration",
        Damage: "None — preservation of resale value",
        ToolOrigin: "Conservation lab",
        Specialist: "Only a trained restorer could do this",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-06", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-005",
      title: "Event Guest List — Access Analysis",
      category: "document",
      description:
        "Of the 12 event guests, only 4 had after-hours badge access: Helena (curator), Victor (security), Raymond (board chairman), and Isla (restorer with special access). The other 8 guests were in the reception hall the entire time, verified by catering staff. The theft required badge access to the west wing and conservation lab.",
      timestamp: "2024-12-20T23:00:00",
      location: "Museum Records",
      source: "Badge Access + Catering Records",
      reliability: "high",
      metadata: {
        TotalGuests: "12",
        BadgeAccess: "4 — Helena, Victor, Raymond, Isla",
        VerifiedAlibi: "8 guests — reception hall all evening",
        WestWingAccess: "Helena, Victor, Raymond",
        ConservationLab: "Isla, Helena",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-03", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-005",
      title: "Victor's Text to Ex-Wife",
      category: "message",
      description:
        "Victor texted his ex-wife at 10:50 PM: 'It's almost done. You'll get your payment.' She responded at 10:52 PM: 'Don't screw this up.' The divorce settlement required Victor to pay $180K by January 1. He had no other means to make the payment.",
      timestamp: "2024-12-20T22:50:00",
      location: "Digital Communication",
      source: "Phone Records",
      reliability: "high",
      metadata: {
        To: "Ex-wife",
        Time: "10:50 PM",
        Message: "'It's almost done. You'll get your payment.'",
        Response: "'Don't screw this up.' — 10:52 PM",
        DivorceDebt: "$180K due January 1",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-005",
      title: "Conservation Lab — Badge Access Log",
      category: "digital",
      description:
        "Badge log shows Isla entered the conservation lab at 10:55 PM and exited at 11:12 PM. During this time, the lab's heated spatula was used (power consumption spike). Helena's badge was used to access the west wing at 11:05 PM — during the blackout window.",
      timestamp: "2024-12-20T22:55:00",
      location: "Conservation Lab + West Wing",
      source: "Badge Access System",
      reliability: "high",
      metadata: {
        IslaEntry: "10:55 PM — conservation lab",
        IslaExit: "11:12 PM — conservation lab",
        LabPower: "Heated spatula used during this window",
        HelenaWestWing: "11:05 PM — during blackout",
        BlackoutWindow: "10:52-11:09 PM",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-03"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-005",
      title: "Raymond's Geneva Call",
      category: "digital",
      description:
        "Raymond called a Geneva art dealer at 9:30 PM during the event. The dealer is known to handle 'clean' art for private buyers — a euphemism for laundered stolen artwork. The call lasted 4 minutes. Raymond's calendar shows no scheduled call with the dealer.",
      timestamp: "2024-12-20T21:30:00",
      location: "Main Reception Hall",
      source: "Phone Records",
      reliability: "high",
      metadata: {
        Called: "Geneva art dealer",
        Duration: "4 minutes",
        DealerKnown: "Handles laundered artwork",
        Scheduled: "No — unscheduled call",
        Time: "During event, 9:30 PM",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-005",
      title: "Museum Insurance Policy — Under-Insurance",
      category: "document",
      description:
        "The museum's insurance policy covers only 80% of the stolen paintings' value — unusual for a major museum, which typically carries 100% coverage. Raymond personally negotiated this policy 18 months ago. The board was not informed of the reduced coverage.",
      timestamp: "2024-12-21T08:00:00",
      location: "Insurance Records",
      source: "Policy Analysis",
      reliability: "high",
      metadata: {
        Coverage: "80% — $33.6M of $42M",
        NegotiatedBy: "Raymond Whitmore III",
        BoardAwareness: "Not informed of reduction",
        TypicalCoverage: "100% for major museums",
        PolicyDate: "18 months before heist",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-07"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-005",
      title: "East Wing Camera Loop — Analysis",
      category: "digital",
      description:
        "The east wing camera was running a looped recording during the event — showing an empty gallery. This loop was initiated at 10:15 PM, matching Helena's text. The loop concealed anyone entering the east wing during the event. The loop was eventually overwritten by the system restart after the firmware update.",
      timestamp: "2024-12-20T22:15:00",
      location: "East Wing Gallery",
      source: "Security System Forensics",
      reliability: "high",
      metadata: {
        LoopStarted: "10:15 PM",
        InitiatedBy: "Unknown — but matches Helena's text timing",
        Duration: "Overwritten at 11:09 PM by system restart",
        Content: "Empty gallery loop — concealed movement",
        HelenaText: "10:15 PM — 'camera loop is ready'",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-02"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-005",
      title: "Victor's Previous Security Footage Sales",
      category: "document",
      description:
        "IT audit reveals Victor has been copying and selling security camera footage to outside parties for 8 months. The buyers include known art theft associates. He earned approximately $45,000 from these sales. This establishes his willingness to compromise security for profit.",
      timestamp: "2024-12-01T00:00:00",
      location: "Museum IT Systems",
      source: "IT Security Audit",
      reliability: "high",
      metadata: {
        Duration: "8 months",
        SalesAmount: "$45,000",
        Buyers: "Art theft associates",
        Method: "USB copy of footage",
        Established: "History of security compromise",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-02"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-005",
      title: "Conservation Lab — Tool Inventory",
      category: "document",
      description:
        "The conservation lab's tool inventory shows a heated spatula, canvas stretching tools, and archival tissue paper are missing from their storage positions. These tools are specifically used for canvas removal and packaging for transport. Isla signed the last tool checkout log 3 days before the heist.",
      timestamp: "2024-12-17T00:00:00",
      location: "Conservation Lab",
      source: "Tool Inventory Records",
      reliability: "medium",
      metadata: {
        MissingTools: "Heated spatula, stretching tools, archival tissue",
        Purpose: "Canvas removal and transport packaging",
        LastCheckout: "Isla — 3 days before heist",
        InventoryDate: "Updated weekly",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-005",
      title: "Raymond's Financial Records — Embezzlement",
      category: "financial",
      description:
        "Forensic accounting reveals Raymond has been diverting $200K/year from the museum's operating fund to personal accounts over 3 years. Total embezzled: $600K. The theft and insurance claim would cover the shortfall. His Geneva call connects to the chain of buyers for the stolen art.",
      timestamp: "2024-12-20T00:00:00",
      location: "Financial Records",
      source: "Forensic Accounting",
      reliability: "high",
      metadata: {
        AnnualDiversion: "$200,000",
        Duration: "3 years",
        Total: "$600,000",
        Accounts: "Personal offshore accounts",
        InsuranceGap: "Would cover shortfall",
      },
      linkedSuspects: ["SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-07", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 8,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "19:00",
      date: "2024-12-20",
      description: "Private event begins. Guests arrive.",
      evidenceIds: ["EVIDENCE-04"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-04",
    },
    {
      id: "TL-02",
      timestamp: "21:00",
      date: "2024-12-20",
      description: "Helena confirms the camera loop is ready via text.",
      evidenceIds: ["EVIDENCE-01", "EVIDENCE-09"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "21:30",
      date: "2024-12-20",
      description: "Raymond calls Geneva art dealer from the event.",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-04",
      timestamp: "22:15",
      date: "2024-12-20",
      description: "Helena texts: 'The east wing camera loop is ready.'",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "22:30",
      date: "2024-12-20",
      description: "Helena leaves east wing, heads toward west wing.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "22:45",
      date: "2024-12-20",
      description: "Isla leaves the event, heads to conservation lab.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "22:50",
      date: "2024-12-20",
      description: "Victor initiates firmware override. Texts ex-wife.",
      evidenceIds: ["EVIDENCE-02", "EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "22:52",
      date: "2024-12-20",
      description: "Security blackout begins. All cameras stop recording.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "22:55",
      date: "2024-12-20",
      description: "Isla enters conservation lab. Retrieves tools.",
      evidenceIds: ["EVIDENCE-06", "EVIDENCE-11"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-03",
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "23:00",
      date: "2024-12-20",
      description: "Victor leaves security office, goes to bathroom.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "23:00",
      date: "2024-12-20",
      description: "Raymond gives closing toast at the event.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "23:05",
      date: "2024-12-20",
      description: "Helena accesses west wing with her badge.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "23:05",
      date: "2024-12-20",
      description: "Isla joins Helena in west wing with tools.",
      evidenceIds: ["EVIDENCE-03", "EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-14",
      timestamp: "23:05",
      date: "2024-12-20",
      description:
        "Paintings removed using heated spatula. Packaged for transport.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-15",
      timestamp: "23:09",
      date: "2024-12-20",
      description: "Security system restarts. Blackout ends.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-16",
      timestamp: "23:12",
      date: "2024-12-20",
      description: "Isla exits conservation lab.",
      evidenceIds: ["EVIDENCE-06"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-17",
      timestamp: "23:15",
      date: "2024-12-20",
      description: "Victor calls museum director: 'We have a problem.'",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-18",
      timestamp: "23:30",
      date: "2024-12-20",
      description: "Tom Harris discovers empty frames during his round.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: [],
      verified: true,
      locationId: "LOC-01",
    },
    {
      id: "TL-19",
      timestamp: "23:35",
      date: "2024-12-20",
      description: "911 called. Police arrive within minutes.",
      evidenceIds: [],
      suspectIds: [],
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Helena stated: 'I went straight to my office after 10:30 PM.'",
      contradictingEvidenceId: "EVIDENCE-06",
      suspectId: "SUSPECT-01",
      confidence: 90,
      explanation:
        "Badge logs show Helena accessed the west wing at 11:05 PM — during the blackout window. If she was in her office, she would not have needed to badge into the west wing. Her 15-minute gap between leaving the east wing and being seen in the west wing matches the time needed to prepare for the theft.",
    },
    {
      id: "CONT-02",
      statementText:
        "Victor stated: 'I took a normal bathroom break at 11:00 PM.'",
      contradictingEvidenceId: "EVIDENCE-02",
      suspectId: "SUSPECT-02",
      confidence: 93,
      explanation:
        "The security system shows a remote login from the bathroom WiFi at 11:00 PM — during the blackout window. Victor left the security office at exactly 11:00 PM and accessed the system remotely from the bathroom, confirming he maintained control of the blackout while establishing an alibi of being away from his desk.",
    },
    {
      id: "CONT-03",
      statementText:
        "Isla stated: 'I left the building at 10:45 PM.'",
      contradictingEvidenceId: "EVIDENCE-06",
      suspectId: "SUSPECT-03",
      confidence: 94,
      explanation:
        "Badge logs show Isla entered the conservation lab at 10:55 PM and exited at 11:12 PM. She did not leave the building — she went to the lab to retrieve the tools needed for the painting removal. Her text to her sister at 9:00 PM ('Tonight I secure our future') confirms premeditation.",
    },
    {
      id: "CONT-04",
      statementText:
        "Raymond stated: 'I had no involvement in the theft.'",
      contradictingEvidenceId: "EVIDENCE-12",
      suspectId: "SUSPECT-04",
      confidence: 82,
      explanation:
        "Raymond's 3-year embezzlement of $600K would be exposed by an audit. The theft and insurance claim would cover the shortfall. He personally negotiated the under-insurance policy and called the Geneva art dealer during the event. His financial motive and logistical connections create a clear conspiracy chain.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-01",
    motive:
      "Helena Cross orchestrated the heist as part of a long-term art fraud scheme. She had been replacing originals with forgeries for a private collector, but the three target paintings were too famous to replace. Instead, she arranged for them to be stolen and sold through the Geneva dealer connected to Raymond. Victor provided the security blackout as part of his debt settlement. Isla provided the technical skill to remove the paintings intact. Raymond facilitated the buyer connection and insurance manipulation. Helena was the mastermind — she knew the art, the security, and the buyers. The paintings are now in a private collection in the Middle East.",
    sequenceOfEvents: [
      "Helena has been selling forgeries through the private collector for 2 years.",
      "She identifies three paintings too valuable to replace — they must be stolen.",
      "She recruits Victor by offering him $200K to create the security blackout (resolving his debt).",
      "She recruits Isla by threatening to expose her undocumented status unless she assists.",
      "Raymond facilitates the buyer through the Geneva dealer, taking a 10% commission.",
      "On the night of December 20, Helena sets up the east wing camera loop at 10:15 PM.",
      "Victor initiates the firmware override at 10:50 PM, creating the 17-minute blackout.",
      "During the blackout, Helena and Isla enter the west wing.",
      "Isla removes the paintings with professional precision using tools from the conservation lab.",
      "The paintings are packaged and moved through a service exit during the blackout.",
      "Victor restarts the system at 11:09 PM, ending the blackout.",
      "The paintings are transported to a waiting vehicle and eventually shipped to Geneva.",
    ],
    keyEvidenceIds: ["EVIDENCE-01", "EVIDENCE-06", "EVIDENCE-02", "EVIDENCE-03"],
    redHerringIds: [],
    fullNarrative:
      "Helena Cross, the museum's head curator, orchestrated the $42M theft of three paintings by exploiting her intimate knowledge of the collection, the security system, and the art black market. She had been running a forgery scheme for 2 years and needed the originals stolen rather than replaced. She recruited Victor (financial desperation), Isla (immigration vulnerability), and Raymond (family connections) into a conspiracy. Victor created the 17-minute security blackout using a firmware override, Helena set up the east wing camera loop, Isla used her conservation skills to remove the paintings without damage, and Raymond connected the operation to international buyers through the Geneva art dealer. The four suspects each brought essential skills to the heist, but Helena's text message ('The east wing camera loop is ready') and her badge access to the west wing during the blackout are the threads that unravel the conspiracy.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
