import { Case } from "@/types";

export const vanishingHeiressCase: Case = {
  metadata: {
    id: "CASE-002",
    title: "The Vanishing Heiress",
    description:
      "22-year-old Lily Fontaine, sole heir to the Fontaine shipping fortune, vanished from her penthouse after a family dinner. Her phone was found on the balcony, her shoes by the door, and a half-packed suitcase on the bed. The penthouse was locked from inside. No signs of struggle. Four people were in the building that night. One of them knows where she went.",
    difficulty: "medium",
    location: "Fontaine Tower, Upper East Side, New York",
    date: "June 8, 2024",
    evidenceCount: 14,
    suspectCount: 4,
    witnessCount: 2,
    status: "unsolved",
    type: "missing_person",
  },
  victim: {
    name: "Lily Fontaine",
    age: 22,
    occupation: "Art History Student & Heiress",
    description:
      "Young heiress to the Fontaine shipping empire. Rebellious, independent, recently threatened to expose a family secret. Had a history of running away but always contacted a friend within 24 hours. This time, silence.",
    causeOfDeath: "Status: Missing — presumed alive at time of disappearance",
    lastSeen: "9:30 PM by her stepmother, entering her penthouse elevator",
  },
  suspects: [
    {
      id: "SUSPECT-01",
      name: "Nathaniel Fontaine",
      age: 58,
      occupation: "CEO, Fontaine Shipping",
      relationshipToVictim: "Father",
      motive:
        "Lily discovered Nathaniel had been embezzling from the company to cover gambling debts. She threatened to go public. The family trust would pass to Lily at 25 — in 3 years.",
      alibi: "I was in my study on the 40th floor the entire evening. I left the penthouse at 8:00 PM after dinner.",
      alibiVerified: false,
      knownLocations: [
        "Fontaine Tower — 40th Floor Study",
        "Penthouse (during dinner, until 8:00 PM)",
        "Private club earlier that day",
      ],
      communicationHistory: [
        "7:30 PM — Called company CFO (12 min)",
        "9:45 PM — Sent email to accountant: 'Move the Q3 figures before Monday'",
      ],
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-05", "EVIDENCE-10"],
      suspicionScore: 70,
      personality:
        "Controlled, calculating, project warmth but operates from fear. Deeply ashamed of his secrets. Would protect the family name at any cost.",
      secrets: [
        "Owes $2.1M to offshore lenders",
        "Hired a private investigator to monitor Lily's movements",
        "Has a second family in Montreal",
      ],
      truthfulStatements: [
        "I did leave the penthouse at 8:00 PM.",
        "Lily and I had disagreements about the company.",
      ],
      lies: [
        "I had no idea Lily was planning anything. (He found her packed suitcase earlier that day)",
        "I was working in my study all evening. (Security logs show his elevator moved at 9:40 PM)",
      ],
      refusesToDiscuss: [
        "The embezzlement",
        "His gambling debts",
        "The private investigator",
      ],
    },
    {
      id: "SUSPECT-02",
      name: "Camille Fontaine",
      age: 35,
      occupation: "Gallery Owner",
      relationshipToVictim: "Stepmother",
      motive:
        "Lily's trust fund includes the penthouse — Camille's primary residence. If Lily disappears before turning 25, control of the trust reverts to Nathaniel, and Camille retains her lifestyle.",
      alibi: "I said goodnight to Lily at 9:30 PM in the penthouse. I went to our bedroom on the 40th floor and read until sleep.",
      alibiVerified: false,
      knownLocations: [
        "Penthouse (until 9:30 PM)",
        "40th Floor Master Bedroom",
        "Gallery in Chelsea (afternoon)",
      ],
      communicationHistory: [
        "8:45 PM — Texted her gallery assistant: 'The Basquiat deal is done'",
        "10:00 PM — No phone activity recorded",
      ],
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-06", "EVIDENCE-08"],
      suspicionScore: 75,
      personality:
        "Charming on the surface, fiercely ambitious underneath. Treats Lily like an obstacle. Genuine affection buried under resentment.",
      secrets: [
        "Lily caught her selling a painting that belonged to Lily's deceased mother",
        "Has been slowly liquidating items from the penthouse",
        "Knows the building's service elevator codes",
      ],
      truthfulStatements: [
        "I did say goodnight to Lily at 9:30 PM.",
        "Lily and I did not always get along.",
      ],
      lies: [
        "I went straight to bed after saying goodnight. (CCTV shows her in the hallway at 10:15 PM near the service elevator)",
        "I have no reason to want Lily gone. (She benefits financially if Lily is declared missing)",
      ],
      refusesToDiscuss: [
        "The painting sale",
        "The service elevator access",
        "Her financial arrangements with Nathaniel",
      ],
    },
    {
      id: "SUSPECT-03",
      name: "Ethan Cross",
      age: 24,
      occupation: "Graduate Student / Lily's Boyfriend",
      relationshipToVictim: "Boyfriend (8 months)",
      motive:
        "Lily told Ethan she was leaving New York to expose her father. Ethan, who came from nothing, saw the Fontaine fortune as his way out. If Lily fled, the relationship — and his access to wealth — would end.",
      alibi: "I was at my apartment in Queens. I spoke to Lily at 7:00 PM on the phone for 20 minutes.",
      alibiVerified: true,
      knownLocations: [
        "Queens apartment (verified by roommate)",
        "Fontaine Tower lobby at 6:15 PM (CCTV)",
      ],
      communicationHistory: [
        "7:00 PM — Phone call with Lily (20 min)",
        "9:15 PM — Texted Lily: 'Be safe tonight. Love you.'",
        "11:00 PM — Texted Lily: 'You okay?'",
      ],
      evidenceConnections: ["EVIDENCE-03", "EVIDENCE-09"],
      suspicionScore: 35,
      personality:
        "Genuinely caring but insecure. Loves Lily but is intimidated by her world. Torn between supporting her and holding on.",
      secrets: [
        "Lily gave him a USB drive to hold 'just in case'",
        "He has a prior arrest for breaking and entering (expunged)",
      ],
      truthfulStatements: [
        "I was at my apartment all evening.",
        "Lily told me she was planning something big.",
        "I love Lily and want her found.",
      ],
      lies: [
        "I had no idea what she was planning. (She told him she was going to confront her father and then leave the city)",
      ],
      refusesToDiscuss: [
        "The USB drive's contents",
        "His prior arrest",
      ],
    },
    {
      id: "SUSPECT-04",
      name: "Raymond Tsai",
      age: 50,
      occupation: "Building Superintendent",
      relationshipToVictim: "Building staff for 15 years",
      motive:
        "Raymond has been paid by Nathaniel for years to monitor Lily's comings and goings. Recently, Lily discovered this and threatened to have him fired and evicted. Raymond's wife is terminally ill and he needs the income.",
      alibi: "I was in the super's office in the basement. I didn't leave the building all night.",
      alibiVerified: false,
      knownLocations: [
        "Basement super office",
        "Penthouse floor — closet (service access)",
      ],
      communicationHistory: [
        "8:00 PM — Called Nathaniel (3 min)",
        "10:30 PM — No phone activity",
      ],
      evidenceConnections: ["EVIDENCE-04", "EVIDENCE-07", "EVIDENCE-11"],
      suspicionScore: 55,
      personality:
        "Quiet, loyal to those who pay him. Conflicted between duty to the Fontaines and guilt over spying on a young woman. Practical above all.",
      secrets: [
        "Has master keys to every apartment in the building",
        "Was paid $2,000/month by Nathaniel to report Lily's movements",
        "Entered the penthouse floor at 10:20 PM to check on something for Nathaniel",
      ],
      truthfulStatements: [
        "I have been the super here for 15 years.",
        "Nathaniel asked me to keep an eye on Lily.",
      ],
      lies: [
        "I never left the basement that night. (His keycard accessed the penthouse floor at 10:20 PM)",
        "I didn't see anything unusual. (He heard voices on the penthouse floor but was told by Nathaniel to stay quiet)",
      ],
      refusesToDiscuss: [
        "The monthly payments from Nathaniel",
        "What he heard on the penthouse floor",
      ],
    },
  ],
  witnesses: [
    {
      id: "WITNESS-01",
      name: "Sandra Wu",
      age: 29,
      occupation: "Doorman / Front Desk",
      relationshipToVictim: "Front desk staff at Fontaine Tower for 3 years",
      statement:
        "I saw Mr. Fontaine leave the penthouse elevator at 8:05 PM. Camille came down at 8:20 PM to get wine from the cellar, went back up at 8:35 PM. Lily was seen on the penthouse camera at 9:28 PM entering the elevator with her father's briefcase — she brought it down and left it at the 40th floor lobby. She went back up. I didn't see anyone else use the penthouse elevator after 9:30 PM.",
      reliability: "high",
      evidenceConnections: ["EVIDENCE-01", "EVIDENCE-02", "EVIDENCE-12"],
      personality: "Observant, takes her job seriously, nervous about the family's power.",
    },
    {
      id: "WITNESS-02",
      name: "Diego Morales",
      age: 41,
      occupation: "Penthouse Neighbor (48th floor)",
      relationshipToVictim: "Neighbor, known Lily casually",
      statement:
        "Around 10:15 PM I heard what sounded like furniture moving above me — the penthouse is the floor above. Then maybe 10 minutes of silence. Then I heard the service elevator ding once. I thought nothing of it at the time.",
      reliability: "medium",
      evidenceConnections: ["EVIDENCE-02", "EVIDENCE-07"],
      personality: "Friendly, slightly nosy, doesn't want to get involved with the Fontaines.",
    },
  ],
  locations: [
    {
      id: "LOC-01",
      name: "Lily's Penthouse",
      type: "Apartment",
      address: "Fontaine Tower, 49th Floor, Upper East Side",
      description:
        "Lily's personal penthouse — a 3-bedroom unit with a wraparound balcony. Locks are smart-enabled (code + keycard). Door was found locked from inside with Lily's keycard in the slot.",
      relevantEvidence: ["EVIDENCE-01", "EVIDENCE-06", "EVIDENCE-12"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-04"],
    },
    {
      id: "LOC-02",
      name: "40th Floor Lobby",
      type: "Corridor",
      address: "Fontaine Tower, 40th Floor",
      description:
        "The family's private floor. Contains Nathaniel's study, master bedroom, and a shared sitting area. Has access to the main elevator and a service elevator.",
      relevantEvidence: ["EVIDENCE-05", "EVIDENCE-11"],
      relevantSuspects: ["SUSPECT-01", "SUSPECT-02", "SUSPECT-04"],
    },
    {
      id: "LOC-03",
      name: "Building Service Elevator",
      type: "Elevator",
      address: "Fontaine Tower, Internal",
      description:
        "A service elevator connecting all floors. Requires a separate keycard (staff access). Used by maintenance, delivery, and building staff. Logs all keycard swipes.",
      relevantEvidence: ["EVIDENCE-02", "EVIDENCE-07"],
      relevantSuspects: ["SUSPECT-02", "SUSPECT-04"],
    },
    {
      id: "LOC-04",
      name: "Superintendent's Office",
      type: "Room",
      address: "Fontaine Tower, Basement",
      description:
        "Raymond's workspace. Contains building logs, spare keys, and monitoring equipment for the building's camera system.",
      relevantEvidence: ["EVIDENCE-04", "EVIDENCE-11"],
      relevantSuspects: ["SUSPECT-04"],
    },
  ],
  evidence: [
    {
      id: "EVIDENCE-01",
      caseId: "CASE-002",
      title: "Penthouse Smart Lock Log",
      category: "digital",
      description:
        "The penthouse smart lock records: locked at 9:42 PM from inside (Lily's keycard). No subsequent unlocks until 6:00 AM when Nathaniel used his keycard to enter and 'discover' the empty penthouse. The balcony door sensor shows it was opened at 9:44 PM and closed at 9:48 PM.",
      timestamp: "2024-06-08T21:42:00",
      location: "Lily's Penthouse",
      source: "Smart Lock System",
      reliability: "high",
      metadata: {
        LockEvent: "Locked from inside — Lily's keycard",
        LockTime: "9:42 PM",
        BalconySensor: "Opened 9:44 PM, Closed 9:48 PM",
        NextUnlock: "6:00 AM — Nathaniel's keycard",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-06", "EVIDENCE-12"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-02",
      caseId: "CASE-002",
      title: "Service Elevator Keycard Log",
      category: "digital",
      description:
        "Service elevator keycard records for June 8: Camille swiped at 8:20 PM (to wine cellar) and 8:35 PM (return to 40th). Raymond swiped at 10:20 PM (penthouse floor). Unknown keycard at 10:25 PM (penthouse floor) — the log shows a staff keycard but doesn't identify which one. Raymond's card was used again at 10:32 PM (basement).",
      timestamp: "2024-06-08T22:20:00",
      location: "Service Elevator",
      source: "Building Access System",
      reliability: "high",
      metadata: {
        CamilleEntry: "8:20 PM (wine cellar)",
        CamilleReturn: "8:35 PM (40th floor)",
        RaymondEntry: "10:20 PM (penthouse floor)",
        UnknownEntry: "10:25 PM (penthouse floor) — staff keycard",
        RaymondReturn: "10:32 PM (basement)",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-07", "EVIDENCE-11"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-03",
      caseId: "CASE-002",
      title: "Lily's Phone — Final Calls & Messages",
      category: "digital",
      description:
        "Phone found on penthouse balcony. Last activity: 9:38 PM — outgoing text to Ethan: 'If I'm not back in 24 hours, give the drive to a lawyer. I love you.' Phone was wiped remotely at 10:05 PM using a factory reset command. The reset command came from an IP address traced to the building's WiFi — Nathaniel's study.",
      timestamp: "2024-06-08T22:05:00",
      location: "Penthouse Balcony",
      source: "Phone Forensics",
      reliability: "high",
      metadata: {
        LastText: "9:38 PM to Ethan — 'If I'm not back in 24 hours...'",
        RemoteWipe: "10:05 PM — factory reset",
        WipeOrigin: "Building WiFi — IP linked to 40th floor study",
        Device: "iPhone 15 Pro Max",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-09", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-04",
      caseId: "CASE-002",
      title: "Nathaniel's Payment Records to Raymond",
      category: "financial",
      description:
        "Bank records show Nathaniel has been paying Raymond $2,000/month via cash deposits for the last 3 years. The memo line reads 'building maintenance bonus.' Raymond's own bank records show these deposits started the month Lily moved into the penthouse.",
      timestamp: "2024-06-01T00:00:00",
      location: "Financial Records",
      source: "Bank Statement Analysis",
      reliability: "high",
      metadata: {
        MonthlyAmount: "$2,000",
        Duration: "3 years",
        Started: "Month Lily moved in",
        PaymentMethod: "Cash deposit",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-11"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-05",
      caseId: "CASE-002",
      title: "Penthouse Security Camera — Elevator",
      category: "cctv",
      description:
        "Elevator camera on penthouse floor: Lily enters at 9:28 PM carrying a briefcase (her father's). She exits on the 40th floor at 9:30 PM, leaves the briefcase in the lobby. Returns to penthouse elevator at 9:32 PM. She is alone both times. No one else uses the penthouse elevator until 6:00 AM.",
      timestamp: "2024-06-08T21:28:00",
      location: "Penthouse Elevator",
      source: "Security Camera",
      reliability: "high",
      metadata: {
        LilyUp: "9:28 PM — carrying briefcase",
        LilyExits40th: "9:30 PM — leaves briefcase",
        LilyReturns: "9:32 PM — alone",
        NextUse: "6:00 AM — Nathaniel",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-10"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-06",
      caseId: "CASE-002",
      title: "Penthouse Contents — Forensic Analysis",
      category: "forensic",
      description:
        "Lily's phone on balcony. Shoes by front door. Half-packed suitcase on bed — passport missing, $5,000 cash missing from her safe. No signs of struggle. A glass of wine on the nightstand (Lily's fingerprints). A second glass in the kitchen sink (two sets of fingerprints — Lily and one unidentified).",
      timestamp: "2024-06-09T08:00:00",
      location: "Lily's Penthouse",
      source: "Crime Scene Processing",
      reliability: "high",
      metadata: {
        Phone: "Balcony",
        Shoes: "Front door",
        Suitcase: "Half-packed, passport missing",
        CashMissing: "$5,000 from safe",
        GlassKitchen: "Two fingerprints — Lily + unknown",
        Struggle: "No signs",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-07",
      caseId: "CASE-002",
      title: "Diego's Witness Statement — Sound Analysis",
      category: "forensic",
      description:
        "Audio analysis of the penthouse floor: At 10:15 PM, sounds consistent with a rolling suitcase on hardwood floor. At 10:25 PM, a single voice (female, calm) speaking indistinctly. At 10:30 PM, the service elevator doors opening and closing.",
      timestamp: "2024-06-08T22:15:00",
      location: "48th Floor (below penthouse)",
      source: "Audio Forensics",
      reliability: "medium",
      metadata: {
        Sound1: "10:15 PM — rolling suitcase",
        Sound2: "10:25 PM — female voice",
        Sound3: "10:30 PM — service elevator",
        Equipment: "Spectrographic analysis",
      },
      linkedSuspects: ["SUSPECT-02", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-08"],
      isRedHerring: false,
      importance: 7,
    },
    {
      id: "EVIDENCE-08",
      caseId: "CASE-002",
      title: "Camille's Gallery Keycard Access",
      category: "digital",
      description:
        "Camille's gallery keycard shows she accessed the gallery at 11:30 PM on June 8 — unusual for a Saturday night when the gallery was closed. Security footage from the gallery shows her entering alone and retrieving a small painting from the back storage room. The painting is a portrait of Lily's late mother.",
      timestamp: "2024-06-08T23:30:00",
      location: "Fontaine Gallery, Chelsea",
      source: "Gallery Security System",
      reliability: "high",
      metadata: {
        AccessTime: "11:30 PM Saturday",
        Purpose: "Retrieved painting from storage",
        Painting: "Portrait of Lily's late mother",
        Witnessed: "Solo visit",
      },
      linkedSuspects: ["SUSPECT-02"],
      linkedEvidence: ["EVIDENCE-06"],
      isRedHerring: true,
      importance: 5,
    },
    {
      id: "EVIDENCE-09",
      caseId: "CASE-002",
      title: "Lily's Research History",
      category: "digital",
      description:
        "Lily's laptop (found in penthouse) shows recent searches: 'how to disappear legally,' 'new identity laws US,' 'fake passport consequences,' 'Swiss bank account without ID.' She also had documents open: a draft email to the SEC about Fontaine Shipping fraud, and a one-way ticket to Zurich booked under a pseudonym for June 10.",
      timestamp: "2024-06-08T18:00:00",
      location: "Lily's Penthouse",
      source: "Laptop Forensics",
      reliability: "high",
      metadata: {
        Searches: "Disappearing, fake IDs, Swiss banking",
        DraftEmail: "SEC complaint about Fontaine Shipping",
        PlaneTicket: "One-way to Zurich, June 10, pseudonym",
        TicketStatus: "Not yet purchased",
      },
      linkedSuspects: ["SUSPECT-03"],
      linkedEvidence: ["EVIDENCE-03"],
      isRedHerring: false,
      importance: 8,
    },
    {
      id: "EVIDENCE-10",
      caseId: "CASE-002",
      title: "Nathaniel's Study — Laptop Wipe History",
      category: "digital",
      description:
        "Nathaniel's study laptop shows a remote wipe command was issued at 10:05 PM targeting device 'LF-iPhone-15.' Nathaniel's browser history also shows searches at 9:50 PM: 'how to remotely erase iPhone' and 'track iPhone location remotely.' The laptop was in his study the entire evening.",
      timestamp: "2024-06-08T22:05:00",
      location: "40th Floor Study",
      source: "Laptop Forensics",
      reliability: "high",
      metadata: {
        RemoteWipe: "10:05 PM — Lily's iPhone",
        BrowserSearch: "9:50 PM — remote erase iPhone",
        DeviceLocation: "40th floor study",
        IP: "Matches building WiFi",
      },
      linkedSuspects: ["SUSPECT-01"],
      linkedEvidence: ["EVIDENCE-03"],
      isRedHerring: false,
      importance: 10,
    },
    {
      id: "EVIDENCE-11",
      caseId: "CASE-002",
      title: "Raymond's Keycard Anomaly",
      category: "document",
      description:
        "Building maintenance logs show Raymond was scheduled for a plumbing repair on the 35th floor at 10:00 PM. However, his keycard accessed the penthouse floor at 10:20 PM instead. The plumbing repair was never logged as completed. Raymond's work phone shows a text from Nathaniel at 9:55 PM: 'Check if she left anything behind.'",
      timestamp: "2024-06-08T22:20:00",
      location: "Building Records",
      source: "Maintenance Logs + Phone Records",
      reliability: "high",
      metadata: {
        ScheduledTask: "Plumbing repair, 35th floor, 10:00 PM",
        ActualAccess: "Penthouse floor, 10:20 PM",
        TaskCompleted: "No",
        TextFromNathaniel: "9:55 PM — 'Check if she left anything behind'",
      },
      linkedSuspects: ["SUSPECT-01", "SUSPECT-04"],
      linkedEvidence: ["EVIDENCE-02", "EVIDENCE-04"],
      isRedHerring: false,
      importance: 9,
    },
    {
      id: "EVIDENCE-12",
      caseId: "CASE-002",
      title: "Penthouse Balcony — Forensic Report",
      category: "forensic",
      description:
        "The penthouse balcony overlooks the building's internal courtyard. Height analysis: a person could lower themselves from the balcony to the 48th floor balcony (6 feet below) using the decorative railing. Scrape marks on the 49th floor balcony railing are fresh. No DNA found on the railing.",
      timestamp: "2024-06-09T10:00:00",
      location: "Penthouse Balcony",
      source: "Forensic Analysis",
      reliability: "high",
      metadata: {
        BalconyDrop: "6 feet to 48th floor",
        ScrapeMarks: "Fresh, on railing",
        DNA: "None recovered",
        Conclusion: "Balcony was used as exit route",
      },
      linkedSuspects: [],
      linkedEvidence: ["EVIDENCE-01", "EVIDENCE-06"],
      isRedHerring: false,
      importance: 10,
    },
  ],
  timeline: [
    {
      id: "TL-01",
      timestamp: "18:15",
      date: "2024-06-08",
      description: "Ethan visits the penthouse lobby, speaks to Lily briefly.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-03"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-02",
      timestamp: "19:00",
      date: "2024-06-08",
      description: "Family dinner begins in the penthouse dining room.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-01", "SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-03",
      timestamp: "19:30",
      date: "2024-06-08",
      description:
        "Lily confronts Nathaniel about the embezzlement during dinner. Argument.",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: ["SUSPECT-01", "SUSPECT-02"],
      locationId: "LOC-01",
      verified: false,
    },
    {
      id: "TL-04",
      timestamp: "19:50",
      date: "2024-06-08",
      description: "Nathaniel retreats to his study. Lily goes to her room.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-05",
      timestamp: "20:00",
      date: "2024-06-08",
      description: "Nathaniel leaves the penthouse, goes to 40th floor.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-06",
      timestamp: "20:15",
      date: "2024-06-08",
      description: "Camille goes to wine cellar for a bottle.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-07",
      timestamp: "20:20",
      date: "2024-06-08",
      description:
        "Camille returns to 40th floor. Lily is packing in her room.",
      evidenceIds: ["EVIDENCE-02", "EVIDENCE-09"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-08",
      timestamp: "21:00",
      date: "2024-06-08",
      description:
        "Lily's laptop research session on disappearing and the SEC complaint.",
      evidenceIds: ["EVIDENCE-09"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-09",
      timestamp: "21:28",
      date: "2024-06-08",
      description: "Lily takes Nathaniel's briefcase down to 40th floor.",
      evidenceIds: ["EVIDENCE-05"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-10",
      timestamp: "21:30",
      date: "2024-06-08",
      description: "Camille says goodnight to Lily in the penthouse.",
      evidenceIds: [],
      suspectIds: ["SUSPECT-02"],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-11",
      timestamp: "21:38",
      date: "2024-06-08",
      description: "Lily texts Ethan the critical message about the USB drive.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: ["SUSPECT-03"],
      verified: true,
    },
    {
      id: "TL-12",
      timestamp: "21:42",
      date: "2024-06-08",
      description: "Penthouse door locks from inside — Lily's keycard.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-13",
      timestamp: "21:44",
      date: "2024-06-08",
      description: "Balcony door opens for 4 minutes.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: [],
      locationId: "LOC-01",
      verified: true,
    },
    {
      id: "TL-14",
      timestamp: "22:00",
      date: "2024-06-08",
      description: "Nathaniel issues remote wipe on Lily's iPhone from his study.",
      evidenceIds: ["EVIDENCE-10"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-02",
      verified: true,
    },
    {
      id: "TL-15",
      timestamp: "22:05",
      date: "2024-06-08",
      description: "Lily's phone is remotely wiped.",
      evidenceIds: ["EVIDENCE-03"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-16",
      timestamp: "22:15",
      date: "2024-06-08",
      description:
        "Rolling suitcase sound heard from 48th floor. Diego's apartment.",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-17",
      timestamp: "22:20",
      date: "2024-06-08",
      description:
        "Raymond's keycard accesses penthouse floor per Nathaniel's instruction.",
      evidenceIds: ["EVIDENCE-11", "EVIDENCE-02"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-18",
      timestamp: "22:25",
      date: "2024-06-08",
      description: "Female voice heard indistinctly on penthouse floor.",
      evidenceIds: ["EVIDENCE-07"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-19",
      timestamp: "22:30",
      date: "2024-06-08",
      description: "Service elevator used — descent to lower floor.",
      evidenceIds: ["EVIDENCE-02", "EVIDENCE-07"],
      suspectIds: [],
      verified: true,
    },
    {
      id: "TL-20",
      timestamp: "22:32",
      date: "2024-06-08",
      description: "Raymond returns to basement.",
      evidenceIds: ["EVIDENCE-02"],
      suspectIds: ["SUSPECT-04"],
      verified: true,
    },
    {
      id: "TL-21",
      timestamp: "23:30",
      date: "2024-06-08",
      description:
        "Camille visits gallery alone — retrieves portrait of Lily's mother.",
      evidenceIds: ["EVIDENCE-08"],
      suspectIds: ["SUSPECT-02"],
      verified: true,
    },
    {
      id: "TL-22",
      timestamp: "06:00",
      date: "2024-06-09",
      description:
        "Nathaniel uses his keycard to enter penthouse. Discovers Lily missing.",
      evidenceIds: ["EVIDENCE-01"],
      suspectIds: ["SUSPECT-01"],
      locationId: "LOC-01",
      verified: true,
    },
  ],
  connections: [],
  contradictions: [
    {
      id: "CONT-01",
      statementText:
        "Nathaniel stated: 'I was working in my study the entire evening.'",
      contradictingEvidenceId: "EVIDENCE-10",
      suspectId: "SUSPECT-01",
      confidence: 92,
      explanation:
        "Nathaniel issued a remote wipe of Lily's phone at 10:05 PM from his study laptop. This is not 'working' — it is an active effort to destroy evidence of his daughter's communications.",
    },
    {
      id: "CONT-02",
      statementText:
        "Camille stated: 'I went straight to bed after saying goodnight at 9:30 PM.'",
      contradictingEvidenceId: "EVIDENCE-02",
      suspectId: "SUSPECT-02",
      confidence: 88,
      explanation:
        "Service elevator logs show Camille's keycard was NOT used for the penthouse floor at 10:15 PM, but Diego heard a female voice at 10:25 PM. More critically, Raymond's keycard and an unknown staff keycard accessed the penthouse floor at 10:20 and 10:25 PM. Camille's alibi of being in bed is contradicted by the timing — she may have used Raymond's keycard or another means.",
    },
    {
      id: "CONT-03",
      statementText:
        "Raymond stated: 'I never left the basement that night.'",
      contradictingEvidenceId: "EVIDENCE-11",
      suspectId: "SUSPECT-04",
      confidence: 95,
      explanation:
        "Raymond's keycard accessed the penthouse floor at 10:20 PM. Maintenance logs confirm he was scheduled for the 35th floor but went to the penthouse floor instead. The plumbing repair was never completed.",
    },
    {
      id: "CONT-04",
      statementText:
        "Raymond stated: 'I didn't see anything unusual.'",
      contradictingEvidenceId: "EVIDENCE-07",
      suspectId: "SUSPECT-04",
      confidence: 80,
      explanation:
        "Diego heard a female voice on the penthouse floor at 10:25 PM — the same time Raymond was there. Raymond must have either heard or seen whoever was speaking, yet he claims nothing unusual occurred.",
    },
  ],
  hiddenSolution: {
    guiltySuspectId: "SUSPECT-02",
    motive:
      "Camille orchestrated Lily's disappearance by staging it as a voluntary disappearance. She had been stealing from Lily's penthouse and feared exposure. Using her knowledge of the building's service elevator and Raymond's keycard (she obtained the code from Nathaniel during an argument), she entered the penthouse after Lily locked it, confronted Lily on the balcony, and coerced her into climbing down to the 48th floor. From there, she escorted Lily out through the service entrance using a staff keycard she had copied weeks earlier. Lily is alive — being held at a property Camille owns upstate, waiting for Camille to force her to sign over trust control.",
    sequenceOfEvents: [
      "Camille discovered Lily was planning to expose Nathaniel's fraud and leave the city.",
      "Camille feared that if Lily disappeared voluntarily, the trust investigation would uncover Camille's own theft of artwork.",
      "Camille copied a staff keycard weeks in advance using Raymond's keycard during a moment she borrowed it.",
      "During the argument at dinner, Camille realized tonight was the night Lily planned to flee.",
      "After saying goodnight, Camille waited in the 40th floor hallway.",
      "At 10:15 PM, Camille used the copied keycard to access the penthouse floor via the service elevator.",
      "She confronted Lily on the penthouse balcony, threatening to expose Lily's SEC complaint and pseudonym ticket if Lily didn't cooperate.",
      "Camille forced Lily to lower herself from the 49th floor balcony to the 48th floor (explaining the fresh scrape marks).",
      "Camille met Lily on the 48th floor and escorted her out through the service entrance.",
      "Lily's phone was remotely wiped by Nathaniel at 10:05 PM — he did this independently, thinking it would protect himself from the SEC complaint, not realizing Camille was acting simultaneously.",
      "Raymond arrived at 10:20 PM per Nathaniel's instruction and found the penthouse empty. He heard Camille and Lily on the floor but was told by Camille to stay silent.",
      "Camille staged the penthouse to look like Lily left voluntarily (packed suitcase, phone on balcony).",
      "Camille took the portrait of Lily's mother from the gallery as an emotional trophy — a reminder of her victory over the Fontaine family matriarchy.",
    ],
    keyEvidenceIds: ["EVIDENCE-02", "EVIDENCE-07", "EVIDENCE-12", "EVIDENCE-11"],
    redHerringIds: ["EVIDENCE-08", "EVIDENCE-09"],
    fullNarrative:
      "Lily Fontaine discovered her father Nathaniel was embezzling from the family company and planned to expose him to the SEC before fleeing to Switzerland. Her stepmother Camille, who had been quietly stealing art from Lily's penthouse, realized that a federal investigation would expose her thefts too. Camille staged Lily's disappearance as a voluntary flight — copying a staff keycard, confronting Lily on the penthouse balcony, and forcing her to climb down to the 48th floor before escorting her out through the service entrance. Nathaniel independently tried to cover his tracks by remotely wiping Lily's phone, not realizing Camille was executing her own plan simultaneously. Lily is alive but being held at Camille's upstate property, where Camille is pressuring her to sign over trust documents. Raymond, the superintendent, witnessed part of the events but stayed silent due to his financial dependence on Nathaniel.",
  },
  scoringRules: {
    correctSuspect: 25,
    correctMotive: 20,
    correctSequence: 20,
    correctEvidence: 20,
    contradictionsDiscovered: 10,
    totalContradictions: 4,
    hintPenalty: 5,
    timePenalty: 5,
    unnecessaryAccusationPenalty: 3,
  },
};
